// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package okta4ai

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &apiServerDataSource{}
	_ datasource.DataSourceWithConfigure = &apiServerDataSource{}
)

// ApiServerDataSource defines the data source implementation.
type apiServerDataSource struct {
	Config *config.Config
}

// ApiServerDataSourceModel describes the data source data model.
type apiServerDataSourceModel struct {
	ID          types.String                           `tfsdk:"id"`
	Created     types.String                           `tfsdk:"created"`
	LastUpdated types.String                           `tfsdk:"last_updated"`
	Metadata    *ApiServerDataSourceModelMetadataModel `tfsdk:"metadata"`
	Orn         types.String                           `tfsdk:"orn"`
	ResourceUrl types.String                           `tfsdk:"resource_url"`
	Status      types.String                           `tfsdk:"status"`
}

// ApiServerDataSourceModelMetadataModel is the nested model for metadata.
type ApiServerDataSourceModelMetadataModel struct {
	Description types.String `tfsdk:"description"`
	DisplayName types.String `tfsdk:"display_name"`
}

func NewApiServerDataSource() datasource.DataSource {
	return &apiServerDataSource{}
}

func (d *apiServerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_api_server"
}

func (d *apiServerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *apiServerDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a third-party API server by ID",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the api_server.",
				Required:            true,
			},
			"created": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the resource server was created",
				Computed:            true,
			},
			"last_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the resource server was last updated",
				Computed:            true,
			},
			"orn": schema.StringAttribute{
				MarkdownDescription: "The [ORN](https://developer.",
				Computed:            true,
			},
			"resource_url": schema.StringAttribute{
				MarkdownDescription: "The URL of the resource server",
				Computed:            true,
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "Current status of the resource server in its lifecycle",
				Computed:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"metadata": schema.SingleNestedBlock{
				Description: "Metadata about the resource server.",
				Attributes: map[string]schema.Attribute{
					"description": schema.StringAttribute{
						Description: "Description of the resource server",
						Computed:    true,
					},
					"display_name": schema.StringAttribute{
						Description: "Human-readable display name for the resource server",
						Computed:    true,
					},
				},
			},
		},
	}
}

func (d *apiServerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state apiServerDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.Okta4AIClient.Okta4AISDKClient()
	id := state.ID.ValueString()
	result, httpResp, err := client.ApiServerRegistrationAPI.GetApiServer(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "api_server with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading api_server", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	if t := result.GetCreated(); !t.IsZero() {
		state.Created = types.StringValue(t.Format(time.RFC3339))
	}
	if t := result.GetLastUpdated(); !t.IsZero() {
		state.LastUpdated = types.StringValue(t.Format(time.RFC3339))
	}
	state.Orn = types.StringValue(string(result.GetOrn()))
	state.ResourceUrl = types.StringValue(string(result.GetResourceUrl()))
	state.Status = types.StringValue(string(result.GetStatus()))
	if metadataRaw0, ok := result.GetMetadataOk(); ok {
		metadataModel0 := &ApiServerDataSourceModelMetadataModel{}
		metadataModel0.Description = types.StringValue(string(metadataRaw0.GetDescription()))
		metadataModel0.DisplayName = types.StringValue(string(metadataRaw0.GetDisplayName()))
		state.Metadata = metadataModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
