// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package okta4ai

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &clientAuthSettingDataSource{}
	_ datasource.DataSourceWithConfigure = &clientAuthSettingDataSource{}
)

// ClientAuthSettingDataSource defines the data source implementation.
type clientAuthSettingDataSource struct {
	Config *config.Config
}

// ClientAuthSettingDataSourceModel describes the data source data model.
type clientAuthSettingDataSourceModel struct {
	ID                     types.String                                             `tfsdk:"id"`
	AuthorizationServerOrn types.String                                             `tfsdk:"authorization_server_orn"`
	ClientCredentials      *ClientAuthSettingDataSourceModelClientCredentialsModel  `tfsdk:"client_credentials"`
	Created                types.String                                             `tfsdk:"created"`
	LastUpdated            types.String                                             `tfsdk:"last_updated"`
	Name                   types.String                                             `tfsdk:"name"`
	OauthConfiguration     *ClientAuthSettingDataSourceModelOauthConfigurationModel `tfsdk:"oauth_configuration"`
	Protocol               types.String                                             `tfsdk:"protocol"`
	Purpose                types.List                                               `tfsdk:"purpose"`
	ResourceOrn            types.String                                             `tfsdk:"resource_orn"`
}

// ClientAuthSettingDataSourceModelClientCredentialsModel is the nested model for client_credentials.
type ClientAuthSettingDataSourceModelClientCredentialsModel struct {
	ClientId types.String `tfsdk:"client_id"`
}

// ClientAuthSettingDataSourceModelOauthConfigurationModel is the nested model for oauth_configuration.
type ClientAuthSettingDataSourceModelOauthConfigurationModel struct {
	Scopes types.List `tfsdk:"scopes"`
}

func NewClientAuthSettingDataSource() datasource.DataSource {
	return &clientAuthSettingDataSource{}
}

func (d *clientAuthSettingDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_client_auth_setting"
}

func (d *clientAuthSettingDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *clientAuthSettingDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves client authentication settings for a resource server.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the client_auth_setting.",
				Required:            true,
			},
			"authorization_server_orn": schema.StringAttribute{
				MarkdownDescription: "The [ORN](https://developer.",
				Computed:            true,
			},
			"created": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the client authentication settings were created",
				Computed:            true,
			},
			"last_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the client authentication settings were last updated",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "A human-readable name for this client authentication settings connection.",
				Computed:            true,
			},
			"protocol": schema.StringAttribute{
				MarkdownDescription: "The authentication protocol used for this connection.",
				Computed:            true,
			},
			"purpose": schema.ListAttribute{
				MarkdownDescription: "The purpose of the client authentication settings.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"resource_orn": schema.StringAttribute{
				MarkdownDescription: "The [ORN](https://developer.",
				Computed:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"client_credentials": schema.SingleNestedBlock{
				Description: "Client credentials in response (no secrets returned)",
				Attributes: map[string]schema.Attribute{
					"client_id": schema.StringAttribute{
						Description: "OAuth client ID",
						Optional:    true,
						Computed:    true,
					},
				},
			},
			"oauth_configuration": schema.SingleNestedBlock{
				Description: "OAuth protocol configuration for the connection.",
				Attributes: map[string]schema.Attribute{
					"scopes": schema.ListAttribute{
						Description: "OAuth scopes to request when obtaining tokens.",
						ElementType: types.StringType,
						Optional:    true,
						Computed:    true,
					},
				},
			},
		},
	}
}

func (d *clientAuthSettingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state clientAuthSettingDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.Okta4AIClient.Okta4AISDKClient()
	id := state.ID.ValueString()
	result, httpResp, err := client.ResourceServerClientAuthSettingsAPI.GetClientAuthSettings(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "client_auth_setting with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading client_auth_setting", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	state.AuthorizationServerOrn = types.StringValue(string(result.GetAuthorizationServerOrn()))
	if t := result.GetCreated(); !t.IsZero() {
		state.Created = types.StringValue(t.Format(time.RFC3339))
	}
	if t := result.GetLastUpdated(); !t.IsZero() {
		state.LastUpdated = types.StringValue(t.Format(time.RFC3339))
	}
	state.Name = types.StringValue(string(result.GetName()))
	state.Protocol = types.StringValue(string(result.GetProtocol()))
	state.ResourceOrn = types.StringValue(string(result.GetResourceOrn()))
	if clientCredentialsRaw0, ok := result.GetClientCredentialsOk(); ok {
		clientCredentialsModel0 := &ClientAuthSettingDataSourceModelClientCredentialsModel{}
		clientCredentialsModel0.ClientId = types.StringValue(string(clientCredentialsRaw0.GetClientId()))
		state.ClientCredentials = clientCredentialsModel0
	}
	if oauthConfigurationRaw0, ok := result.GetOauthConfigurationOk(); ok {
		oauthConfigurationModel0 := &ClientAuthSettingDataSourceModelOauthConfigurationModel{}
		{
			listVal, listDiags := types.ListValueFrom(ctx, types.StringType, oauthConfigurationRaw0.GetScopes())
			resp.Diagnostics.Append(listDiags...)
			oauthConfigurationModel0.Scopes = listVal
		}
		state.OauthConfiguration = oauthConfigurationModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
