// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package okta4ai

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta4AI "github.com/okta4AI/okta4AI-for-ai-sdk-golang/v1"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &aiAgentResource{}
	_ resource.ResourceWithConfigure   = &aiAgentResource{}
	_ resource.ResourceWithImportState = &aiAgentResource{}
)

// AiAgentResource defines the resource implementation.
type aiAgentResource struct {
	Config *config.Config
}

// AiAgentModel describes the resource data model.
type aiAgentModel struct {
	ID          types.String              `tfsdk:"id"`
	Created     types.String              `tfsdk:"created"`
	LastUpdated types.String              `tfsdk:"last_updated"`
	Profile     *AiAgentModelProfileModel `tfsdk:"profile"`
	Status      types.String              `tfsdk:"status"`
	ResourceUrl types.String              `tfsdk:"resource_url"`
}

// AiAgentModelProfileModel is the nested model for profile.
type AiAgentModelProfileModel struct {
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
}

func NewAiAgentResource() resource.Resource {
	return &aiAgentResource{}
}

func (r *aiAgentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ai_agent"
}

func (r *aiAgentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *aiAgentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The AI Agent Registrations API provides registration and lifecycle management operations for AI agents.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the AI agent was created",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the AI agent was updated",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Description: "When an AI agent is created, it's in the `STAGED` status.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"resource_url": schema.StringAttribute{
				Description: "The resource URL for the agent-to-agent (A2A) server associated with this AI agent.",
				Optional:    true,
				Sensitive:   true,
			},
		},
		Blocks: map[string]schema.Block{
			"profile": schema.SingleNestedBlock{
				Description: "AI agent profile",
				Attributes: map[string]schema.Attribute{
					"description": schema.StringAttribute{
						Description: "Description of the AI agent",
						Optional:    true,
					},
					"name": schema.StringAttribute{
						Description: "Unique name of the AI agent",
						Optional:    true,
					},
				},
			},
		},
	}
}
func (r *aiAgentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *aiAgentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state aiAgentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.Okta4AIClient.Okta4AISDKClient()
	result, httpResp, err := client.AgentRegistrationAPI.GetAIAgent(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading ai_agent", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.Status = types.StringValue(string(result.GetStatus()))
	if profileRaw0, ok := result.GetProfileOk(); ok && state.Profile != nil {
		profileModel0 := &AiAgentModelProfileModel{}
		profileModel0.Description = types.StringValue(string(profileRaw0.GetDescription()))
		profileModel0.Name = types.StringValue(string(profileRaw0.GetName()))
		state.Profile = profileModel0
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *aiAgentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan aiAgentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.Okta4AIClient.Okta4AISDKClient()

	// Build request body from plan
	createReq := client.AgentRegistrationAPI.RegisterAIAgent(ctx)
	body := okta4AI.NewCreateAIAgentRequestWithDefaults()
	if plan.Profile != nil {
		nestedProfile := okta4AI.NewAIAgentProfileWithDefaults()
		if !plan.Profile.Description.IsNull() && !plan.Profile.Description.IsUnknown() {
			nestedProfile.SetDescription(plan.Profile.Description.ValueString())
		}
		if !plan.Profile.Name.IsNull() && !plan.Profile.Name.IsUnknown() {
			nestedProfile.SetName(plan.Profile.Name.ValueString())
		}
		body.SetProfile(*nestedProfile)
	}
	body.SetResourceUrl(plan.ResourceUrl.ValueString())
	createReq = createReq.Body(*body)
	httpResp, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating ai_agent", err.Error())
		return
	}

	// Extract operation ID from Location header
	locationURL := httpResp.Header.Get("Location")
	parts := strings.Split(locationURL, "/")
	operationID := parts[len(parts)-1]

	// Poll the operation until completion with exponential backoff
	timeout := time.After(5 * time.Minute)
	ticker := time.NewTicker(1 * time.Second)
	backoffDuration := 1 * time.Second
	const maxBackoffDuration = 2 * time.Second
	defer ticker.Stop()

	var operationResult interface{}
	for {
		select {
		case <-timeout:
			resp.Diagnostics.AddError("Timeout waiting for ai_agent operation", "Operation did not complete within 5 minutes")
			return
		case <-ctx.Done():
			resp.Diagnostics.AddError("Context cancelled", "Waiting for ai_agent operation was cancelled")
			return
		case <-ticker.C:
			// Decode response body directly to check status
			opResp, _, opErr := client.WorkloadPrincipalOperationsAPI.GetWorkloadPrincipalOperation(ctx, operationID).Execute()
			if opErr != nil {
				resp.Diagnostics.AddError("Error polling ai_agent operation status", opErr.Error())
				return
			}

			// Parse response JSON to check status field
			var respJSON map[string]interface{}
			bodyBytes, _ := json.Marshal(opResp)
			if err := json.Unmarshal(bodyBytes, &respJSON); err == nil {
				if status, ok := respJSON["status"]; ok {
					statusStr := fmt.Sprintf("%v", status)
					if statusStr == "COMPLETED" {
						operationResult = opResp
						break
					} else if statusStr == "FAILED" {
						resp.Diagnostics.AddError("ai_agent operation failed", "The async operation failed to complete")
						return
					}
				}
			}

			// Apply exponential backoff for next poll
			backoffDuration = time.Duration(float64(backoffDuration) * 1.5)
			if backoffDuration > maxBackoffDuration {
				backoffDuration = maxBackoffDuration
			}
			ticker.Stop()
			ticker = time.NewTicker(backoffDuration)
		}
		if operationResult != nil {
			break
		}
	}

	// Extract resource from operation response
	if operationResult == nil {
		resp.Diagnostics.AddError("Async operation error", "Operation polling completed but returned no result")
		return
	}
	opResp := operationResult.(*okta4AI.WorkloadPrincipalOperationResponse)
	if resource := opResp.Resource; resource != nil {
		plan.ID = types.StringValue(string(resource.GetId()))
	} else {
		resp.Diagnostics.AddError("Async operation error", "Operation completed but returned no resource")
		return
	}

	// Fetch computed fields from the resource to ensure created/updated timestamps are available
	id := plan.ID.ValueString()
	readResult, _, readErr := client.AgentRegistrationAPI.GetAIAgent(ctx, id).Execute()
	if readErr == nil {
		plan.Created = types.StringValue(readResult.GetCreated().Format(time.RFC3339))
		plan.LastUpdated = types.StringValue(readResult.GetLastUpdated().Format(time.RFC3339))
		plan.Status = types.StringValue(string(readResult.GetStatus()))
		if profileRaw0, ok := readResult.GetProfileOk(); ok && plan.Profile != nil {
			profileModel0 := &AiAgentModelProfileModel{}
			profileModel0.Description = types.StringValue(string(profileRaw0.GetDescription()))
			profileModel0.Name = types.StringValue(string(profileRaw0.GetName()))
			plan.Profile = profileModel0
		}

	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *aiAgentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan aiAgentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state aiAgentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.Okta4AIClient.Okta4AISDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.AgentRegistrationAPI.ReplaceAIAgent(ctx, id)
	updateBody := okta4AI.NewUpdateAIAgentRequestWithDefaults()
	if plan.Profile != nil {
		nestedProfile := okta4AI.NewAIAgentProfileWithDefaults()
		if !plan.Profile.Description.IsNull() && !plan.Profile.Description.IsUnknown() {
			nestedProfile.SetDescription(plan.Profile.Description.ValueString())
		}
		if !plan.Profile.Name.IsNull() && !plan.Profile.Name.IsUnknown() {
			nestedProfile.SetName(plan.Profile.Name.ValueString())
		}
		updateBody.SetProfile(*nestedProfile)
	}
	updateReq = updateReq.Body(*updateBody)
	_, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating ai_agent", err.Error())
		return
	}
	// Update returns no body; preserve ID from state.
	// No response body — copy all plan fields back to state (including write-only).
	state.Created = plan.Created
	state.LastUpdated = plan.LastUpdated
	state.Profile = plan.Profile
	state.Status = plan.Status
	state.ResourceUrl = plan.ResourceUrl

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *aiAgentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state aiAgentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.Okta4AIClient.Okta4AISDKClient()
	httpResp, err := client.AgentRegistrationAPI.DeleteAIAgent(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting ai_agent", err.Error())
		return
	}
}
