// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &usersClassificationDataSource{}
	_ datasource.DataSourceWithConfigure = &usersClassificationDataSource{}
)

// UsersClassificationDataSource defines the data source implementation.
type usersClassificationDataSource struct {
	Config *config.Config
}

// UsersClassificationItemModel is one element returned by the list endpoint.
type usersClassificationItemModel struct {
	ID          types.String `tfsdk:"id"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Type        types.String `tfsdk:"type"`
}

// UsersClassificationDataSourceModel describes the data source data model.
type usersClassificationDataSourceModel struct {
	ID     types.String                   `tfsdk:"id"`
	UserId types.String                   `tfsdk:"user_id"`
	Items  []usersClassificationItemModel `tfsdk:"items"`
}

func NewUsersClassificationDataSource() datasource.DataSource {
	return &usersClassificationDataSource{}
}

func (d *usersClassificationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users_classification"
}

func (d *usersClassificationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *usersClassificationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a user's classification",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the users_classification.",
				Optional:            true,
				Computed:            true,
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "ID of an existing Okta user",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of users_classification items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"last_updated": schema.StringAttribute{
							MarkdownDescription: "The timestamp when the user classification was last updated",
							Computed:            true,
						},
						"type": schema.StringAttribute{
							MarkdownDescription: "The type of user classification",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *usersClassificationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state usersClassificationDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		userId := state.UserId.ValueString()
		results, httpResp, err := client.UserClassificationAPI.GetUserClassification(ctx, userId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No users_classification resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing users_classification", err.Error())
			return
		}
		result := results
		_ = result
		state.ID = types.StringValue("okta_users_classification_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
