// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &submissionsAuthSettingsDefaultDataSource{}
	_ datasource.DataSourceWithConfigure = &submissionsAuthSettingsDefaultDataSource{}
)

// SubmissionsAuthSettingsDefaultDataSource defines the data source implementation.
type submissionsAuthSettingsDefaultDataSource struct {
	Config *config.Config
}

// SubmissionsAuthSettingsDefaultItemModel is one element returned by the list endpoint.
type submissionsAuthSettingsDefaultItemModel struct {
	ID       types.String `tfsdk:"id"`
	AuthType types.String `tfsdk:"auth_type"`
}

// SubmissionsAuthSettingsDefaultDataSourceModelCustomSettingsModel is the nested model for custom_settings.
type SubmissionsAuthSettingsDefaultDataSourceModelCustomSettingsModel struct {
	AppInstanceProperties []SubmissionsAuthSettingsDefaultDataSourceModelCustomSettingsModelAppInstancePropertiesModel `tfsdk:"app_instance_properties"`
}

// SubmissionsAuthSettingsDefaultDataSourceModelCustomSettingsModelAppInstancePropertiesModel is the nested model for app_instance_properties.
type SubmissionsAuthSettingsDefaultDataSourceModelCustomSettingsModelAppInstancePropertiesModel struct {
	Label types.String `tfsdk:"label"`
	Name  types.String `tfsdk:"name"`
}

// SubmissionsAuthSettingsDefaultDataSourceModelOAuth2SettingsModel is the nested model for o_auth2_settings.
type SubmissionsAuthSettingsDefaultDataSourceModelOAuth2SettingsModel struct {
	AuthorizeEndpoint types.String                                                                    `tfsdk:"authorize_endpoint"`
	ClientId          types.String                                                                    `tfsdk:"client_id"`
	ClientSecret      types.String                                                                    `tfsdk:"client_secret"`
	PublicKey         *SubmissionsAuthSettingsDefaultDataSourceModelOAuth2SettingsModelPublicKeyModel `tfsdk:"public_key"`
	Scopes            types.List                                                                      `tfsdk:"scopes"`
	TokenEndpoint     types.String                                                                    `tfsdk:"token_endpoint"`
}

// SubmissionsAuthSettingsDefaultDataSourceModelOAuth2SettingsModelPublicKeyModel is the nested model for public_key.
type SubmissionsAuthSettingsDefaultDataSourceModelOAuth2SettingsModelPublicKeyModel struct {
	E   types.String `tfsdk:"e"`
	Kid types.String `tfsdk:"kid"`
	Kty types.String `tfsdk:"kty"`
	N   types.String `tfsdk:"n"`
}

// SubmissionsAuthSettingsDefaultDataSourceModel describes the data source data model.
type submissionsAuthSettingsDefaultDataSourceModel struct {
	ID           types.String                              `tfsdk:"id"`
	SubmissionId types.String                              `tfsdk:"submission_id"`
	Items        []submissionsAuthSettingsDefaultItemModel `tfsdk:"items"`
}

func NewSubmissionsAuthSettingsDefaultDataSource() datasource.DataSource {
	return &submissionsAuthSettingsDefaultDataSource{}
}

func (d *submissionsAuthSettingsDefaultDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_submissions_auth_settings_default"
}

func (d *submissionsAuthSettingsDefaultDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *submissionsAuthSettingsDefaultDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves the authentication settings for an OIN Integration submission",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the submissions_auth_settings_default.",
				Optional:            true,
				Computed:            true,
			},
			"submission_id": schema.StringAttribute{
				MarkdownDescription: "OIN integration ID",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of submissions_auth_settings_default items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"auth_type": schema.StringAttribute{
							MarkdownDescription: "AuthType",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *submissionsAuthSettingsDefaultDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state submissionsAuthSettingsDefaultDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		submissionId := state.SubmissionId.ValueString()
		results, httpResp, err := client.YourOinIntegrationsAPI.GetSubmissionAuthSettings(ctx, submissionId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No submissions_auth_settings_default resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing submissions_auth_settings_default", err.Error())
			return
		}
		result := results
		_ = result
		state.ID = types.StringValue("okta_submissions_auth_settings_default_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
