// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"net/http"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &usersFactorsQuestionDataSource{}
	_ datasource.DataSourceWithConfigure = &usersFactorsQuestionDataSource{}
)

// UsersFactorsQuestionDataSource defines the data source implementation.
type usersFactorsQuestionDataSource struct {
	Config *config.Config
}

// UsersFactorsQuestionItemModel is one element returned by the list endpoint.
type usersFactorsQuestionItemModel struct {
	ID           types.String `tfsdk:"id"`
	Answer       types.String `tfsdk:"answer"`
	Question     types.String `tfsdk:"question"`
	QuestionText types.String `tfsdk:"question_text"`
}

// UsersFactorsQuestionDataSourceModel describes the data source data model.
type usersFactorsQuestionDataSourceModel struct {
	ID     types.String                    `tfsdk:"id"`
	UserId types.String                    `tfsdk:"user_id"`
	Items  []usersFactorsQuestionItemModel `tfsdk:"items"`
}

func NewUsersFactorsQuestionDataSource() datasource.DataSource {
	return &usersFactorsQuestionDataSource{}
}

func (d *usersFactorsQuestionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users_factors_question"
}

func (d *usersFactorsQuestionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *usersFactorsQuestionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all available security questions for the specified user",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the users_factors_question.",
				Optional:            true,
				Computed:            true,
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "ID of an existing Okta user",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of users_factors_question items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"answer": schema.StringAttribute{
							MarkdownDescription: "Answer to the question",
							Computed:            true,
						},
						"question": schema.StringAttribute{
							MarkdownDescription: "Unique key for the question",
							Computed:            true,
						},
						"question_text": schema.StringAttribute{
							MarkdownDescription: "Human-readable text that's displayed to the user",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *usersFactorsQuestionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state usersFactorsQuestionDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		userId := state.UserId.ValueString()
		results, httpResp, err := client.UserFactorAPI.ListSupportedSecurityQuestions(ctx, userId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No users_factors_question resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing users_factors_question", err.Error())
			return
		}
		state.Items = make([]usersFactorsQuestionItemModel, 0, len(results))
		for _i, result := range results {
			_ = _i
			_ = result
			item := usersFactorsQuestionItemModel{}
			item.ID = types.StringValue(fmt.Sprintf("%d", _i))
			item.Answer = types.StringValue(string(result.GetAnswer()))
			item.Question = types.StringValue(string(result.GetQuestion()))
			item.QuestionText = types.StringValue(string(result.GetQuestionText()))
			state.Items = append(state.Items, item)
		}
		sort.Slice(state.Items, func(i, j int) bool {
			return state.Items[i].ID.ValueString() < state.Items[j].ID.ValueString()
		})
		state.ID = types.StringValue("okta_users_factors_question_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
