// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"sort"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &oauth2V1ClientsRolesTargetsGroupDataSource{}
	_ datasource.DataSourceWithConfigure = &oauth2V1ClientsRolesTargetsGroupDataSource{}
)

// Oauth2V1ClientsRolesTargetsGroupDataSource defines the data source implementation.
type oauth2V1ClientsRolesTargetsGroupDataSource struct {
	Config *config.Config
}

// Oauth2V1ClientsRolesTargetsGroupItemModel is one element returned by the list endpoint.
type oauth2V1ClientsRolesTargetsGroupItemModel struct {
	ID                    types.String `tfsdk:"id"`
	Created               types.String `tfsdk:"created"`
	LastMembershipUpdated types.String `tfsdk:"last_membership_updated"`
	LastUpdated           types.String `tfsdk:"last_updated"`
	ObjectClass           types.List   `tfsdk:"object_class"`
	Type                  types.String `tfsdk:"type"`
}

// Oauth2V1ClientsRolesTargetsGroupDataSourceModel describes the data source data model.
type oauth2V1ClientsRolesTargetsGroupDataSourceModel struct {
	ID               types.String                                `tfsdk:"id"`
	ClientId         types.String                                `tfsdk:"client_id"`
	RoleAssignmentId types.String                                `tfsdk:"role_assignment_id"`
	Items            []oauth2V1ClientsRolesTargetsGroupItemModel `tfsdk:"items"`
}

func NewOauth2V1ClientsRolesTargetsGroupDataSource() datasource.DataSource {
	return &oauth2V1ClientsRolesTargetsGroupDataSource{}
}

func (d *oauth2V1ClientsRolesTargetsGroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_oauth2_v1_clients_roles_targets_group"
}

func (d *oauth2V1ClientsRolesTargetsGroupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *oauth2V1ClientsRolesTargetsGroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all group targets for a [`USER_ADMIN`](/openapi/okta-management/guides/roles/#standard-roles), `HELP_DESK_ADMIN`, or `GROUP_MEMBERSHIP_ADMIN` role assignment to a client.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the oauth2_v1_clients_roles_targets_group.",
				Optional:            true,
				Computed:            true,
			},
			"client_id": schema.StringAttribute{
				MarkdownDescription: "`client_id` of the app",
				Required:            true,
			},
			"role_assignment_id": schema.StringAttribute{
				MarkdownDescription: "The `id` of the role assignment",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of oauth2_v1_clients_roles_targets_group items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"created": schema.StringAttribute{
							MarkdownDescription: "Timestamp when the group was created",
							Computed:            true,
						},
						"last_membership_updated": schema.StringAttribute{
							MarkdownDescription: "Timestamp when the groups memberships were last updated",
							Computed:            true,
						},
						"last_updated": schema.StringAttribute{
							MarkdownDescription: "Timestamp when the group's profile was last updated",
							Computed:            true,
						},
						"object_class": schema.ListAttribute{
							MarkdownDescription: "Determines the group's `profile`",
							ElementType:         types.StringType,
							Computed:            true,
						},
						"type": schema.StringAttribute{
							MarkdownDescription: "Determines how a group's profile and memberships are managed",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *oauth2V1ClientsRolesTargetsGroupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state oauth2V1ClientsRolesTargetsGroupDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		clientId := state.ClientId.ValueString()
		roleAssignmentId := state.RoleAssignmentId.ValueString()
		results, httpResp, err := client.RoleBTargetClientAPI.ListGroupTargetRoleForClient(ctx, clientId, roleAssignmentId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No oauth2_v1_clients_roles_targets_group resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing oauth2_v1_clients_roles_targets_group", err.Error())
			return
		}
		state.Items = make([]oauth2V1ClientsRolesTargetsGroupItemModel, 0, len(results))
		for _i, result := range results {
			_ = _i
			_ = result
			item := oauth2V1ClientsRolesTargetsGroupItemModel{}
			item.ID = types.StringValue(string(result.GetId()))
			if t := result.GetCreated(); !t.IsZero() {
				item.Created = types.StringValue(t.Format(time.RFC3339))
			}
			if t := result.GetLastMembershipUpdated(); !t.IsZero() {
				item.LastMembershipUpdated = types.StringValue(t.Format(time.RFC3339))
			}
			if t := result.GetLastUpdated(); !t.IsZero() {
				item.LastUpdated = types.StringValue(t.Format(time.RFC3339))
			}
			item.Type = types.StringValue(string(result.GetType()))
			state.Items = append(state.Items, item)
		}
		sort.Slice(state.Items, func(i, j int) bool {
			return state.Items[i].ID.ValueString() < state.Items[j].ID.ValueString()
		})
		state.ID = types.StringValue("okta_oauth2_v1_clients_roles_targets_group_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
