// Code generated by tf-generator. DO NOT EDIT.
package fwprovider_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccDataSourceOktaAiAgentsCredentialsSecret_read(t *testing.T) {
	mgr := acctest.NewFixtureManager("data-sources", "okta_ai_agents_credentials_secret", t.Name())
	config := mgr.GetFixtures("datasource.tf", t)
	resourceName := "data.okta_ai_agents_credentials_secret.test"

	acctest.OktaResourceTest(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ErrorCheck:               acctest.TestAccErrorChecks(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
		},
	})
}
