// Code generated by tf-generator. DO NOT EDIT.
package fwprovider_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccDataSourceOktaAgentPoolsUpdatesSetting_read(t *testing.T) {
	mgr := acctest.NewFixtureManager("data-sources", "okta_agent_pools_updates_setting", t.Name())
	config := mgr.GetFixtures("datasource.tf", t)
	resourceName := "data.okta_agent_pools_updates_setting.test"

	acctest.OktaResourceTest(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ErrorCheck:               acctest.TestAccErrorChecks(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "agent_type"),
					resource.TestCheckResourceAttrSet(resourceName, "continue_on_error"),
					resource.TestCheckResourceAttrSet(resourceName, "latest_version"),
					resource.TestCheckResourceAttrSet(resourceName, "minimal_supported_version"),
					resource.TestCheckResourceAttrSet(resourceName, "pool_name"),
					resource.TestCheckResourceAttrSet(resourceName, "release_channel"),
				),
			},
		},
	})
}
