// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &groupDataSource{}
	_ datasource.DataSourceWithConfigure = &groupDataSource{}
)

// GroupDataSource defines the data source implementation.
type groupDataSource struct {
	Config *config.Config
}

// GroupDataSourceModel describes the data source data model.
type groupDataSourceModel struct {
	ID                    types.String `tfsdk:"id"`
	Created               types.String `tfsdk:"created"`
	LastMembershipUpdated types.String `tfsdk:"last_membership_updated"`
	LastUpdated           types.String `tfsdk:"last_updated"`
	ObjectClass           types.List   `tfsdk:"object_class"`
	Type                  types.String `tfsdk:"type"`
}

func NewGroupDataSource() datasource.DataSource {
	return &groupDataSource{}
}

func (d *groupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_group"
}

func (d *groupDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *groupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a specific group by `id` from your org",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the group.",
				Required:            true,
			},
			"created": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the group was created",
				Computed:            true,
			},
			"last_membership_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the groups memberships were last updated",
				Computed:            true,
			},
			"last_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the group's profile was last updated",
				Computed:            true,
			},
			"object_class": schema.ListAttribute{
				MarkdownDescription: "Determines the group's `profile`",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Determines how a group's profile and memberships are managed",
				Computed:            true,
			},
		},
	}
}

func (d *groupDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state groupDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	result, httpResp, err := client.GroupAPI.GetGroup(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "group with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading group", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	if t := result.GetCreated(); !t.IsZero() {
		state.Created = types.StringValue(t.Format(time.RFC3339))
	}
	if t := result.GetLastMembershipUpdated(); !t.IsZero() {
		state.LastMembershipUpdated = types.StringValue(t.Format(time.RFC3339))
	}
	if t := result.GetLastUpdated(); !t.IsZero() {
		state.LastUpdated = types.StringValue(t.Format(time.RFC3339))
	}
	state.Type = types.StringValue(string(result.GetType()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
