// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"net/http"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &devicesUserDataSource{}
	_ datasource.DataSourceWithConfigure = &devicesUserDataSource{}
)

// DevicesUserDataSource defines the data source implementation.
type devicesUserDataSource struct {
	Config *config.Config
}

// DevicesUserItemModel is one element returned by the list endpoint.
type devicesUserItemModel struct {
	ID               types.String `tfsdk:"id"`
	Created          types.String `tfsdk:"created"`
	ManagementStatus types.String `tfsdk:"management_status"`
	ScreenLockType   types.String `tfsdk:"screen_lock_type"`
}

// DevicesUserDataSourceModelUserModel is the nested model for user.
type DevicesUserDataSourceModelUserModel struct {
	Activated             types.String                                         `tfsdk:"activated"`
	Created               types.String                                         `tfsdk:"created"`
	Credentials           *DevicesUserDataSourceModelUserModelCredentialsModel `tfsdk:"credentials"`
	Id                    types.String                                         `tfsdk:"id"`
	LastLogin             types.String                                         `tfsdk:"last_login"`
	LastUpdated           types.String                                         `tfsdk:"last_updated"`
	PasswordChanged       types.String                                         `tfsdk:"password_changed"`
	Profile               *DevicesUserDataSourceModelUserModelProfileModel     `tfsdk:"profile"`
	RealmId               types.String                                         `tfsdk:"realm_id"`
	Status                types.String                                         `tfsdk:"status"`
	StatusChanged         types.String                                         `tfsdk:"status_changed"`
	TransitioningToStatus types.String                                         `tfsdk:"transitioning_to_status"`
	Type                  *DevicesUserDataSourceModelUserModelTypeModel        `tfsdk:"type"`
}

// DevicesUserDataSourceModelUserModelCredentialsModel is the nested model for credentials.
type DevicesUserDataSourceModelUserModelCredentialsModel struct {
	Password         *DevicesUserDataSourceModelUserModelCredentialsModelPasswordModel         `tfsdk:"password"`
	Provider         *DevicesUserDataSourceModelUserModelCredentialsModelProviderModel         `tfsdk:"provider"`
	RecoveryQuestion *DevicesUserDataSourceModelUserModelCredentialsModelRecoveryQuestionModel `tfsdk:"recovery_question"`
}

// DevicesUserDataSourceModelUserModelCredentialsModelPasswordModel is the nested model for password.
type DevicesUserDataSourceModelUserModelCredentialsModelPasswordModel struct {
	Hash  *DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHashModel `tfsdk:"hash"`
	Hook  *DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHookModel `tfsdk:"hook"`
	Value types.String                                                               `tfsdk:"value"`
}

// DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHashModel is the nested model for hash.
type DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHashModel struct {
	Algorithm       types.String `tfsdk:"algorithm"`
	DigestAlgorithm types.String `tfsdk:"digest_algorithm"`
	IterationCount  types.Int64  `tfsdk:"iteration_count"`
	KeySize         types.Int64  `tfsdk:"key_size"`
	Salt            types.String `tfsdk:"salt"`
	SaltOrder       types.String `tfsdk:"salt_order"`
	Value           types.String `tfsdk:"value"`
	WorkFactor      types.Int64  `tfsdk:"work_factor"`
}

// DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHookModel is the nested model for hook.
type DevicesUserDataSourceModelUserModelCredentialsModelPasswordModelHookModel struct {
	Type types.String `tfsdk:"type"`
}

// DevicesUserDataSourceModelUserModelCredentialsModelProviderModel is the nested model for provider.
type DevicesUserDataSourceModelUserModelCredentialsModelProviderModel struct {
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

// DevicesUserDataSourceModelUserModelCredentialsModelRecoveryQuestionModel is the nested model for recovery_question.
type DevicesUserDataSourceModelUserModelCredentialsModelRecoveryQuestionModel struct {
	Answer   types.String `tfsdk:"answer"`
	Question types.String `tfsdk:"question"`
}

// DevicesUserDataSourceModelUserModelProfileModel is the nested model for profile.
type DevicesUserDataSourceModelUserModelProfileModel struct {
	City              types.String `tfsdk:"city"`
	CostCenter        types.String `tfsdk:"cost_center"`
	CountryCode       types.String `tfsdk:"country_code"`
	Department        types.String `tfsdk:"department"`
	DisplayName       types.String `tfsdk:"display_name"`
	Division          types.String `tfsdk:"division"`
	Email             types.String `tfsdk:"email"`
	EmployeeNumber    types.String `tfsdk:"employee_number"`
	FirstName         types.String `tfsdk:"first_name"`
	HonorificPrefix   types.String `tfsdk:"honorific_prefix"`
	HonorificSuffix   types.String `tfsdk:"honorific_suffix"`
	LastName          types.String `tfsdk:"last_name"`
	Locale            types.String `tfsdk:"locale"`
	Login             types.String `tfsdk:"login"`
	Manager           types.String `tfsdk:"manager"`
	ManagerId         types.String `tfsdk:"manager_id"`
	MiddleName        types.String `tfsdk:"middle_name"`
	MobilePhone       types.String `tfsdk:"mobile_phone"`
	NickName          types.String `tfsdk:"nick_name"`
	Organization      types.String `tfsdk:"organization"`
	PostalAddress     types.String `tfsdk:"postal_address"`
	PreferredLanguage types.String `tfsdk:"preferred_language"`
	PrimaryPhone      types.String `tfsdk:"primary_phone"`
	ProfileUrl        types.String `tfsdk:"profile_url"`
	SecondEmail       types.String `tfsdk:"second_email"`
	State             types.String `tfsdk:"state"`
	StreetAddress     types.String `tfsdk:"street_address"`
	Timezone          types.String `tfsdk:"timezone"`
	Title             types.String `tfsdk:"title"`
	UserType          types.String `tfsdk:"user_type"`
	ZipCode           types.String `tfsdk:"zip_code"`
}

// DevicesUserDataSourceModelUserModelTypeModel is the nested model for type.
type DevicesUserDataSourceModelUserModelTypeModel struct {
	Id types.String `tfsdk:"id"`
}

// DevicesUserDataSourceModel describes the data source data model.
type devicesUserDataSourceModel struct {
	ID       types.String           `tfsdk:"id"`
	DeviceId types.String           `tfsdk:"device_id"`
	Items    []devicesUserItemModel `tfsdk:"items"`
}

func NewDevicesUserDataSource() datasource.DataSource {
	return &devicesUserDataSource{}
}

func (d *devicesUserDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_devices_user"
}

func (d *devicesUserDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *devicesUserDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all Users for a device by `deviceId`",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the devices_user.",
				Optional:            true,
				Computed:            true,
			},
			"device_id": schema.StringAttribute{
				MarkdownDescription: "`id` of the device",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of devices_user items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"created": schema.StringAttribute{
							MarkdownDescription: "Timestamp when device was created",
							Computed:            true,
						},
						"management_status": schema.StringAttribute{
							MarkdownDescription: "The management status of the device",
							Computed:            true,
						},
						"screen_lock_type": schema.StringAttribute{
							MarkdownDescription: "Screen lock type of the device",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *devicesUserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state devicesUserDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		deviceId := state.DeviceId.ValueString()
		results, httpResp, err := client.DeviceAPI.ListDeviceUsers(ctx, deviceId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No devices_user resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing devices_user", err.Error())
			return
		}
		state.Items = make([]devicesUserItemModel, 0, len(results))
		for _i, result := range results {
			_ = _i
			_ = result
			item := devicesUserItemModel{}
			item.ID = types.StringValue(fmt.Sprintf("%d", _i))
			item.Created = types.StringValue(string(result.GetCreated()))
			item.ManagementStatus = types.StringValue(string(result.GetManagementStatus()))
			item.ScreenLockType = types.StringValue(string(result.GetScreenLockType()))
			state.Items = append(state.Items, item)
		}
		sort.Slice(state.Items, func(i, j int) bool {
			return state.Items[i].ID.ValueString() < state.Items[j].ID.ValueString()
		})
		state.ID = types.StringValue("okta_devices_user_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
