// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &usersFactorsTransactionSuccessDataSource{}
	_ datasource.DataSourceWithConfigure = &usersFactorsTransactionSuccessDataSource{}
)

// UsersFactorsTransactionSuccessDataSource defines the data source implementation.
type usersFactorsTransactionSuccessDataSource struct {
	Config *config.Config
}

// UsersFactorsTransactionSuccessDataSourceModel describes the data source data model.
type usersFactorsTransactionSuccessDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	UserId       types.String `tfsdk:"user_id"`
	FactorId     types.String `tfsdk:"factor_id"`
	FactorResult types.String `tfsdk:"factor_result"`
}

func NewUsersFactorsTransactionSuccessDataSource() datasource.DataSource {
	return &usersFactorsTransactionSuccessDataSource{}
}

func (d *usersFactorsTransactionSuccessDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users_factors_transaction_success"
}

func (d *usersFactorsTransactionSuccessDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *usersFactorsTransactionSuccessDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves the status of a `push` factor verification transaction   > **Note:**  > The response body for a number matching push challenge to an Okta Verify `push` factor enrollment is different from the response body of a standard push challenge.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the users_factors_transaction_success.",
				Required:            true,
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "ID of an existing Okta user",
				Required:            true,
			},
			"factor_id": schema.StringAttribute{
				MarkdownDescription: "ID of an existing user factor",
				Required:            true,
			},
			"factor_result": schema.StringAttribute{
				MarkdownDescription: "Result of the verification transaction",
				Computed:            true,
			},
		},
	}
}

func (d *usersFactorsTransactionSuccessDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state usersFactorsTransactionSuccessDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	userId := state.UserId.ValueString()
	factorId := state.FactorId.ValueString()
	result, httpResp, err := client.UserFactorAPI.GetFactorTransactionStatus(ctx, userId, factorId, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "users_factors_transaction_success with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading users_factors_transaction_success", err.Error())
		return
	}
	if variantObj, ok := result.GetActualInstance().(*okta.UserFactorPushTransactionSuccess); ok {
		state.ID = state.ID
		state.FactorResult = types.StringValue(string(variantObj.GetFactorResult()))

	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
