// Code generated by tf-generator. DO NOT EDIT.
package fwprovider_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccDataSourceOktaAppsUser_read(t *testing.T) {
	mgr := acctest.NewFixtureManager("data-sources", "okta_apps_user", t.Name())
	config := mgr.GetFixtures("datasource.tf", t)
	resourceName := "data.okta_apps_user.test"

	acctest.OktaResourceTest(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ErrorCheck:               acctest.TestAccErrorChecks(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "created"),
					resource.TestCheckResourceAttrSet(resourceName, "external_id"),
					resource.TestCheckResourceAttrSet(resourceName, "last_sync"),
					resource.TestCheckResourceAttrSet(resourceName, "last_updated"),
					resource.TestCheckResourceAttrSet(resourceName, "password_changed"),
					resource.TestCheckResourceAttrSet(resourceName, "profile"),
					resource.TestCheckResourceAttrSet(resourceName, "scope"),
					resource.TestCheckResourceAttrSet(resourceName, "status"),
					resource.TestCheckResourceAttrSet(resourceName, "status_changed"),
					resource.TestCheckResourceAttrSet(resourceName, "sync_state"),
				),
			},
		},
	})
}
