// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"sort"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &usersEnrollmentDataSource{}
	_ datasource.DataSourceWithConfigure = &usersEnrollmentDataSource{}
)

// UsersEnrollmentDataSource defines the data source implementation.
type usersEnrollmentDataSource struct {
	Config *config.Config
}

// UsersEnrollmentItemModel is one element returned by the list endpoint.
type usersEnrollmentItemModel struct {
	ID          types.String `tfsdk:"id"`
	Created     types.String `tfsdk:"created"`
	FactorType  types.String `tfsdk:"factor_type"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Profile     types.Map    `tfsdk:"profile"`
	Provider    types.String `tfsdk:"provider"`
	Status      types.String `tfsdk:"status"`
	VendorName  types.String `tfsdk:"vendor_name"`
}

// UsersEnrollmentDataSourceModel describes the data source data model.
type usersEnrollmentDataSourceModel struct {
	ID     types.String               `tfsdk:"id"`
	UserId types.String               `tfsdk:"user_id"`
	Items  []usersEnrollmentItemModel `tfsdk:"items"`
}

func NewUsersEnrollmentDataSource() datasource.DataSource {
	return &usersEnrollmentDataSource{}
}

func (d *usersEnrollmentDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users_enrollment"
}

func (d *usersEnrollmentDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *usersEnrollmentDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all WebAuthn preregistration factors for the specified user",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the users_enrollment.",
				Optional:            true,
				Computed:            true,
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "ID of an existing Okta user",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of users_enrollment items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"created": schema.StringAttribute{
							MarkdownDescription: "Timestamp indicating when the factor was enrolled",
							Computed:            true,
						},
						"factor_type": schema.StringAttribute{
							MarkdownDescription: "Type of factor",
							Computed:            true,
						},
						"last_updated": schema.StringAttribute{
							MarkdownDescription: "Timestamp indicating when the factor was last updated",
							Computed:            true,
						},
						"profile": schema.MapAttribute{
							MarkdownDescription: "Specific attributes related to the factor",
							ElementType:         types.StringType,
							Computed:            true,
						},
						"provider": schema.StringAttribute{
							MarkdownDescription: "Provider",
							Computed:            true,
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "Status of the factor",
							Computed:            true,
						},
						"vendor_name": schema.StringAttribute{
							MarkdownDescription: "Name of the factor vendor.",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *usersEnrollmentDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state usersEnrollmentDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	{
		userId := state.UserId.ValueString()
		results, httpResp, err := client.WebAuthnPreregistrationAPI.ListWebAuthnPreregistrationFactors(ctx, userId).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No users_enrollment resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing users_enrollment", err.Error())
			return
		}
		state.Items = make([]usersEnrollmentItemModel, 0, len(results))
		for _i, result := range results {
			_ = _i
			_ = result
			item := usersEnrollmentItemModel{}
			item.ID = types.StringValue(string(result.GetId()))
			if t := result.GetCreated(); !t.IsZero() {
				item.Created = types.StringValue(t.Format(time.RFC3339))
			}
			item.FactorType = types.StringValue(string(result.GetFactorType()))
			if t := result.GetLastUpdated(); !t.IsZero() {
				item.LastUpdated = types.StringValue(t.Format(time.RFC3339))
			}
			item.Provider = types.StringValue(string(result.GetProvider()))
			item.Status = types.StringValue(string(result.GetStatus()))
			item.VendorName = types.StringValue(string(result.GetVendorName()))
			state.Items = append(state.Items, item)
		}
		sort.Slice(state.Items, func(i, j int) bool {
			return state.Items[i].ID.ValueString() < state.Items[j].ID.ValueString()
		})
		state.ID = types.StringValue("okta_users_enrollment_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
