// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &authorizationServersResourceservercredentialsKeyDataSource{}
	_ datasource.DataSourceWithConfigure = &authorizationServersResourceservercredentialsKeyDataSource{}
)

// AuthorizationServersResourceservercredentialsKeyDataSource defines the data source implementation.
type authorizationServersResourceservercredentialsKeyDataSource struct {
	Config *config.Config
}

// AuthorizationServersResourceservercredentialsKeyDataSourceModel describes the data source data model.
type authorizationServersResourceservercredentialsKeyDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	AuthServerId types.String `tfsdk:"auth_server_id"`
	Created      types.String `tfsdk:"created"`
	E            types.String `tfsdk:"e"`
	Kid          types.String `tfsdk:"kid"`
	Kty          types.String `tfsdk:"kty"`
	LastUpdated  types.String `tfsdk:"last_updated"`
	N            types.String `tfsdk:"n"`
	Status       types.String `tfsdk:"status"`
	Use          types.String `tfsdk:"use"`
}

func NewAuthorizationServersResourceservercredentialsKeyDataSource() datasource.DataSource {
	return &authorizationServersResourceservercredentialsKeyDataSource{}
}

func (d *authorizationServersResourceservercredentialsKeyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_authorization_servers_resourceservercredentials_key"
}

func (d *authorizationServersResourceservercredentialsKeyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *authorizationServersResourceservercredentialsKeyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a custom authorization server public JSON web key by key `id`",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the authorization_servers_resourceservercredentials_key.",
				Required:            true,
			},
			"auth_server_id": schema.StringAttribute{
				MarkdownDescription: "`id` of the Authorization Server",
				Required:            true,
			},
			"created": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the JSON Web Key was created",
				Computed:            true,
			},
			"e": schema.StringAttribute{
				MarkdownDescription: "RSA key value (exponent) for key binding",
				Computed:            true,
			},
			"kid": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the JSON Web Key in the Custom Authorization Server's Public JWKS",
				Computed:            true,
			},
			"kty": schema.StringAttribute{
				MarkdownDescription: "Cryptographic algorithm family for the certificate's key pair",
				Computed:            true,
			},
			"last_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp when the JSON Web Key was updated",
				Computed:            true,
			},
			"n": schema.StringAttribute{
				MarkdownDescription: "RSA key value (modulus) for key binding",
				Computed:            true,
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "The status of the encryption key.",
				Computed:            true,
			},
			"use": schema.StringAttribute{
				MarkdownDescription: "Acceptable use of the JSON Web Key",
				Computed:            true,
			},
		},
	}
}

func (d *authorizationServersResourceservercredentialsKeyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state authorizationServersResourceservercredentialsKeyDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	authServerId := state.AuthServerId.ValueString()
	result, httpResp, err := client.OAuth2ResourceServerCredentialsKeysAPI.GetOAuth2ResourceServerJsonWebKey(ctx, authServerId, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "authorization_servers_resourceservercredentials_key with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading authorization_servers_resourceservercredentials_key", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	state.Created = types.StringValue(string(result.GetCreated()))
	state.E = types.StringValue(string(result.GetE()))
	state.Kid = types.StringValue(string(result.GetKid()))
	state.Kty = types.StringValue(string(result.GetKty()))
	state.LastUpdated = types.StringValue(string(result.GetLastUpdated()))
	state.N = types.StringValue(string(result.GetN()))
	state.Status = types.StringValue(string(result.GetStatus()))
	state.Use = types.StringValue(string(result.GetUse()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
