// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &domainDataSource{}
	_ datasource.DataSourceWithConfigure = &domainDataSource{}
)

// DomainDataSource defines the data source implementation.
type domainDataSource struct {
	Config *config.Config
}

// DomainDataSourceModel describes the data source data model.
type domainDataSourceModel struct {
	ID                    types.String                                 `tfsdk:"id"`
	BrandId               types.String                                 `tfsdk:"brand_id"`
	CertificateSourceType types.String                                 `tfsdk:"certificate_source_type"`
	DnsRecords            []DomainDataSourceModelDnsRecordsModel       `tfsdk:"dns_records"`
	Domain                types.String                                 `tfsdk:"domain"`
	PublicCertificate     *DomainDataSourceModelPublicCertificateModel `tfsdk:"public_certificate"`
	ValidationStatus      types.String                                 `tfsdk:"validation_status"`
}

// DomainDataSourceModelDnsRecordsModel is the nested model for dns_records.
type DomainDataSourceModelDnsRecordsModel struct {
	Expiration types.String `tfsdk:"expiration"`
	Fqdn       types.String `tfsdk:"fqdn"`
	RecordType types.String `tfsdk:"record_type"`
	Values     types.List   `tfsdk:"values"`
}

// DomainDataSourceModelPublicCertificateModel is the nested model for public_certificate.
type DomainDataSourceModelPublicCertificateModel struct {
	Expiration  types.String `tfsdk:"expiration"`
	Fingerprint types.String `tfsdk:"fingerprint"`
	Subject     types.String `tfsdk:"subject"`
}

func NewDomainDataSource() datasource.DataSource {
	return &domainDataSource{}
}

func (d *domainDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_domain"
}

func (d *domainDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *domainDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a custom domain by `domainId`",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the domain.",
				Required:            true,
			},
			"brand_id": schema.StringAttribute{
				MarkdownDescription: "The ID number of the brand",
				Computed:            true,
			},
			"certificate_source_type": schema.StringAttribute{
				MarkdownDescription: "Certificate source type that indicates whether the certificate is provided by the user or Okta.",
				Computed:            true,
			},
			"domain": schema.StringAttribute{
				MarkdownDescription: "Custom domain name",
				Computed:            true,
			},
			"validation_status": schema.StringAttribute{
				MarkdownDescription: "Status of the domain",
				Computed:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"dns_records": schema.ListNestedBlock{
				Description: "DnsRecords",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"expiration": schema.StringAttribute{
							Description: "DNS TXT record expiration",
							Computed:    true,
						},
						"fqdn": schema.StringAttribute{
							Description: "DNS record name",
							Computed:    true,
						},
						"record_type": schema.StringAttribute{
							Description: "RecordType",
							Computed:    true,
						},
						"values": schema.ListAttribute{
							Description: "DNS record value",
							ElementType: types.StringType,
							Computed:    true,
						},
					},
				},
			},
			"public_certificate": schema.SingleNestedBlock{
				Description: "Certificate metadata for the domain",
				Attributes: map[string]schema.Attribute{
					"expiration": schema.StringAttribute{
						Description: "Certificate expiration",
						Computed:    true,
					},
					"fingerprint": schema.StringAttribute{
						Description: "Certificate fingerprint",
						Computed:    true,
					},
					"subject": schema.StringAttribute{
						Description: "Certificate subject",
						Computed:    true,
					},
				},
			},
		},
	}
}

func (d *domainDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state domainDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	result, httpResp, err := client.CustomDomainAPI.GetCustomDomain(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "domain with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading domain", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	state.BrandId = types.StringValue(string(result.GetBrandId()))
	state.CertificateSourceType = types.StringValue(string(result.GetCertificateSourceType()))
	state.Domain = types.StringValue(string(result.GetDomain()))
	state.ValidationStatus = types.StringValue(string(result.GetValidationStatus()))
	if apiList := result.GetDnsRecords(); len(apiList) > 0 {
		dnsRecordsList0 := make([]DomainDataSourceModelDnsRecordsModel, 0, len(apiList))
		for _, apiItem := range apiList {
			dnsRecordsItem0 := &DomainDataSourceModelDnsRecordsModel{}
			dnsRecordsItem0.Expiration = types.StringValue(string(apiItem.GetExpiration()))
			dnsRecordsItem0.Fqdn = types.StringValue(string(apiItem.GetFqdn()))
			dnsRecordsItem0.RecordType = types.StringValue(string(apiItem.GetRecordType()))
			dnsRecordsList0 = append(dnsRecordsList0, *dnsRecordsItem0)
		}
		state.DnsRecords = dnsRecordsList0
	}
	if publicCertificateRaw0, ok := result.GetPublicCertificateOk(); ok {
		var publicCertificateModel0 *DomainDataSourceModelPublicCertificateModel
		if state.PublicCertificate == nil {
			publicCertificateModel0 = &DomainDataSourceModelPublicCertificateModel{}
		} else {
			publicCertificateModel0 = state.PublicCertificate
		}
		publicCertificateModel0.Expiration = types.StringValue(string(publicCertificateRaw0.GetExpiration()))
		publicCertificateModel0.Fingerprint = types.StringValue(string(publicCertificateRaw0.GetFingerprint()))
		publicCertificateModel0.Subject = types.StringValue(string(publicCertificateRaw0.GetSubject()))
		state.PublicCertificate = publicCertificateModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
