// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &mappingDataSource{}
	_ datasource.DataSourceWithConfigure = &mappingDataSource{}
)

// MappingDataSource defines the data source implementation.
type mappingDataSource struct {
	Config *config.Config
}

// MappingDataSourceModel describes the data source data model.
type mappingDataSourceModel struct {
	ID         types.String                           `tfsdk:"id"`
	Properties *MappingDataSourceModelPropertiesModel `tfsdk:"properties"`
	Source     *MappingDataSourceModelSourceModel     `tfsdk:"source"`
	Target     *MappingDataSourceModelTargetModel     `tfsdk:"target"`
}

// MappingDataSourceModelPropertiesModel is the nested model for properties.
type MappingDataSourceModelPropertiesModel struct {
	Expression types.String `tfsdk:"expression"`
	PushStatus types.String `tfsdk:"push_status"`
}

// MappingDataSourceModelSourceModel is the nested model for source.
type MappingDataSourceModelSourceModel struct {
	Id   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

// MappingDataSourceModelTargetModel is the nested model for target.
type MappingDataSourceModelTargetModel struct {
	Id   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

func NewMappingDataSource() datasource.DataSource {
	return &mappingDataSource{}
}

func (d *mappingDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mapping"
}

func (d *mappingDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *mappingDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a single profile mapping referenced by its ID",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the mapping.",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"properties": schema.SingleNestedBlock{
				Description: "A target property, in string form, that maps to a valid [JSON Schema Draft](https://tools.",
				Attributes: map[string]schema.Attribute{
					"expression": schema.StringAttribute{
						Description: "Combination or single source properties that are mapped to the target property.",
						Computed:    true,
					},
					"push_status": schema.StringAttribute{
						Description: "Indicates whether to update target properties for user create and update or just for user create.",
						Computed:    true,
					},
				},
			},
			"source": schema.SingleNestedBlock{
				Description: "The parameter is the source of a profile mapping and is a valid [JSON Schema Draft 4](https://datatracker.",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Description: "Unique identifier for the application instance or userType",
						Computed:    true,
					},
					"name": schema.StringAttribute{
						Description: "Variable name of the application instance or name of the referenced UserType",
						Computed:    true,
					},
					"type": schema.StringAttribute{
						Description: "Type of user referenced in the mapping",
						Computed:    true,
					},
				},
			},
			"target": schema.SingleNestedBlock{
				Description: "The parameter is the target of a profile mapping and is a valid [JSON Schema Draft 4](https://datatracker.",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Description: "Unique identifier for the application instance or UserType",
						Computed:    true,
					},
					"name": schema.StringAttribute{
						Description: "Variable name of the application instance or name of the referenced userType",
						Computed:    true,
					},
					"type": schema.StringAttribute{
						Description: "Type of user referenced in the mapping",
						Computed:    true,
					},
				},
			},
		},
	}
}

func (d *mappingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state mappingDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	result, httpResp, err := client.ProfileMappingAPI.GetProfileMapping(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "mapping with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading mapping", err.Error())
		return
	}
	state.ID = types.StringValue(string(result.GetId()))
	if propertiesRaw0, ok := result.GetPropertiesOk(); ok {
		var propertiesModel0 *MappingDataSourceModelPropertiesModel
		if state.Properties == nil {
			propertiesModel0 = &MappingDataSourceModelPropertiesModel{}
		} else {
			propertiesModel0 = state.Properties
		}
		propertiesModel0.Expression = types.StringValue(string(propertiesRaw0.GetExpression()))
		propertiesModel0.PushStatus = types.StringValue(string(propertiesRaw0.GetPushStatus()))
		state.Properties = propertiesModel0
	}
	if sourceRaw0, ok := result.GetSourceOk(); ok {
		var sourceModel0 *MappingDataSourceModelSourceModel
		if state.Source == nil {
			sourceModel0 = &MappingDataSourceModelSourceModel{}
		} else {
			sourceModel0 = state.Source
		}
		sourceModel0.Id = types.StringValue(string(sourceRaw0.GetId()))
		sourceModel0.Name = types.StringValue(string(sourceRaw0.GetName()))
		sourceModel0.Type = types.StringValue(string(sourceRaw0.GetType()))
		state.Source = sourceModel0
	}
	if targetRaw0, ok := result.GetTargetOk(); ok {
		var targetModel0 *MappingDataSourceModelTargetModel
		if state.Target == nil {
			targetModel0 = &MappingDataSourceModelTargetModel{}
		} else {
			targetModel0 = state.Target
		}
		targetModel0.Id = types.StringValue(string(targetRaw0.GetId()))
		targetModel0.Name = types.StringValue(string(targetRaw0.GetName()))
		targetModel0.Type = types.StringValue(string(targetRaw0.GetType()))
		state.Target = targetModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
