// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &usersLinkedObjectDataSource{}
	_ datasource.DataSourceWithConfigure = &usersLinkedObjectDataSource{}
)

// UsersLinkedObjectDataSource defines the data source implementation.
type usersLinkedObjectDataSource struct {
	Config *config.Config
}

// UsersLinkedObjectDataSourceModel describes the data source data model.
type usersLinkedObjectDataSourceModel struct {
	ID            types.String `tfsdk:"id"`
	UserIdOrLogin types.String `tfsdk:"user_id_or_login"`
}

func NewUsersLinkedObjectDataSource() datasource.DataSource {
	return &usersLinkedObjectDataSource{}
}

func (d *usersLinkedObjectDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users_linked_object"
}

func (d *usersLinkedObjectDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *usersLinkedObjectDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists either the `self` link for the primary user or all associated users in the relationship specified by `relationshipName`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the users_linked_object.",
				Required:            true,
			},
			"user_id_or_login": schema.StringAttribute{
				MarkdownDescription: "If for the `self` link, this is the ID of the user for whom you want to get the primary user ID",
				Required:            true,
			},
		},
	}
}

func (d *usersLinkedObjectDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state usersLinkedObjectDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClient()
	id := state.ID.ValueString()
	userIdOrLogin := state.UserIdOrLogin.ValueString()
	result, httpResp, err := client.UserLinkedObjectAPI.ListLinkedObjectsForUser(ctx, userIdOrLogin, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.Diagnostics.AddError("Not Found", "users_linked_object with the given ID was not found.")
			return
		}
		resp.Diagnostics.AddError("Error reading users_linked_object", err.Error())
		return
	}
	state.ID = state.ID
	_ = result // IDExpr may not reference result; prevent "declared and not used"

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
