// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"strings"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &iamResourceSetsResourceResource{}
	_ resource.ResourceWithConfigure   = &iamResourceSetsResourceResource{}
	_ resource.ResourceWithImportState = &iamResourceSetsResourceResource{}
)

// IamResourceSetsResourceResource defines the resource implementation.
type iamResourceSetsResourceResource struct {
	Config *config.Config
}

// IamResourceSetsResourceModel describes the resource data model.
type iamResourceSetsResourceModel struct {
	ID                   types.String                                 `tfsdk:"id"`
	ResourceSetIdOrLabel types.String                                 `tfsdk:"resource_set_id_or_label"`
	Conditions           *IamResourceSetsResourceModelConditionsModel `tfsdk:"conditions"`
	Created              types.String                                 `tfsdk:"created"`
	LastUpdated          types.String                                 `tfsdk:"last_updated"`
	Orn                  types.String                                 `tfsdk:"orn"`
	ResourceOrnOrUrl     types.String                                 `tfsdk:"resource_orn_or_url"`
}

// IamResourceSetsResourceModelConditionsModel is the nested model for conditions.
type IamResourceSetsResourceModelConditionsModel struct {
	Exclude *IamResourceSetsResourceModelConditionsModelExcludeModel `tfsdk:"exclude"`
}

// IamResourceSetsResourceModelConditionsModelExcludeModel is the nested model for exclude.
type IamResourceSetsResourceModelConditionsModelExcludeModel struct {
	OktaORN types.List `tfsdk:"okta_orn"`
}

func NewIamResourceSetsResourceResource() resource.Resource {
	return &iamResourceSetsResourceResource{}
}

func (r *iamResourceSetsResourceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_resource_sets_resource"
}

func (r *iamResourceSetsResourceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *iamResourceSetsResourceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Resource Set Resources API provides operations to manage resources within a resource set.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"resource_set_id_or_label": schema.StringAttribute{
				Description: "`id` or `label` of the resource set",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the resource set resource object was created",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when this object was last updated",
				Computed:    true,
			},
			"orn": schema.StringAttribute{
				Description: "The Okta Resource Name (ORN) of the resource",
				Optional:    true,
			},
			"resource_orn_or_url": schema.StringAttribute{
				Description: "Resource in ORN or REST API URL format",
				Required:    true,
				Sensitive:   true,
			},
		},
		Blocks: map[string]schema.Block{
			"conditions": schema.SingleNestedBlock{
				Description: "Conditions for further restricting a resource.",
				Blocks: map[string]schema.Block{
					"exclude": schema.SingleNestedBlock{
						Description: "Specific resources to exclude",
						Attributes: map[string]schema.Attribute{
							"okta_orn": schema.ListAttribute{
								Description: "List of specific resources to exclude in ORN format",
								ElementType: types.StringType,
								Optional:    true,
							},
						},
					},
				},
			},
		},
	}
}
func (r *iamResourceSetsResourceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: {resource_set_id_or_label}/{id}
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Import ID must be in the format: {resource_set_id_or_label}/{id}",
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("resource_set_id_or_label"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("id"), parts[1])...)
}

func (r *iamResourceSetsResourceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state iamResourceSetsResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	resourceSetIdOrLabel := state.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.RoleCResourceSetResourceAPI.GetResourceSetResource(ctx, resourceSetIdOrLabel, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading iam_resource_sets_resource", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetOrn(); v != "" {
		state.Orn = types.StringValue(string(v))
	} else {
		state.Orn = types.StringNull()
	}
	if conditionsRaw0, ok := result.GetConditionsOk(); ok {
		var conditionsModel0 *IamResourceSetsResourceModelConditionsModel
		if state.Conditions == nil {
			conditionsModel0 = &IamResourceSetsResourceModelConditionsModel{}
		} else {
			conditionsModel0 = state.Conditions
		}
		if excludeRaw1, ok := conditionsRaw0.GetExcludeOk(); ok {
			var excludeModel1 *IamResourceSetsResourceModelConditionsModelExcludeModel
			if conditionsModel0.Exclude == nil {
				excludeModel1 = &IamResourceSetsResourceModelConditionsModelExcludeModel{}
			} else {
				excludeModel1 = conditionsModel0.Exclude
			}
			{
				listVal, listDiags := types.ListValueFrom(ctx, types.StringType, excludeRaw1.GetOktaORN())
				resp.Diagnostics.Append(listDiags...)
				excludeModel1.OktaORN = listVal
			}
			conditionsModel0.Exclude = excludeModel1
		}
		state.Conditions = conditionsModel0
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *iamResourceSetsResourceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan iamResourceSetsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resourceSetIdOrLabel := plan.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.RoleCResourceSetResourceAPI.AddResourceSetResource(ctx, resourceSetIdOrLabel)
	body := okta.NewResourceSetResourcePostRequestWithDefaults()
	if plan.Conditions != nil {
		nestedConditions := okta.NewResourceConditionsWithDefaults()
		body.SetConditions(*nestedConditions)
	}
	body.SetResourceOrnOrUrl(plan.ResourceOrnOrUrl.ValueString())
	createReq = createReq.Instance(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating iam_resource_sets_resource", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetOrn(); v != "" {
		plan.Orn = types.StringValue(string(v))
	} else {
		plan.Orn = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *iamResourceSetsResourceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan iamResourceSetsResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state iamResourceSetsResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	resourceSetIdOrLabel := state.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.RoleCResourceSetResourceAPI.ReplaceResourceSetResource(ctx, resourceSetIdOrLabel, id)
	updateBody := okta.NewResourceSetResourcePutRequestWithDefaults()
	if plan.Conditions != nil {
		nestedConditions := okta.NewResourceConditionsWithDefaults()
		updateBody.SetConditions(*nestedConditions)
	}
	updateReq = updateReq.ResourceSetResourcePutRequest(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating iam_resource_sets_resource", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetOrn(); v != "" {
		state.Orn = types.StringValue(string(v))
	} else {
		state.Orn = types.StringNull()
	}
	state.ResourceOrnOrUrl = plan.ResourceOrnOrUrl

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *iamResourceSetsResourceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state iamResourceSetsResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	resourceSetIdOrLabel := state.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.RoleCResourceSetResourceAPI.DeleteResourceSetResource(ctx, resourceSetIdOrLabel, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting iam_resource_sets_resource", err.Error())
		return
	}
}
