// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccOktaApplicationSaml_basic(t *testing.T) {
	resourceName := "okta_application_saml.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		CheckDestroy:             testAccCheckOktaApplicationSamlDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccOktaApplicationSamlConfig_basic(),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckOktaApplicationSamlExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccOktaApplicationSamlConfig_basic() string {
	return `
resource "okta_application_saml" "test" {
	// TODO: Add required attributes
}
`
}

func testAccCheckOktaApplicationSamlExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		// TODO: Implement API call to verify resource exists
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, _, err := client.ApplicationAPI.GetApplication(context.Background(), rs.Primary.ID).Execute()
		// if err != nil {
		//     return fmt.Errorf("error getting application_saml: %v", err)
		// }

		return nil
	}
}

func testAccCheckOktaApplicationSamlDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "okta_application_saml" {
			continue
		}

		// TODO: Implement API call to verify resource is destroyed
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, httpResp, err := client.ApplicationAPI.GetApplication(context.Background(), rs.Primary.ID).Execute()
		// if err == nil {
		//     return fmt.Errorf("application_saml still exists: %s", rs.Primary.ID)
		// }
		// if httpResp != nil && httpResp.StatusCode != 404 {
		//     return fmt.Errorf("error checking application_saml destruction: %v", err)
		// }
	}
	return nil
}

// Ensure context is used
var _ = context.Background
