// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &trustedOriginResource{}
	_ resource.ResourceWithConfigure   = &trustedOriginResource{}
	_ resource.ResourceWithImportState = &trustedOriginResource{}
)

// TrustedOriginResource defines the resource implementation.
type trustedOriginResource struct {
	Config *config.Config
}

// TrustedOriginModel describes the resource data model.
type trustedOriginModel struct {
	ID            types.String                    `tfsdk:"id"`
	Created       types.String                    `tfsdk:"created"`
	CreatedBy     types.String                    `tfsdk:"created_by"`
	LastUpdated   types.String                    `tfsdk:"last_updated"`
	LastUpdatedBy types.String                    `tfsdk:"last_updated_by"`
	Name          types.String                    `tfsdk:"name"`
	Origin        types.String                    `tfsdk:"origin"`
	Scopes        []TrustedOriginModelScopesModel `tfsdk:"scopes"`
	Status        types.String                    `tfsdk:"status"`
}

// TrustedOriginModelScopesModel is the nested model for scopes.
type TrustedOriginModelScopesModel struct {
	AllowedOktaApps types.List   `tfsdk:"allowed_okta_apps"`
	Type            types.String `tfsdk:"type"`
}

func NewTrustedOriginResource() resource.Resource {
	return &trustedOriginResource{}
}

func (r *trustedOriginResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_trusted_origin"
}

func (r *trustedOriginResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *trustedOriginResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Trusted Origins API provides operations to manage Trusted Origins and sources.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the trusted origin was created",
				Computed:    true,
			},
			"created_by": schema.StringAttribute{
				Description: "The ID of the user who created the trusted origin",
				Optional:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the trusted origin was last updated",
				Computed:    true,
			},
			"last_updated_by": schema.StringAttribute{
				Description: "The ID of the user who last updated the trusted origin",
				Optional:    true,
			},
			"name": schema.StringAttribute{
				Description: "Unique name for the trusted origin",
				Optional:    true,
			},
			"origin": schema.StringAttribute{
				Description: "Unique origin URL for the trusted origin.",
				Optional:    true,
			},
			"status": schema.StringAttribute{
				Description: "Status",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"scopes": schema.ListNestedBlock{
				Description: "Array of scope types that this trusted origin is used for",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"allowed_okta_apps": schema.ListAttribute{
							Description: "The allowed Okta apps for the trusted origin scope",
							ElementType: types.StringType,
							Optional:    true,
						},
						"type": schema.StringAttribute{
							Description: "The scope type.",
							Optional:    true,
						},
					},
				},
			},
		},
	}
}
func (r *trustedOriginResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *trustedOriginResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state trustedOriginModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.TrustedOriginAPI.GetTrustedOrigin(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading trusted_origin", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetCreatedBy(); v != "" {
		state.CreatedBy = types.StringValue(string(v))
	} else {
		state.CreatedBy = types.StringNull()
	}
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetLastUpdatedBy(); v != "" {
		state.LastUpdatedBy = types.StringValue(string(v))
	} else {
		state.LastUpdatedBy = types.StringNull()
	}
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	if v := result.GetOrigin(); v != "" {
		state.Origin = types.StringValue(string(v))
	} else {
		state.Origin = types.StringNull()
	}
	if v := result.GetStatus(); v != "" {
		state.Status = types.StringValue(string(v))
	} else {
		state.Status = types.StringNull()
	}
	if apiList := result.GetScopes(); len(apiList) > 0 {
		scopesList0 := make([]TrustedOriginModelScopesModel, 0, len(apiList))
		for _, apiItem := range apiList {
			scopesItem0 := &TrustedOriginModelScopesModel{}
			if v := apiItem.GetType(); v != "" {
				scopesItem0.Type = types.StringValue(string(v))
			} else {
				scopesItem0.Type = types.StringNull()
			}
			scopesList0 = append(scopesList0, *scopesItem0)
		}
		state.Scopes = scopesList0
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *trustedOriginResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan trustedOriginModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.TrustedOriginAPI.CreateTrustedOrigin(ctx)
	body := okta.NewTrustedOriginWriteWithDefaults()
	body.SetName(plan.Name.ValueString())
	body.SetOrigin(plan.Origin.ValueString())
	if len(plan.Scopes) > 0 {
		var scopesSlice []okta.TrustedOriginScope
		for _, item := range plan.Scopes {
			nestedItem := okta.NewTrustedOriginScopeWithDefaults()
			if !item.AllowedOktaApps.IsNull() && !item.AllowedOktaApps.IsUnknown() {
				var allowedOktaAppsItemSlice []string
				for _, elem := range item.AllowedOktaApps.Elements() {
					if sv, ok := elem.(types.String); ok {
						allowedOktaAppsItemSlice = append(allowedOktaAppsItemSlice, sv.ValueString())
					}
				}
				nestedItem.SetAllowedOktaApps(allowedOktaAppsItemSlice)
			}
			if !item.Type.IsNull() && !item.Type.IsUnknown() {
				nestedItem.SetType(item.Type.ValueString())
			}
			scopesSlice = append(scopesSlice, *nestedItem)
		}
		body.SetScopes(scopesSlice)
	}
	createReq = createReq.TrustedOrigin(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating trusted_origin", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetCreatedBy(); v != "" {
		plan.CreatedBy = types.StringValue(string(v))
	} else {
		plan.CreatedBy = types.StringNull()
	}
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetLastUpdatedBy(); v != "" {
		plan.LastUpdatedBy = types.StringValue(string(v))
	} else {
		plan.LastUpdatedBy = types.StringNull()
	}
	if v := result.GetName(); v != "" {
		plan.Name = types.StringValue(string(v))
	} else {
		plan.Name = types.StringNull()
	}
	if v := result.GetOrigin(); v != "" {
		plan.Origin = types.StringValue(string(v))
	} else {
		plan.Origin = types.StringNull()
	}
	if v := result.GetStatus(); v != "" {
		plan.Status = types.StringValue(string(v))
	} else {
		plan.Status = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trustedOriginResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan trustedOriginModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state trustedOriginModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.TrustedOriginAPI.ReplaceTrustedOrigin(ctx, id)
	updateBody := okta.NewTrustedOriginWithDefaults()
	updateBody.SetCreatedBy(plan.CreatedBy.ValueString())
	updateBody.SetLastUpdatedBy(plan.LastUpdatedBy.ValueString())
	updateBody.SetName(plan.Name.ValueString())
	updateBody.SetOrigin(plan.Origin.ValueString())
	if len(plan.Scopes) > 0 {
		var scopesSlice []okta.TrustedOriginScope
		for _, item := range plan.Scopes {
			nestedItem := okta.NewTrustedOriginScopeWithDefaults()
			if !item.AllowedOktaApps.IsNull() && !item.AllowedOktaApps.IsUnknown() {
				var allowedOktaAppsItemSlice []string
				for _, elem := range item.AllowedOktaApps.Elements() {
					if sv, ok := elem.(types.String); ok {
						allowedOktaAppsItemSlice = append(allowedOktaAppsItemSlice, sv.ValueString())
					}
				}
				nestedItem.SetAllowedOktaApps(allowedOktaAppsItemSlice)
			}
			if !item.Type.IsNull() && !item.Type.IsUnknown() {
				nestedItem.SetType(item.Type.ValueString())
			}
			scopesSlice = append(scopesSlice, *nestedItem)
		}
		updateBody.SetScopes(scopesSlice)
	}
	updateBody.SetStatus(plan.Status.ValueString())
	updateReq = updateReq.TrustedOrigin(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating trusted_origin", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetCreatedBy(); v != "" {
		state.CreatedBy = types.StringValue(string(v))
	} else {
		state.CreatedBy = types.StringNull()
	}
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetLastUpdatedBy(); v != "" {
		state.LastUpdatedBy = types.StringValue(string(v))
	} else {
		state.LastUpdatedBy = types.StringNull()
	}
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	if v := result.GetOrigin(); v != "" {
		state.Origin = types.StringValue(string(v))
	} else {
		state.Origin = types.StringNull()
	}
	if v := result.GetStatus(); v != "" {
		state.Status = types.StringValue(string(v))
	} else {
		state.Status = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *trustedOriginResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state trustedOriginModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.TrustedOriginAPI.DeleteTrustedOrigin(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting trusted_origin", err.Error())
		return
	}
}
