// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccOktaUserFactorWebauthn_basic(t *testing.T) {
	resourceName := "okta_user_factor_webauthn.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		CheckDestroy:             testAccCheckOktaUserFactorWebauthnDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccOktaUserFactorWebauthnConfig_basic(),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckOktaUserFactorWebauthnExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccOktaUserFactorWebauthnConfig_basic() string {
	return `
resource "okta_user_factor_webauthn" "test" {
  # user_id = "<user_id>"
	// TODO: Add required attributes
}
`
}

func testAccCheckOktaUserFactorWebauthnExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		// TODO: Implement API call to verify resource exists
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// Retrieve parent param(s) from state attributes:
		// user_id := rs.Primary.Attributes["user_id"]
		// _, _, err := client.UserFactorAPI.GetFactor(context.Background(), user_id, rs.Primary.ID).Execute()
		// if err != nil {
		//     return fmt.Errorf("error getting user_factor_webauthn: %v", err)
		// }

		return nil
	}
}

func testAccCheckOktaUserFactorWebauthnDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "okta_user_factor_webauthn" {
			continue
		}

		// TODO: Implement API call to verify resource is destroyed
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// Retrieve parent param(s) from state attributes:
		// user_id := rs.Primary.Attributes["user_id"]
		// _, httpResp, err := client.UserFactorAPI.GetFactor(context.Background(), user_id, rs.Primary.ID).Execute()
		// if err == nil {
		//     return fmt.Errorf("user_factor_webauthn still exists: %s", rs.Primary.ID)
		// }
		// if httpResp != nil && httpResp.StatusCode != 404 {
		//     return fmt.Errorf("error checking user_factor_webauthn destruction: %v", err)
		// }
	}
	return nil
}

// Ensure context is used
var _ = context.Background
