// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccOktaRoleCResourceSet_basic(t *testing.T) {
	resourceName := "okta_role_c_resource_set.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		CheckDestroy:             testAccCheckOktaRoleCResourceSetDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccOktaRoleCResourceSetConfig_basic(),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckOktaRoleCResourceSetExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccOktaRoleCResourceSetConfig_basic() string {
	return `
resource "okta_role_c_resource_set" "test" {
	// TODO: Add required attributes
}
`
}

func testAccCheckOktaRoleCResourceSetExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		// TODO: Implement API call to verify resource exists
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, _, err := client.RoleCResourceSetAPI.GetResourceSet(context.Background(), rs.Primary.ID).Execute()
		// if err != nil {
		//     return fmt.Errorf("error getting role_c_resource_set: %v", err)
		// }

		return nil
	}
}

func testAccCheckOktaRoleCResourceSetDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "okta_role_c_resource_set" {
			continue
		}

		// TODO: Implement API call to verify resource is destroyed
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, httpResp, err := client.RoleCResourceSetAPI.GetResourceSet(context.Background(), rs.Primary.ID).Execute()
		// if err == nil {
		//     return fmt.Errorf("role_c_resource_set still exists: %s", rs.Primary.ID)
		// }
		// if httpResp != nil && httpResp.StatusCode != 404 {
		//     return fmt.Errorf("error checking role_c_resource_set destruction: %v", err)
		// }
	}
	return nil
}

// Ensure context is used
var _ = context.Background
