// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource              = &brandsTemplatesEmailSettingResource{}
	_ resource.ResourceWithConfigure = &brandsTemplatesEmailSettingResource{}
)

// BrandsTemplatesEmailSettingResource defines the resource implementation.
type brandsTemplatesEmailSettingResource struct {
	Config *config.Config
}

// BrandsTemplatesEmailSettingModel describes the resource data model.
type brandsTemplatesEmailSettingModel struct {
	BrandId      types.String `tfsdk:"brand_id"`
	TemplateName types.String `tfsdk:"template_name"`
	Recipients   types.String `tfsdk:"recipients"`
}

func NewBrandsTemplatesEmailSettingResource() resource.Resource {
	return &brandsTemplatesEmailSettingResource{}
}

func (r *brandsTemplatesEmailSettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_brands_templates_email_setting"
}

func (r *brandsTemplatesEmailSettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *brandsTemplatesEmailSettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "These endpoints allow you to programmatically manage email customizations.",
		Attributes: map[string]schema.Attribute{
			"brand_id": schema.StringAttribute{
				Description: "The ID of the brand",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"template_name": schema.StringAttribute{
				Description: "The name of the email template",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"recipients": schema.StringAttribute{
				Description: "Recipients",
				Optional:    true,
			},
		},
	}
}

func (r *brandsTemplatesEmailSettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state brandsTemplatesEmailSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	brandId := state.BrandId.ValueString()
	templateName := state.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.CustomTemplatesAPI.GetEmailSettings(ctx, brandId, templateName).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading brands_templates_email_setting", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	if v := result.GetRecipients(); v != "" {
		state.Recipients = types.StringValue(string(v))
	} else {
		state.Recipients = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *brandsTemplatesEmailSettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan brandsTemplatesEmailSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	brandId := plan.BrandId.ValueString()
	templateName := plan.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.CustomTemplatesAPI.ReplaceEmailSettings(ctx, brandId, templateName)
	body := okta.NewEmailSettingsWithDefaults()
	body.SetRecipients(plan.Recipients.ValueString())
	createReq = createReq.EmailSettings(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating brands_templates_email_setting", err.Error())
		return
	}
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	if v := result.GetRecipients(); v != "" {
		plan.Recipients = types.StringValue(string(v))
	} else {
		plan.Recipients = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *brandsTemplatesEmailSettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan brandsTemplatesEmailSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state brandsTemplatesEmailSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	brandId := state.BrandId.ValueString()
	templateName := state.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.CustomTemplatesAPI.ReplaceEmailSettings(ctx, brandId, templateName)
	updateBody := okta.NewEmailSettingsWithDefaults()
	updateBody.SetRecipients(plan.Recipients.ValueString())
	updateReq = updateReq.EmailSettings(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating brands_templates_email_setting", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	if v := result.GetRecipients(); v != "" {
		state.Recipients = types.StringValue(string(v))
	} else {
		state.Recipients = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *brandsTemplatesEmailSettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning(
		"Delete Not Supported",
		"This resource cannot be deleted via Terraform.",
	)
}
