// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &userResource{}
	_ resource.ResourceWithConfigure   = &userResource{}
	_ resource.ResourceWithImportState = &userResource{}
)

// UserResource defines the resource implementation.
type userResource struct {
	Config *config.Config
}

// UserModel describes the resource data model.
type userModel struct {
	ID                    types.String               `tfsdk:"id"`
	Activated             types.String               `tfsdk:"activated"`
	Created               types.String               `tfsdk:"created"`
	Credentials           *UserModelCredentialsModel `tfsdk:"credentials"`
	LastLogin             types.String               `tfsdk:"last_login"`
	LastUpdated           types.String               `tfsdk:"last_updated"`
	PasswordChanged       types.String               `tfsdk:"password_changed"`
	Profile               *UserModelProfileModel     `tfsdk:"profile"`
	RealmId               types.String               `tfsdk:"realm_id"`
	Status                types.String               `tfsdk:"status"`
	StatusChanged         types.String               `tfsdk:"status_changed"`
	TransitioningToStatus types.String               `tfsdk:"transitioning_to_status"`
	Type                  *UserModelTypeModel        `tfsdk:"type"`
	GroupIds              types.List                 `tfsdk:"group_ids"`
}

// UserModelCredentialsModel is the nested model for credentials.
type UserModelCredentialsModel struct {
	Password         *UserModelCredentialsModelPasswordModel         `tfsdk:"password"`
	Provider         *UserModelCredentialsModelProviderModel         `tfsdk:"provider"`
	RecoveryQuestion *UserModelCredentialsModelRecoveryQuestionModel `tfsdk:"recovery_question"`
}

// UserModelCredentialsModelPasswordModel is the nested model for password.
type UserModelCredentialsModelPasswordModel struct {
	Hash  *UserModelCredentialsModelPasswordModelHashModel `tfsdk:"hash"`
	Hook  *UserModelCredentialsModelPasswordModelHookModel `tfsdk:"hook"`
	Value types.String                                     `tfsdk:"value"`
}

// UserModelCredentialsModelPasswordModelHashModel is the nested model for hash.
type UserModelCredentialsModelPasswordModelHashModel struct {
	Algorithm       types.String `tfsdk:"algorithm"`
	DigestAlgorithm types.String `tfsdk:"digest_algorithm"`
	IterationCount  types.Int64  `tfsdk:"iteration_count"`
	KeySize         types.Int64  `tfsdk:"key_size"`
	Salt            types.String `tfsdk:"salt"`
	SaltOrder       types.String `tfsdk:"salt_order"`
	Value           types.String `tfsdk:"value"`
	WorkFactor      types.Int64  `tfsdk:"work_factor"`
}

// UserModelCredentialsModelPasswordModelHookModel is the nested model for hook.
type UserModelCredentialsModelPasswordModelHookModel struct {
	Type types.String `tfsdk:"type"`
}

// UserModelCredentialsModelProviderModel is the nested model for provider.
type UserModelCredentialsModelProviderModel struct {
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
}

// UserModelCredentialsModelRecoveryQuestionModel is the nested model for recovery_question.
type UserModelCredentialsModelRecoveryQuestionModel struct {
	Answer   types.String `tfsdk:"answer"`
	Question types.String `tfsdk:"question"`
}

// UserModelProfileModel is the nested model for profile.
type UserModelProfileModel struct {
	City              types.String `tfsdk:"city"`
	CostCenter        types.String `tfsdk:"cost_center"`
	CountryCode       types.String `tfsdk:"country_code"`
	Department        types.String `tfsdk:"department"`
	DisplayName       types.String `tfsdk:"display_name"`
	Division          types.String `tfsdk:"division"`
	Email             types.String `tfsdk:"email"`
	EmployeeNumber    types.String `tfsdk:"employee_number"`
	FirstName         types.String `tfsdk:"first_name"`
	HonorificPrefix   types.String `tfsdk:"honorific_prefix"`
	HonorificSuffix   types.String `tfsdk:"honorific_suffix"`
	LastName          types.String `tfsdk:"last_name"`
	Locale            types.String `tfsdk:"locale"`
	Login             types.String `tfsdk:"login"`
	Manager           types.String `tfsdk:"manager"`
	ManagerId         types.String `tfsdk:"manager_id"`
	MiddleName        types.String `tfsdk:"middle_name"`
	MobilePhone       types.String `tfsdk:"mobile_phone"`
	NickName          types.String `tfsdk:"nick_name"`
	Organization      types.String `tfsdk:"organization"`
	PostalAddress     types.String `tfsdk:"postal_address"`
	PreferredLanguage types.String `tfsdk:"preferred_language"`
	PrimaryPhone      types.String `tfsdk:"primary_phone"`
	ProfileUrl        types.String `tfsdk:"profile_url"`
	SecondEmail       types.String `tfsdk:"second_email"`
	State             types.String `tfsdk:"state"`
	StreetAddress     types.String `tfsdk:"street_address"`
	Timezone          types.String `tfsdk:"timezone"`
	Title             types.String `tfsdk:"title"`
	UserType          types.String `tfsdk:"user_type"`
	ZipCode           types.String `tfsdk:"zip_code"`
}

// UserModelTypeModel is the nested model for type.
type UserModelTypeModel struct {
	Id types.String `tfsdk:"id"`
}

func NewUserResource() resource.Resource {
	return &userResource{}
}

func (r *userResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (r *userResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *userResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Users API provides operations to manage users in your org.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"activated": schema.StringAttribute{
				Description: "The timestamp when the user status transitioned to `ACTIVE`",
				Computed:    true,
			},
			"created": schema.StringAttribute{
				Description: "The timestamp when the user was created",
				Computed:    true,
			},
			"last_login": schema.StringAttribute{
				Description: "The timestamp of the last login",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "The timestamp when the user was last updated",
				Computed:    true,
			},
			"password_changed": schema.StringAttribute{
				Description: "The timestamp when the user's password was last updated",
				Computed:    true,
			},
			"realm_id": schema.StringAttribute{
				Description: "The ID of the realm in which the user is residing.",
				Optional:    true,
			},
			"status": schema.StringAttribute{
				Description: "The current status of the user.",
				Computed:    true,
			},
			"status_changed": schema.StringAttribute{
				Description: "The timestamp when the status of the user last changed",
				Computed:    true,
			},
			"transitioning_to_status": schema.StringAttribute{
				Description: "The target status of an in-progress asynchronous status transition.",
				Computed:    true,
			},
			"group_ids": schema.ListAttribute{
				Description: "The list of group IDs of groups that the user is added to at the time of creation",
				ElementType: types.StringType,
				Optional:    true,
				Sensitive:   true,
			},
		},
		Blocks: map[string]schema.Block{
			"credentials": schema.SingleNestedBlock{
				Description: "Specifies primary authentication and recovery credentials for a user.",
				Blocks: map[string]schema.Block{
					"password": schema.SingleNestedBlock{
						Description: "Specifies a password for a user.",
						Attributes: map[string]schema.Attribute{
							"value": schema.StringAttribute{
								Description: "Specifies the password for a user.",
								Optional:    true,
							},
						},
						Blocks: map[string]schema.Block{
							"hash": schema.SingleNestedBlock{
								Description: "Specifies a hashed password to import into Okta.",
								Attributes: map[string]schema.Attribute{
									"algorithm": schema.StringAttribute{
										Description: "The algorithm used to generate the hash using the password (and salt, when applicable).",
										Optional:    true,
									},
									"digest_algorithm": schema.StringAttribute{
										Description: "Algorithm used to generate the key.",
										Optional:    true,
									},
									"iteration_count": schema.Int64Attribute{
										Description: "The number of iterations used when hashing passwords using PBKDF2.",
										Optional:    true,
									},
									"key_size": schema.Int64Attribute{
										Description: "Size of the derived key in bytes.",
										Optional:    true,
									},
									"salt": schema.StringAttribute{
										Description: "Only required for salted hashes.",
										Optional:    true,
									},
									"salt_order": schema.StringAttribute{
										Description: "Specifies whether salt was pre- or postfixed to the password before hashing.",
										Optional:    true,
									},
									"value": schema.StringAttribute{
										Description: "For SHA-512, SHA-256, SHA-1, MD5, and PBKDF2, this is the actual base64-encoded hash of the password (and salt, if used).",
										Optional:    true,
									},
									"work_factor": schema.Int64Attribute{
										Description: "Governs the strength of the hash and the time required to compute it.",
										Optional:    true,
									},
								},
							},
							"hook": schema.SingleNestedBlock{
								Description: "Specify a [password import inline hook](/openapi/okta-management/management/tags/inlinehook/createpasswordimportinlinehook) to trigger verification of the user's password the first time the user signs in.",
								Attributes: map[string]schema.Attribute{
									"type": schema.StringAttribute{
										Description: "The type of password inline hook.",
										Optional:    true,
									},
								},
							},
						},
					},
					"provider": schema.SingleNestedBlock{
						Description: "Specifies the authentication provider that validates the user password credential.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								Description: "The name of the authentication provider",
								Optional:    true,
							},
							"type": schema.StringAttribute{
								Description: "The type of authentication provider",
								Optional:    true,
							},
						},
					},
					"recovery_question": schema.SingleNestedBlock{
						Description: "Specifies a secret question and answer that's validated (case insensitive) when a user forgets their password or unlocks their account.",
						Attributes: map[string]schema.Attribute{
							"answer": schema.StringAttribute{
								Description: "The answer to the recovery question",
								Optional:    true,
							},
							"question": schema.StringAttribute{
								Description: "The recovery question",
								Optional:    true,
							},
						},
					},
				},
			},
			"profile": schema.SingleNestedBlock{
				Description: "Specifies the default and custom profile properties for a user.",
				Attributes: map[string]schema.Attribute{
					"city": schema.StringAttribute{
						Description: "The city or locality of the user's address (`locality`)",
						Optional:    true,
					},
					"cost_center": schema.StringAttribute{
						Description: "Name of the cost center assigned to a user",
						Optional:    true,
					},
					"country_code": schema.StringAttribute{
						Description: "The country name component of the user's address (`country`).",
						Optional:    true,
					},
					"department": schema.StringAttribute{
						Description: "Name of the user's department",
						Optional:    true,
					},
					"display_name": schema.StringAttribute{
						Description: "Name of the user suitable for display to end users",
						Optional:    true,
					},
					"division": schema.StringAttribute{
						Description: "Name of the user's division",
						Optional:    true,
					},
					"email": schema.StringAttribute{
						Description: "The primary email address of the user.",
						Optional:    true,
					},
					"employee_number": schema.StringAttribute{
						Description: "The organization or company assigned unique identifier for the user",
						Optional:    true,
					},
					"first_name": schema.StringAttribute{
						Description: "Given name of the user (`givenName`)",
						Optional:    true,
					},
					"honorific_prefix": schema.StringAttribute{
						Description: "Honorific prefix(es) of the user, or title in most Western languages",
						Optional:    true,
					},
					"honorific_suffix": schema.StringAttribute{
						Description: "Honorific suffix(es) of the user",
						Optional:    true,
					},
					"last_name": schema.StringAttribute{
						Description: "The family name of the user (`familyName`)",
						Optional:    true,
					},
					"locale": schema.StringAttribute{
						Description: "The user's default location for purposes of localizing items such as currency, date time format, numerical representations, and so on.",
						Optional:    true,
					},
					"login": schema.StringAttribute{
						Description: "The unique identifier for the user (`username`).",
						Optional:    true,
					},
					"manager": schema.StringAttribute{
						Description: "The `displayName` of the user's manager",
						Optional:    true,
					},
					"manager_id": schema.StringAttribute{
						Description: "The `id` of the user's manager",
						Optional:    true,
					},
					"middle_name": schema.StringAttribute{
						Description: "The middle name of the user",
						Optional:    true,
					},
					"mobile_phone": schema.StringAttribute{
						Description: "The mobile phone number of the user",
						Optional:    true,
					},
					"nick_name": schema.StringAttribute{
						Description: "The casual way to address the user in real life",
						Optional:    true,
					},
					"organization": schema.StringAttribute{
						Description: "Name of the the user's organization",
						Optional:    true,
					},
					"postal_address": schema.StringAttribute{
						Description: "Mailing address component of the user's address",
						Optional:    true,
					},
					"preferred_language": schema.StringAttribute{
						Description: "The user's preferred written or spoken language.",
						Optional:    true,
					},
					"primary_phone": schema.StringAttribute{
						Description: "The primary phone number of the user such as a home number",
						Optional:    true,
					},
					"profile_url": schema.StringAttribute{
						Description: "The URL of the user's online profile.",
						Optional:    true,
					},
					"second_email": schema.StringAttribute{
						Description: "The secondary email address of the user typically used for account recovery.",
						Optional:    true,
					},
					"state": schema.StringAttribute{
						Description: "The state or region component of the user's address (`region`)",
						Optional:    true,
					},
					"street_address": schema.StringAttribute{
						Description: "The full street address component of the user's address",
						Optional:    true,
					},
					"timezone": schema.StringAttribute{
						Description: "The user's time zone",
						Optional:    true,
					},
					"title": schema.StringAttribute{
						Description: "The user's title, such as Vice President",
						Optional:    true,
					},
					"user_type": schema.StringAttribute{
						Description: "The property used to describe the organization-to-user relationship, such as employee or contractor  > **Note:** The `userType` property is a standard string attribute and should be treated as a descriptive label rather than a functional setting.",
						Optional:    true,
					},
					"zip_code": schema.StringAttribute{
						Description: "The ZIP code or postal code component of the user's address (`postalCode`)",
						Optional:    true,
					},
				},
			},
			"type": schema.SingleNestedBlock{
				Description: "The ID of the user type.",
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Description: "The ID of the user type",
						Optional:    true,
					},
				},
			},
		},
	}
}
func (r *userResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *userResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state userModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.UserAPI.GetUser(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading user", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Activated = types.StringValue(result.GetActivated().Format(time.RFC3339))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastLogin = types.StringValue(result.GetLastLogin().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.PasswordChanged = types.StringValue(result.GetPasswordChanged().Format(time.RFC3339))
	if v := result.GetRealmId(); v != "" {
		state.RealmId = types.StringValue(string(v))
	} else {
		state.RealmId = types.StringNull()
	}
	state.Status = types.StringValue(string(result.GetStatus()))
	state.StatusChanged = types.StringValue(result.GetStatusChanged().Format(time.RFC3339))
	state.TransitioningToStatus = types.StringValue(string(result.GetTransitioningToStatus()))
	if credentialsRaw0, ok := result.GetCredentialsOk(); ok {
		var credentialsModel0 *UserModelCredentialsModel
		if state.Credentials == nil {
			credentialsModel0 = &UserModelCredentialsModel{}
		} else {
			credentialsModel0 = state.Credentials
		}
		if passwordRaw1, ok := credentialsRaw0.GetPasswordOk(); ok {
			var passwordModel1 *UserModelCredentialsModelPasswordModel
			if credentialsModel0.Password == nil {
				passwordModel1 = &UserModelCredentialsModelPasswordModel{}
			} else {
				passwordModel1 = credentialsModel0.Password
			}
			if hashRaw2, ok := passwordRaw1.GetHashOk(); ok {
				var hashModel2 *UserModelCredentialsModelPasswordModelHashModel
				if passwordModel1.Hash == nil {
					hashModel2 = &UserModelCredentialsModelPasswordModelHashModel{}
				} else {
					hashModel2 = passwordModel1.Hash
				}
				if v := hashRaw2.GetAlgorithm(); v != "" {
					hashModel2.Algorithm = types.StringValue(string(v))
				} else {
					hashModel2.Algorithm = types.StringNull()
				}
				if v := hashRaw2.GetDigestAlgorithm(); v != "" {
					hashModel2.DigestAlgorithm = types.StringValue(string(v))
				} else {
					hashModel2.DigestAlgorithm = types.StringNull()
				}
				hashModel2.IterationCount = types.Int64Value(int64(hashRaw2.GetIterationCount()))
				hashModel2.KeySize = types.Int64Value(int64(hashRaw2.GetKeySize()))
				if v := hashRaw2.GetSalt(); v != "" {
					hashModel2.Salt = types.StringValue(string(v))
				} else {
					hashModel2.Salt = types.StringNull()
				}
				if v := hashRaw2.GetSaltOrder(); v != "" {
					hashModel2.SaltOrder = types.StringValue(string(v))
				} else {
					hashModel2.SaltOrder = types.StringNull()
				}
				if v := hashRaw2.GetValue(); v != "" {
					hashModel2.Value = types.StringValue(string(v))
				} else {
					hashModel2.Value = types.StringNull()
				}
				hashModel2.WorkFactor = types.Int64Value(int64(hashRaw2.GetWorkFactor()))
				passwordModel1.Hash = hashModel2
			}
			if hookRaw2, ok := passwordRaw1.GetHookOk(); ok {
				var hookModel2 *UserModelCredentialsModelPasswordModelHookModel
				if passwordModel1.Hook == nil {
					hookModel2 = &UserModelCredentialsModelPasswordModelHookModel{}
				} else {
					hookModel2 = passwordModel1.Hook
				}
				if v := hookRaw2.GetType(); v != "" {
					hookModel2.Type = types.StringValue(string(v))
				} else {
					hookModel2.Type = types.StringNull()
				}
				passwordModel1.Hook = hookModel2
			}
			if v := passwordRaw1.GetValue(); v != "" {
				passwordModel1.Value = types.StringValue(string(v))
			} else {
				passwordModel1.Value = types.StringNull()
			}
			credentialsModel0.Password = passwordModel1
		}
		if providerRaw1, ok := credentialsRaw0.GetProviderOk(); ok {
			var providerModel1 *UserModelCredentialsModelProviderModel
			if credentialsModel0.Provider == nil {
				providerModel1 = &UserModelCredentialsModelProviderModel{}
			} else {
				providerModel1 = credentialsModel0.Provider
			}
			if v := providerRaw1.GetName(); v != "" {
				providerModel1.Name = types.StringValue(string(v))
			} else {
				providerModel1.Name = types.StringNull()
			}
			if v := providerRaw1.GetType(); v != "" {
				providerModel1.Type = types.StringValue(string(v))
			} else {
				providerModel1.Type = types.StringNull()
			}
			credentialsModel0.Provider = providerModel1
		}
		if recoveryQuestionRaw1, ok := credentialsRaw0.GetRecoveryQuestionOk(); ok {
			var recoveryQuestionModel1 *UserModelCredentialsModelRecoveryQuestionModel
			if credentialsModel0.RecoveryQuestion == nil {
				recoveryQuestionModel1 = &UserModelCredentialsModelRecoveryQuestionModel{}
			} else {
				recoveryQuestionModel1 = credentialsModel0.RecoveryQuestion
			}
			if v := recoveryQuestionRaw1.GetAnswer(); v != "" {
				recoveryQuestionModel1.Answer = types.StringValue(string(v))
			} else {
				recoveryQuestionModel1.Answer = types.StringNull()
			}
			if v := recoveryQuestionRaw1.GetQuestion(); v != "" {
				recoveryQuestionModel1.Question = types.StringValue(string(v))
			} else {
				recoveryQuestionModel1.Question = types.StringNull()
			}
			credentialsModel0.RecoveryQuestion = recoveryQuestionModel1
		}
		state.Credentials = credentialsModel0
	}
	if profileRaw0, ok := result.GetProfileOk(); ok {
		var profileModel0 *UserModelProfileModel
		if state.Profile == nil {
			profileModel0 = &UserModelProfileModel{}
		} else {
			profileModel0 = state.Profile
		}
		if v := profileRaw0.GetCity(); v != "" {
			profileModel0.City = types.StringValue(string(v))
		} else {
			profileModel0.City = types.StringNull()
		}
		if v := profileRaw0.GetCostCenter(); v != "" {
			profileModel0.CostCenter = types.StringValue(string(v))
		} else {
			profileModel0.CostCenter = types.StringNull()
		}
		if v := profileRaw0.GetCountryCode(); v != "" {
			profileModel0.CountryCode = types.StringValue(string(v))
		} else {
			profileModel0.CountryCode = types.StringNull()
		}
		if v := profileRaw0.GetDepartment(); v != "" {
			profileModel0.Department = types.StringValue(string(v))
		} else {
			profileModel0.Department = types.StringNull()
		}
		if v := profileRaw0.GetDisplayName(); v != "" {
			profileModel0.DisplayName = types.StringValue(string(v))
		} else {
			profileModel0.DisplayName = types.StringNull()
		}
		if v := profileRaw0.GetDivision(); v != "" {
			profileModel0.Division = types.StringValue(string(v))
		} else {
			profileModel0.Division = types.StringNull()
		}
		if v := profileRaw0.GetEmail(); v != "" {
			profileModel0.Email = types.StringValue(string(v))
		} else {
			profileModel0.Email = types.StringNull()
		}
		if v := profileRaw0.GetEmployeeNumber(); v != "" {
			profileModel0.EmployeeNumber = types.StringValue(string(v))
		} else {
			profileModel0.EmployeeNumber = types.StringNull()
		}
		if v := profileRaw0.GetFirstName(); v != "" {
			profileModel0.FirstName = types.StringValue(string(v))
		} else {
			profileModel0.FirstName = types.StringNull()
		}
		if v := profileRaw0.GetHonorificPrefix(); v != "" {
			profileModel0.HonorificPrefix = types.StringValue(string(v))
		} else {
			profileModel0.HonorificPrefix = types.StringNull()
		}
		if v := profileRaw0.GetHonorificSuffix(); v != "" {
			profileModel0.HonorificSuffix = types.StringValue(string(v))
		} else {
			profileModel0.HonorificSuffix = types.StringNull()
		}
		if v := profileRaw0.GetLastName(); v != "" {
			profileModel0.LastName = types.StringValue(string(v))
		} else {
			profileModel0.LastName = types.StringNull()
		}
		if v := profileRaw0.GetLocale(); v != "" {
			profileModel0.Locale = types.StringValue(string(v))
		} else {
			profileModel0.Locale = types.StringNull()
		}
		if v := profileRaw0.GetLogin(); v != "" {
			profileModel0.Login = types.StringValue(string(v))
		} else {
			profileModel0.Login = types.StringNull()
		}
		if v := profileRaw0.GetManager(); v != "" {
			profileModel0.Manager = types.StringValue(string(v))
		} else {
			profileModel0.Manager = types.StringNull()
		}
		if v := profileRaw0.GetManagerId(); v != "" {
			profileModel0.ManagerId = types.StringValue(string(v))
		} else {
			profileModel0.ManagerId = types.StringNull()
		}
		if v := profileRaw0.GetMiddleName(); v != "" {
			profileModel0.MiddleName = types.StringValue(string(v))
		} else {
			profileModel0.MiddleName = types.StringNull()
		}
		if v := profileRaw0.GetMobilePhone(); v != "" {
			profileModel0.MobilePhone = types.StringValue(string(v))
		} else {
			profileModel0.MobilePhone = types.StringNull()
		}
		if v := profileRaw0.GetNickName(); v != "" {
			profileModel0.NickName = types.StringValue(string(v))
		} else {
			profileModel0.NickName = types.StringNull()
		}
		if v := profileRaw0.GetOrganization(); v != "" {
			profileModel0.Organization = types.StringValue(string(v))
		} else {
			profileModel0.Organization = types.StringNull()
		}
		if v := profileRaw0.GetPostalAddress(); v != "" {
			profileModel0.PostalAddress = types.StringValue(string(v))
		} else {
			profileModel0.PostalAddress = types.StringNull()
		}
		if v := profileRaw0.GetPreferredLanguage(); v != "" {
			profileModel0.PreferredLanguage = types.StringValue(string(v))
		} else {
			profileModel0.PreferredLanguage = types.StringNull()
		}
		if v := profileRaw0.GetPrimaryPhone(); v != "" {
			profileModel0.PrimaryPhone = types.StringValue(string(v))
		} else {
			profileModel0.PrimaryPhone = types.StringNull()
		}
		if v := profileRaw0.GetProfileUrl(); v != "" {
			profileModel0.ProfileUrl = types.StringValue(string(v))
		} else {
			profileModel0.ProfileUrl = types.StringNull()
		}
		if v := profileRaw0.GetSecondEmail(); v != "" {
			profileModel0.SecondEmail = types.StringValue(string(v))
		} else {
			profileModel0.SecondEmail = types.StringNull()
		}
		if v := profileRaw0.GetState(); v != "" {
			profileModel0.State = types.StringValue(string(v))
		} else {
			profileModel0.State = types.StringNull()
		}
		if v := profileRaw0.GetStreetAddress(); v != "" {
			profileModel0.StreetAddress = types.StringValue(string(v))
		} else {
			profileModel0.StreetAddress = types.StringNull()
		}
		if v := profileRaw0.GetTimezone(); v != "" {
			profileModel0.Timezone = types.StringValue(string(v))
		} else {
			profileModel0.Timezone = types.StringNull()
		}
		if v := profileRaw0.GetTitle(); v != "" {
			profileModel0.Title = types.StringValue(string(v))
		} else {
			profileModel0.Title = types.StringNull()
		}
		if v := profileRaw0.GetUserType(); v != "" {
			profileModel0.UserType = types.StringValue(string(v))
		} else {
			profileModel0.UserType = types.StringNull()
		}
		if v := profileRaw0.GetZipCode(); v != "" {
			profileModel0.ZipCode = types.StringValue(string(v))
		} else {
			profileModel0.ZipCode = types.StringNull()
		}
		state.Profile = profileModel0
	}
	if typeRaw0, ok := result.GetTypeOk(); ok {
		var typeModel0 *UserModelTypeModel
		if state.Type == nil {
			typeModel0 = &UserModelTypeModel{}
		} else {
			typeModel0 = state.Type
		}
		if v := typeRaw0.GetId(); v != "" {
			typeModel0.Id = types.StringValue(string(v))
		} else {
			typeModel0.Id = types.StringNull()
		}
		state.Type = typeModel0
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *userResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan userModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.UserAPI.CreateUser(ctx)
	body := okta.NewCreateUserRequestWithDefaults()
	if plan.Credentials != nil {
		nestedCredentials := okta.NewUserCredentialsWritableWithDefaults()
		body.SetCredentials(*nestedCredentials)
	}
	if !plan.GroupIds.IsNull() && !plan.GroupIds.IsUnknown() {
		var groupIdsSlice []string
		for _, item := range plan.GroupIds.Elements() {
			if sv, ok := item.(types.String); ok {
				groupIdsSlice = append(groupIdsSlice, sv.ValueString())
			}
		}
		body.SetGroupIds(groupIdsSlice)
	}
	if plan.Profile != nil {
		nestedProfile := okta.NewUserProfileWithDefaults()
		if !plan.Profile.City.IsNull() && !plan.Profile.City.IsUnknown() {
			nestedProfile.SetCity(plan.Profile.City.ValueString())
		}
		if !plan.Profile.CostCenter.IsNull() && !plan.Profile.CostCenter.IsUnknown() {
			nestedProfile.SetCostCenter(plan.Profile.CostCenter.ValueString())
		}
		if !plan.Profile.CountryCode.IsNull() && !plan.Profile.CountryCode.IsUnknown() {
			nestedProfile.SetCountryCode(plan.Profile.CountryCode.ValueString())
		}
		if !plan.Profile.Department.IsNull() && !plan.Profile.Department.IsUnknown() {
			nestedProfile.SetDepartment(plan.Profile.Department.ValueString())
		}
		if !plan.Profile.DisplayName.IsNull() && !plan.Profile.DisplayName.IsUnknown() {
			nestedProfile.SetDisplayName(plan.Profile.DisplayName.ValueString())
		}
		if !plan.Profile.Division.IsNull() && !plan.Profile.Division.IsUnknown() {
			nestedProfile.SetDivision(plan.Profile.Division.ValueString())
		}
		if !plan.Profile.Email.IsNull() && !plan.Profile.Email.IsUnknown() {
			nestedProfile.SetEmail(plan.Profile.Email.ValueString())
		}
		if !plan.Profile.EmployeeNumber.IsNull() && !plan.Profile.EmployeeNumber.IsUnknown() {
			nestedProfile.SetEmployeeNumber(plan.Profile.EmployeeNumber.ValueString())
		}
		if !plan.Profile.FirstName.IsNull() && !plan.Profile.FirstName.IsUnknown() {
			nestedProfile.SetFirstName(plan.Profile.FirstName.ValueString())
		}
		if !plan.Profile.HonorificPrefix.IsNull() && !plan.Profile.HonorificPrefix.IsUnknown() {
			nestedProfile.SetHonorificPrefix(plan.Profile.HonorificPrefix.ValueString())
		}
		if !plan.Profile.HonorificSuffix.IsNull() && !plan.Profile.HonorificSuffix.IsUnknown() {
			nestedProfile.SetHonorificSuffix(plan.Profile.HonorificSuffix.ValueString())
		}
		if !plan.Profile.LastName.IsNull() && !plan.Profile.LastName.IsUnknown() {
			nestedProfile.SetLastName(plan.Profile.LastName.ValueString())
		}
		if !plan.Profile.Locale.IsNull() && !plan.Profile.Locale.IsUnknown() {
			nestedProfile.SetLocale(plan.Profile.Locale.ValueString())
		}
		if !plan.Profile.Login.IsNull() && !plan.Profile.Login.IsUnknown() {
			nestedProfile.SetLogin(plan.Profile.Login.ValueString())
		}
		if !plan.Profile.Manager.IsNull() && !plan.Profile.Manager.IsUnknown() {
			nestedProfile.SetManager(plan.Profile.Manager.ValueString())
		}
		if !plan.Profile.ManagerId.IsNull() && !plan.Profile.ManagerId.IsUnknown() {
			nestedProfile.SetManagerId(plan.Profile.ManagerId.ValueString())
		}
		if !plan.Profile.MiddleName.IsNull() && !plan.Profile.MiddleName.IsUnknown() {
			nestedProfile.SetMiddleName(plan.Profile.MiddleName.ValueString())
		}
		if !plan.Profile.MobilePhone.IsNull() && !plan.Profile.MobilePhone.IsUnknown() {
			nestedProfile.SetMobilePhone(plan.Profile.MobilePhone.ValueString())
		}
		if !plan.Profile.NickName.IsNull() && !plan.Profile.NickName.IsUnknown() {
			nestedProfile.SetNickName(plan.Profile.NickName.ValueString())
		}
		if !plan.Profile.Organization.IsNull() && !plan.Profile.Organization.IsUnknown() {
			nestedProfile.SetOrganization(plan.Profile.Organization.ValueString())
		}
		if !plan.Profile.PostalAddress.IsNull() && !plan.Profile.PostalAddress.IsUnknown() {
			nestedProfile.SetPostalAddress(plan.Profile.PostalAddress.ValueString())
		}
		if !plan.Profile.PreferredLanguage.IsNull() && !plan.Profile.PreferredLanguage.IsUnknown() {
			nestedProfile.SetPreferredLanguage(plan.Profile.PreferredLanguage.ValueString())
		}
		if !plan.Profile.PrimaryPhone.IsNull() && !plan.Profile.PrimaryPhone.IsUnknown() {
			nestedProfile.SetPrimaryPhone(plan.Profile.PrimaryPhone.ValueString())
		}
		if !plan.Profile.ProfileUrl.IsNull() && !plan.Profile.ProfileUrl.IsUnknown() {
			nestedProfile.SetProfileUrl(plan.Profile.ProfileUrl.ValueString())
		}
		if !plan.Profile.SecondEmail.IsNull() && !plan.Profile.SecondEmail.IsUnknown() {
			nestedProfile.SetSecondEmail(plan.Profile.SecondEmail.ValueString())
		}
		if !plan.Profile.State.IsNull() && !plan.Profile.State.IsUnknown() {
			nestedProfile.SetState(plan.Profile.State.ValueString())
		}
		if !plan.Profile.StreetAddress.IsNull() && !plan.Profile.StreetAddress.IsUnknown() {
			nestedProfile.SetStreetAddress(plan.Profile.StreetAddress.ValueString())
		}
		if !plan.Profile.Timezone.IsNull() && !plan.Profile.Timezone.IsUnknown() {
			nestedProfile.SetTimezone(plan.Profile.Timezone.ValueString())
		}
		if !plan.Profile.Title.IsNull() && !plan.Profile.Title.IsUnknown() {
			nestedProfile.SetTitle(plan.Profile.Title.ValueString())
		}
		if !plan.Profile.UserType.IsNull() && !plan.Profile.UserType.IsUnknown() {
			nestedProfile.SetUserType(plan.Profile.UserType.ValueString())
		}
		if !plan.Profile.ZipCode.IsNull() && !plan.Profile.ZipCode.IsUnknown() {
			nestedProfile.SetZipCode(plan.Profile.ZipCode.ValueString())
		}
		body.SetProfile(*nestedProfile)
	}
	body.SetRealmId(plan.RealmId.ValueString())
	createReq = createReq.Body(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating user", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Activated = types.StringValue(result.GetActivated().Format(time.RFC3339))
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.LastLogin = types.StringValue(result.GetLastLogin().Format(time.RFC3339))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	plan.PasswordChanged = types.StringValue(result.GetPasswordChanged().Format(time.RFC3339))
	if v := result.GetRealmId(); v != "" {
		plan.RealmId = types.StringValue(string(v))
	} else {
		plan.RealmId = types.StringNull()
	}
	plan.Status = types.StringValue(string(result.GetStatus()))
	plan.StatusChanged = types.StringValue(result.GetStatusChanged().Format(time.RFC3339))
	plan.TransitioningToStatus = types.StringValue(string(result.GetTransitioningToStatus()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *userResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan userModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state userModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.UserAPI.ReplaceUser(ctx, id)
	updateBody := okta.NewUpdateUserRequestWithDefaults()
	if plan.Credentials != nil {
		nestedCredentials := okta.NewUserCredentialsWithDefaults()
		if !plan.Credentials.Provider.IsNull() && !plan.Credentials.Provider.IsUnknown() {
			nestedCredentials.SetProvider(plan.Credentials.Provider.ValueString())
		}
		updateBody.SetCredentials(*nestedCredentials)
	}
	if plan.Profile != nil {
		nestedProfile := okta.NewUserProfileWithDefaults()
		if !plan.Profile.City.IsNull() && !plan.Profile.City.IsUnknown() {
			nestedProfile.SetCity(plan.Profile.City.ValueString())
		}
		if !plan.Profile.CostCenter.IsNull() && !plan.Profile.CostCenter.IsUnknown() {
			nestedProfile.SetCostCenter(plan.Profile.CostCenter.ValueString())
		}
		if !plan.Profile.CountryCode.IsNull() && !plan.Profile.CountryCode.IsUnknown() {
			nestedProfile.SetCountryCode(plan.Profile.CountryCode.ValueString())
		}
		if !plan.Profile.Department.IsNull() && !plan.Profile.Department.IsUnknown() {
			nestedProfile.SetDepartment(plan.Profile.Department.ValueString())
		}
		if !plan.Profile.DisplayName.IsNull() && !plan.Profile.DisplayName.IsUnknown() {
			nestedProfile.SetDisplayName(plan.Profile.DisplayName.ValueString())
		}
		if !plan.Profile.Division.IsNull() && !plan.Profile.Division.IsUnknown() {
			nestedProfile.SetDivision(plan.Profile.Division.ValueString())
		}
		if !plan.Profile.Email.IsNull() && !plan.Profile.Email.IsUnknown() {
			nestedProfile.SetEmail(plan.Profile.Email.ValueString())
		}
		if !plan.Profile.EmployeeNumber.IsNull() && !plan.Profile.EmployeeNumber.IsUnknown() {
			nestedProfile.SetEmployeeNumber(plan.Profile.EmployeeNumber.ValueString())
		}
		if !plan.Profile.FirstName.IsNull() && !plan.Profile.FirstName.IsUnknown() {
			nestedProfile.SetFirstName(plan.Profile.FirstName.ValueString())
		}
		if !plan.Profile.HonorificPrefix.IsNull() && !plan.Profile.HonorificPrefix.IsUnknown() {
			nestedProfile.SetHonorificPrefix(plan.Profile.HonorificPrefix.ValueString())
		}
		if !plan.Profile.HonorificSuffix.IsNull() && !plan.Profile.HonorificSuffix.IsUnknown() {
			nestedProfile.SetHonorificSuffix(plan.Profile.HonorificSuffix.ValueString())
		}
		if !plan.Profile.LastName.IsNull() && !plan.Profile.LastName.IsUnknown() {
			nestedProfile.SetLastName(plan.Profile.LastName.ValueString())
		}
		if !plan.Profile.Locale.IsNull() && !plan.Profile.Locale.IsUnknown() {
			nestedProfile.SetLocale(plan.Profile.Locale.ValueString())
		}
		if !plan.Profile.Login.IsNull() && !plan.Profile.Login.IsUnknown() {
			nestedProfile.SetLogin(plan.Profile.Login.ValueString())
		}
		if !plan.Profile.Manager.IsNull() && !plan.Profile.Manager.IsUnknown() {
			nestedProfile.SetManager(plan.Profile.Manager.ValueString())
		}
		if !plan.Profile.ManagerId.IsNull() && !plan.Profile.ManagerId.IsUnknown() {
			nestedProfile.SetManagerId(plan.Profile.ManagerId.ValueString())
		}
		if !plan.Profile.MiddleName.IsNull() && !plan.Profile.MiddleName.IsUnknown() {
			nestedProfile.SetMiddleName(plan.Profile.MiddleName.ValueString())
		}
		if !plan.Profile.MobilePhone.IsNull() && !plan.Profile.MobilePhone.IsUnknown() {
			nestedProfile.SetMobilePhone(plan.Profile.MobilePhone.ValueString())
		}
		if !plan.Profile.NickName.IsNull() && !plan.Profile.NickName.IsUnknown() {
			nestedProfile.SetNickName(plan.Profile.NickName.ValueString())
		}
		if !plan.Profile.Organization.IsNull() && !plan.Profile.Organization.IsUnknown() {
			nestedProfile.SetOrganization(plan.Profile.Organization.ValueString())
		}
		if !plan.Profile.PostalAddress.IsNull() && !plan.Profile.PostalAddress.IsUnknown() {
			nestedProfile.SetPostalAddress(plan.Profile.PostalAddress.ValueString())
		}
		if !plan.Profile.PreferredLanguage.IsNull() && !plan.Profile.PreferredLanguage.IsUnknown() {
			nestedProfile.SetPreferredLanguage(plan.Profile.PreferredLanguage.ValueString())
		}
		if !plan.Profile.PrimaryPhone.IsNull() && !plan.Profile.PrimaryPhone.IsUnknown() {
			nestedProfile.SetPrimaryPhone(plan.Profile.PrimaryPhone.ValueString())
		}
		if !plan.Profile.ProfileUrl.IsNull() && !plan.Profile.ProfileUrl.IsUnknown() {
			nestedProfile.SetProfileUrl(plan.Profile.ProfileUrl.ValueString())
		}
		if !plan.Profile.SecondEmail.IsNull() && !plan.Profile.SecondEmail.IsUnknown() {
			nestedProfile.SetSecondEmail(plan.Profile.SecondEmail.ValueString())
		}
		if !plan.Profile.State.IsNull() && !plan.Profile.State.IsUnknown() {
			nestedProfile.SetState(plan.Profile.State.ValueString())
		}
		if !plan.Profile.StreetAddress.IsNull() && !plan.Profile.StreetAddress.IsUnknown() {
			nestedProfile.SetStreetAddress(plan.Profile.StreetAddress.ValueString())
		}
		if !plan.Profile.Timezone.IsNull() && !plan.Profile.Timezone.IsUnknown() {
			nestedProfile.SetTimezone(plan.Profile.Timezone.ValueString())
		}
		if !plan.Profile.Title.IsNull() && !plan.Profile.Title.IsUnknown() {
			nestedProfile.SetTitle(plan.Profile.Title.ValueString())
		}
		if !plan.Profile.UserType.IsNull() && !plan.Profile.UserType.IsUnknown() {
			nestedProfile.SetUserType(plan.Profile.UserType.ValueString())
		}
		if !plan.Profile.ZipCode.IsNull() && !plan.Profile.ZipCode.IsUnknown() {
			nestedProfile.SetZipCode(plan.Profile.ZipCode.ValueString())
		}
		updateBody.SetProfile(*nestedProfile)
	}
	updateBody.SetRealmId(plan.RealmId.ValueString())
	updateReq = updateReq.User(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating user", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Activated = types.StringValue(result.GetActivated().Format(time.RFC3339))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastLogin = types.StringValue(result.GetLastLogin().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.PasswordChanged = types.StringValue(result.GetPasswordChanged().Format(time.RFC3339))
	if v := result.GetRealmId(); v != "" {
		state.RealmId = types.StringValue(string(v))
	} else {
		state.RealmId = types.StringNull()
	}
	state.Status = types.StringValue(string(result.GetStatus()))
	state.StatusChanged = types.StringValue(result.GetStatusChanged().Format(time.RFC3339))
	state.TransitioningToStatus = types.StringValue(string(result.GetTransitioningToStatus()))
	state.GroupIds = plan.GroupIds

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *userResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state userModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.UserAPI.DeleteUser(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting user", err.Error())
		return
	}
}
