// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &serviceAccountResource{}
	_ resource.ResourceWithConfigure   = &serviceAccountResource{}
	_ resource.ResourceWithImportState = &serviceAccountResource{}
)

// ServiceAccountResource defines the resource implementation.
type serviceAccountResource struct {
	Config *config.Config
}

// ServiceAccountModel describes the resource data model.
type serviceAccountModel struct {
	ID                    types.String `tfsdk:"id"`
	ContainerGlobalName   types.String `tfsdk:"container_global_name"`
	ContainerInstanceName types.String `tfsdk:"container_instance_name"`
	ContainerOrn          types.String `tfsdk:"container_orn"`
	Created               types.String `tfsdk:"created"`
	Description           types.String `tfsdk:"description"`
	LastUpdated           types.String `tfsdk:"last_updated"`
	Name                  types.String `tfsdk:"name"`
	OwnerGroupIds         types.List   `tfsdk:"owner_group_ids"`
	OwnerUserIds          types.List   `tfsdk:"owner_user_ids"`
	Password              types.String `tfsdk:"password"`
	Status                types.String `tfsdk:"status"`
	StatusDetail          types.String `tfsdk:"status_detail"`
	Username              types.String `tfsdk:"username"`
}

func NewServiceAccountResource() resource.Resource {
	return &serviceAccountResource{}
}

func (r *serviceAccountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_account"
}

func (r *serviceAccountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *serviceAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Service Accounts API provides operations to manage SaaS or On-Prem Provisioning (OPP) app accounts as service accounts.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"container_global_name": schema.StringAttribute{
				Description: "The key name of the app in the Okta Integration Network (OIN)",
				Computed:    true,
			},
			"container_instance_name": schema.StringAttribute{
				Description: "The app instance label",
				Computed:    true,
			},
			"container_orn": schema.StringAttribute{
				Description: "The [ORN](/openapi/okta-management/guides/roles/#okta-resource-name-orn) of the relevant resource.",
				Required:    true,
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the app service account was created",
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Description: "The description of the app service account",
				Optional:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the app service account was last updated",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "The user-defined name for the app service account",
				Required:    true,
			},
			"owner_group_ids": schema.ListAttribute{
				Description: "A list of IDs of the Okta groups who own the app service account",
				ElementType: types.StringType,
				Optional:    true,
			},
			"owner_user_ids": schema.ListAttribute{
				Description: "A list of IDs of the Okta users who own the app service account",
				ElementType: types.StringType,
				Optional:    true,
			},
			"password": schema.StringAttribute{
				Description: "The app service account password",
				Required:    true,
			},
			"status": schema.StringAttribute{
				Description: "Describes the current status of a service account",
				Computed:    true,
			},
			"status_detail": schema.StringAttribute{
				Description: "Describes the detailed status of a service account",
				Computed:    true,
			},
			"username": schema.StringAttribute{
				Description: "The username that serves as the direct link to your managed app account.",
				Required:    true,
			},
		},
	}
}
func (r *serviceAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *serviceAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state serviceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.ServiceAccountAPI.GetAppServiceAccount(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading service_account", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.ContainerGlobalName = types.StringValue(string(result.GetContainerGlobalName()))
	state.ContainerInstanceName = types.StringValue(string(result.GetContainerInstanceName()))
	state.ContainerOrn = types.StringValue(string(result.GetContainerOrn()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetDescription(); v != "" {
		state.Description = types.StringValue(string(v))
	} else {
		state.Description = types.StringNull()
	}
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.Name = types.StringValue(string(result.GetName()))
	state.Password = types.StringValue(string(result.GetPassword()))
	state.Status = types.StringValue(string(result.GetStatus()))
	state.StatusDetail = types.StringValue(string(result.GetStatusDetail()))
	state.Username = types.StringValue(string(result.GetUsername()))

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *serviceAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan serviceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.ServiceAccountAPI.CreateAppServiceAccount(ctx)
	body := okta.NewAppServiceAccountWithDefaults()
	body.SetContainerOrn(plan.ContainerOrn.ValueString())
	body.SetDescription(plan.Description.ValueString())
	body.SetName(plan.Name.ValueString())
	if !plan.OwnerGroupIds.IsNull() && !plan.OwnerGroupIds.IsUnknown() {
		var ownerGroupIdsSlice []string
		for _, item := range plan.OwnerGroupIds.Elements() {
			if sv, ok := item.(types.String); ok {
				ownerGroupIdsSlice = append(ownerGroupIdsSlice, sv.ValueString())
			}
		}
		body.SetOwnerGroupIds(ownerGroupIdsSlice)
	}
	if !plan.OwnerUserIds.IsNull() && !plan.OwnerUserIds.IsUnknown() {
		var ownerUserIdsSlice []string
		for _, item := range plan.OwnerUserIds.Elements() {
			if sv, ok := item.(types.String); ok {
				ownerUserIdsSlice = append(ownerUserIdsSlice, sv.ValueString())
			}
		}
		body.SetOwnerUserIds(ownerUserIdsSlice)
	}
	body.SetPassword(plan.Password.ValueString())
	body.SetUsername(plan.Username.ValueString())
	createReq = createReq.Body(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating service_account", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.ContainerGlobalName = types.StringValue(string(result.GetContainerGlobalName()))
	plan.ContainerInstanceName = types.StringValue(string(result.GetContainerInstanceName()))
	plan.ContainerOrn = types.StringValue(string(result.GetContainerOrn()))
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetDescription(); v != "" {
		plan.Description = types.StringValue(string(v))
	} else {
		plan.Description = types.StringNull()
	}
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	plan.Name = types.StringValue(string(result.GetName()))
	plan.Password = types.StringValue(string(result.GetPassword()))
	plan.Status = types.StringValue(string(result.GetStatus()))
	plan.StatusDetail = types.StringValue(string(result.GetStatusDetail()))
	plan.Username = types.StringValue(string(result.GetUsername()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *serviceAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan serviceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state serviceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.ServiceAccountAPI.UpdateAppServiceAccount(ctx, id)
	updateBody := okta.NewAppServiceAccountForUpdateWithDefaults()
	updateBody.SetDescription(plan.Description.ValueString())
	updateBody.SetName(plan.Name.ValueString())
	if !plan.OwnerGroupIds.IsNull() && !plan.OwnerGroupIds.IsUnknown() {
		var ownerGroupIdsSlice []string
		for _, item := range plan.OwnerGroupIds.Elements() {
			if sv, ok := item.(types.String); ok {
				ownerGroupIdsSlice = append(ownerGroupIdsSlice, sv.ValueString())
			}
		}
		updateBody.SetOwnerGroupIds(ownerGroupIdsSlice)
	}
	if !plan.OwnerUserIds.IsNull() && !plan.OwnerUserIds.IsUnknown() {
		var ownerUserIdsSlice []string
		for _, item := range plan.OwnerUserIds.Elements() {
			if sv, ok := item.(types.String); ok {
				ownerUserIdsSlice = append(ownerUserIdsSlice, sv.ValueString())
			}
		}
		updateBody.SetOwnerUserIds(ownerUserIdsSlice)
	}
	updateReq = updateReq.Body(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating service_account", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.ContainerGlobalName = types.StringValue(string(result.GetContainerGlobalName()))
	state.ContainerInstanceName = types.StringValue(string(result.GetContainerInstanceName()))
	state.ContainerOrn = types.StringValue(string(result.GetContainerOrn()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetDescription(); v != "" {
		state.Description = types.StringValue(string(v))
	} else {
		state.Description = types.StringNull()
	}
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.Name = types.StringValue(string(result.GetName()))
	state.Password = types.StringValue(string(result.GetPassword()))
	state.Status = types.StringValue(string(result.GetStatus()))
	state.StatusDetail = types.StringValue(string(result.GetStatusDetail()))
	state.Username = types.StringValue(string(result.GetUsername()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *serviceAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state serviceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.ServiceAccountAPI.DeleteAppServiceAccount(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting service_account", err.Error())
		return
	}
}
