// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"strings"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &iamResourceSetsBindingResource{}
	_ resource.ResourceWithConfigure   = &iamResourceSetsBindingResource{}
	_ resource.ResourceWithImportState = &iamResourceSetsBindingResource{}
)

// IamResourceSetsBindingResource defines the resource implementation.
type iamResourceSetsBindingResource struct {
	Config *config.Config
}

// IamResourceSetsBindingModel describes the resource data model.
type iamResourceSetsBindingModel struct {
	ID                   types.String `tfsdk:"id"`
	ResourceSetIdOrLabel types.String `tfsdk:"resource_set_id_or_label"`
	Members              types.List   `tfsdk:"members"`
	Role                 types.String `tfsdk:"role"`
}

func NewIamResourceSetsBindingResource() resource.Resource {
	return &iamResourceSetsBindingResource{}
}

func (r *iamResourceSetsBindingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_resource_sets_binding"
}

func (r *iamResourceSetsBindingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *iamResourceSetsBindingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Role Resource Set Bindings API provides operations to assign members to a [Custom Role](https://developer.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"resource_set_id_or_label": schema.StringAttribute{
				Description: "`id` or `label` of the resource set",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"members": schema.ListAttribute{
				Description: "URLs to user and/or group instances that are assigned to the role",
				ElementType: types.StringType,
				Optional:    true,
				Sensitive:   true,
			},
			"role": schema.StringAttribute{
				Description: "Unique key for the role",
				Optional:    true,
				Sensitive:   true,
			},
		},
	}
}
func (r *iamResourceSetsBindingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: {resource_set_id_or_label}/{id}
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Import ID must be in the format: {resource_set_id_or_label}/{id}",
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("resource_set_id_or_label"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("id"), parts[1])...)
}

func (r *iamResourceSetsBindingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state iamResourceSetsBindingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	resourceSetIdOrLabel := state.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.RoleDResourceSetBindingAPI.GetBinding(ctx, resourceSetIdOrLabel, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading iam_resource_sets_binding", err.Error())
		return
	}
	_ = result // all properties are nested blocks — no scalar fields to map from response

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *iamResourceSetsBindingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan iamResourceSetsBindingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resourceSetIdOrLabel := plan.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.RoleDResourceSetBindingAPI.CreateResourceSetBinding(ctx, resourceSetIdOrLabel)
	body := okta.NewResourceSetBindingCreateRequestWithDefaults()
	if !plan.Members.IsNull() && !plan.Members.IsUnknown() {
		var membersSlice []string
		for _, item := range plan.Members.Elements() {
			if sv, ok := item.(types.String); ok {
				membersSlice = append(membersSlice, sv.ValueString())
			}
		}
		body.SetMembers(membersSlice)
	}
	body.SetRole(plan.Role.ValueString())
	createReq = createReq.Instance(*body)
	_, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating iam_resource_sets_binding", err.Error())
		return
	}
	// Create returns no body or ID; set ID from the plan field.
	plan.ID = plan.Role

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *iamResourceSetsBindingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddWarning(
		"Update Not Supported",
		"This resource does not support in-place updates. Changes will require resource replacement.",
	)
}

func (r *iamResourceSetsBindingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state iamResourceSetsBindingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	resourceSetIdOrLabel := state.ResourceSetIdOrLabel.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.RoleDResourceSetBindingAPI.DeleteBinding(ctx, resourceSetIdOrLabel, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting iam_resource_sets_binding", err.Error())
		return
	}
}
