// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &applicationSecurePasswordStoreResource{}
	_ resource.ResourceWithConfigure   = &applicationSecurePasswordStoreResource{}
	_ resource.ResourceWithImportState = &applicationSecurePasswordStoreResource{}
)

// ApplicationSecurePasswordStoreResource defines the resource implementation.
type applicationSecurePasswordStoreResource struct {
	Config *config.Config
}

// ApplicationSecurePasswordStoreModel describes the resource data model.
type applicationSecurePasswordStoreModel struct {
	ID                   types.String                                           `tfsdk:"id"`
	SignOnMode           types.String                                           `tfsdk:"sign_on_mode"`
	Accessibility        *ApplicationSecurePasswordStoreModelAccessibilityModel `tfsdk:"accessibility"`
	Created              types.String                                           `tfsdk:"created"`
	Credentials          *ApplicationSecurePasswordStoreModelCredentialsModel   `tfsdk:"credentials"`
	ExpressConfiguration types.String                                           `tfsdk:"express_configuration"`
	Features             types.List                                             `tfsdk:"features"`
	Label                types.String                                           `tfsdk:"label"`
	LastUpdated          types.String                                           `tfsdk:"last_updated"`
	Licensing            *ApplicationSecurePasswordStoreModelLicensingModel     `tfsdk:"licensing"`
	Name                 types.String                                           `tfsdk:"name"`
	Orn                  types.String                                           `tfsdk:"orn"`
	Profile              types.Map                                              `tfsdk:"profile"`
	Settings             *ApplicationSecurePasswordStoreModelSettingsModel      `tfsdk:"settings"`
	Status               types.String                                           `tfsdk:"status"`
	UniversalLogout      types.String                                           `tfsdk:"universal_logout"`
	Visibility           *ApplicationSecurePasswordStoreModelVisibilityModel    `tfsdk:"visibility"`
}

// ApplicationSecurePasswordStoreModelAccessibilityModel is the nested model for accessibility.
type ApplicationSecurePasswordStoreModelAccessibilityModel struct {
	ErrorRedirectUrl types.String `tfsdk:"error_redirect_url"`
	LoginRedirectUrl types.String `tfsdk:"login_redirect_url"`
	SelfService      types.Bool   `tfsdk:"self_service"`
}

// ApplicationSecurePasswordStoreModelCredentialsModel is the nested model for credentials.
type ApplicationSecurePasswordStoreModelCredentialsModel struct {
	Password         *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel         `tfsdk:"password"`
	RevealPassword   types.Bool                                                                `tfsdk:"reveal_password"`
	Scheme           types.String                                                              `tfsdk:"scheme"`
	Signing          *ApplicationSecurePasswordStoreModelCredentialsModelSigningModel          `tfsdk:"signing"`
	UserName         types.String                                                              `tfsdk:"user_name"`
	UserNameTemplate *ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel `tfsdk:"user_name_template"`
}

// ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel is the nested model for password.
type ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel struct {
	Hash  *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel `tfsdk:"hash"`
	Hook  *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel `tfsdk:"hook"`
	Value types.String                                                               `tfsdk:"value"`
}

// ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel is the nested model for hash.
type ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel struct {
	Algorithm       types.String `tfsdk:"algorithm"`
	DigestAlgorithm types.String `tfsdk:"digest_algorithm"`
	IterationCount  types.Int64  `tfsdk:"iteration_count"`
	KeySize         types.Int64  `tfsdk:"key_size"`
	Salt            types.String `tfsdk:"salt"`
	SaltOrder       types.String `tfsdk:"salt_order"`
	Value           types.String `tfsdk:"value"`
	WorkFactor      types.Int64  `tfsdk:"work_factor"`
}

// ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel is the nested model for hook.
type ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel struct {
	Type types.String `tfsdk:"type"`
}

// ApplicationSecurePasswordStoreModelCredentialsModelSigningModel is the nested model for signing.
type ApplicationSecurePasswordStoreModelCredentialsModelSigningModel struct {
	Kid          types.String `tfsdk:"kid"`
	LastRotated  types.String `tfsdk:"last_rotated"`
	NextRotation types.String `tfsdk:"next_rotation"`
	RotationMode types.String `tfsdk:"rotation_mode"`
	Use          types.String `tfsdk:"use"`
}

// ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel is the nested model for user_name_template.
type ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel struct {
	PushStatus types.String `tfsdk:"push_status"`
	Template   types.String `tfsdk:"template"`
	Type       types.String `tfsdk:"type"`
	UserSuffix types.String `tfsdk:"user_suffix"`
}

// ApplicationSecurePasswordStoreModelLicensingModel is the nested model for licensing.
type ApplicationSecurePasswordStoreModelLicensingModel struct {
	SeatCount types.Int64 `tfsdk:"seat_count"`
}

// ApplicationSecurePasswordStoreModelSettingsModel is the nested model for settings.
type ApplicationSecurePasswordStoreModelSettingsModel struct {
	App                *ApplicationSecurePasswordStoreModelSettingsModelAppModel           `tfsdk:"app"`
	EmOptInStatus      types.String                                                        `tfsdk:"em_opt_in_status"`
	IdentityStoreId    types.String                                                        `tfsdk:"identity_store_id"`
	ImplicitAssignment types.Bool                                                          `tfsdk:"implicit_assignment"`
	InlineHookId       types.String                                                        `tfsdk:"inline_hook_id"`
	Notes              *ApplicationSecurePasswordStoreModelSettingsModelNotesModel         `tfsdk:"notes"`
	Notifications      *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel `tfsdk:"notifications"`
}

// ApplicationSecurePasswordStoreModelSettingsModelAppModel is the nested model for app.
type ApplicationSecurePasswordStoreModelSettingsModelAppModel struct {
	OptionalField1      types.String `tfsdk:"optional_field1"`
	OptionalField1Value types.String `tfsdk:"optional_field1_value"`
	OptionalField2      types.String `tfsdk:"optional_field2"`
	OptionalField2Value types.String `tfsdk:"optional_field2_value"`
	OptionalField3      types.String `tfsdk:"optional_field3"`
	OptionalField3Value types.String `tfsdk:"optional_field3_value"`
	PasswordField       types.String `tfsdk:"password_field"`
	Url                 types.String `tfsdk:"url"`
	UsernameField       types.String `tfsdk:"username_field"`
}

// ApplicationSecurePasswordStoreModelSettingsModelNotesModel is the nested model for notes.
type ApplicationSecurePasswordStoreModelSettingsModelNotesModel struct {
	Admin   types.String `tfsdk:"admin"`
	Enduser types.String `tfsdk:"enduser"`
}

// ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel is the nested model for notifications.
type ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel struct {
	Vpn *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel `tfsdk:"vpn"`
}

// ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel is the nested model for vpn.
type ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel struct {
	HelpUrl types.String                                                                            `tfsdk:"help_url"`
	Message types.String                                                                            `tfsdk:"message"`
	Network *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel `tfsdk:"network"`
}

// ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel is the nested model for network.
type ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel struct {
	Connection types.String `tfsdk:"connection"`
	Exclude    types.List   `tfsdk:"exclude"`
	Include    types.List   `tfsdk:"include"`
}

// ApplicationSecurePasswordStoreModelVisibilityModel is the nested model for visibility.
type ApplicationSecurePasswordStoreModelVisibilityModel struct {
	AppLinks          types.Object                                                 `tfsdk:"app_links"`
	AutoLaunch        types.Bool                                                   `tfsdk:"auto_launch"`
	AutoSubmitToolbar types.Bool                                                   `tfsdk:"auto_submit_toolbar"`
	Hide              *ApplicationSecurePasswordStoreModelVisibilityModelHideModel `tfsdk:"hide"`
}

// ApplicationSecurePasswordStoreModelVisibilityModelHideModel is the nested model for hide.
type ApplicationSecurePasswordStoreModelVisibilityModelHideModel struct {
	IOS types.Bool `tfsdk:"i_os"`
	Web types.Bool `tfsdk:"web"`
}

func NewApplicationSecurePasswordStoreResource() resource.Resource {
	return &applicationSecurePasswordStoreResource{}
}

func (r *applicationSecurePasswordStoreResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_secure_password_store"
}

func (r *applicationSecurePasswordStoreResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *applicationSecurePasswordStoreResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Applications API provides operations to manage apps in your org.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"sign_on_mode": schema.StringAttribute{
				Description: "Discriminator field identifying the variant type. Must be set to \"SECURE_PASSWORD_STORE\".",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the application object was created",
				Computed:    true,
			},
			"express_configuration": schema.StringAttribute{
				Description: "<div class='x-lifecycle-container'><x-lifecycle class='oie'></x-lifecycle></div> Indicates which Express Configuration capabilities the app supports and has enabled",
				Computed:    true,
			},
			"features": schema.ListAttribute{
				Description: "Enabled app features > **Note:** See [Application Features](/openapi/okta-management/management/tags/applicationfeatures/) for app provisioning features.",
				ElementType: types.StringType,
				Computed:    true,
			},
			"label": schema.StringAttribute{
				Description: "User-defined display name for app",
				Required:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the application object was last updated",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "`template_sps` is the key name for a SWA app instance that uses HTTP POST and doesn't require a browser plugin",
				Required:    true,
			},
			"orn": schema.StringAttribute{
				Description: "The Okta resource name (ORN) for the current app instance",
				Computed:    true,
			},
			"profile": schema.MapAttribute{
				Description: "Contains any valid JSON schema for specifying properties that can be referenced from a request (only available to OAuth 2.",
				ElementType: types.StringType,
				Optional:    true,
			},
			"status": schema.StringAttribute{
				Description: "App instance status",
				Computed:    true,
			},
			"universal_logout": schema.StringAttribute{
				Description: "<div class='x-lifecycle-container'><x-lifecycle class='oie'></x-lifecycle></div> Universal Logout properties for the app.",
				Computed:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"accessibility": schema.SingleNestedBlock{
				Description: "Specifies access settings for the app",
				Attributes: map[string]schema.Attribute{
					"error_redirect_url": schema.StringAttribute{
						Description: "Custom error page URL for the app",
						Optional:    true,
					},
					"login_redirect_url": schema.StringAttribute{
						Description: "Custom login page URL for the app > **Note:** The `loginRedirectUrl` property is deprecated in Identity Engine.",
						Optional:    true,
					},
					"self_service": schema.BoolAttribute{
						Description: "Represents whether the app can be self-assignable by users",
						Optional:    true,
					},
				},
			},
			"credentials": schema.SingleNestedBlock{
				Description: "Credentials",
				Attributes: map[string]schema.Attribute{
					"reveal_password": schema.BoolAttribute{
						Description: "Allow users to securely see their password",
						Optional:    true,
					},
					"scheme": schema.StringAttribute{
						Description: "Apps with `BASIC_AUTH`, `BROWSER_PLUGIN`, or `SECURE_PASSWORD_STORE` sign-on modes have credentials vaulted by Okta and can be configured with the following schemes.",
						Optional:    true,
					},
					"user_name": schema.StringAttribute{
						Description: "Shared username for the app",
						Optional:    true,
					},
				},
				Blocks: map[string]schema.Block{
					"password": schema.SingleNestedBlock{
						Description: "Specifies a password for a user.",
						Attributes: map[string]schema.Attribute{
							"value": schema.StringAttribute{
								Description: "Specifies the password for a user.",
								Optional:    true,
							},
						},
						Blocks: map[string]schema.Block{
							"hash": schema.SingleNestedBlock{
								Description: "Specifies a hashed password to import into Okta.",
								Attributes: map[string]schema.Attribute{
									"algorithm": schema.StringAttribute{
										Description: "The algorithm used to generate the hash using the password (and salt, when applicable).",
										Optional:    true,
									},
									"digest_algorithm": schema.StringAttribute{
										Description: "Algorithm used to generate the key.",
										Optional:    true,
									},
									"iteration_count": schema.Int64Attribute{
										Description: "The number of iterations used when hashing passwords using PBKDF2.",
										Optional:    true,
									},
									"key_size": schema.Int64Attribute{
										Description: "Size of the derived key in bytes.",
										Optional:    true,
									},
									"salt": schema.StringAttribute{
										Description: "Only required for salted hashes.",
										Optional:    true,
									},
									"salt_order": schema.StringAttribute{
										Description: "Specifies whether salt was pre- or postfixed to the password before hashing.",
										Optional:    true,
									},
									"value": schema.StringAttribute{
										Description: "For SHA-512, SHA-256, SHA-1, MD5, and PBKDF2, this is the actual base64-encoded hash of the password (and salt, if used).",
										Optional:    true,
									},
									"work_factor": schema.Int64Attribute{
										Description: "Governs the strength of the hash and the time required to compute it.",
										Optional:    true,
									},
								},
							},
							"hook": schema.SingleNestedBlock{
								Description: "Specify a [password import inline hook](/openapi/okta-management/management/tags/inlinehook/createpasswordimportinlinehook) to trigger verification of the user's password the first time the user signs in.",
								Attributes: map[string]schema.Attribute{
									"type": schema.StringAttribute{
										Description: "The type of password inline hook.",
										Optional:    true,
									},
								},
							},
						},
					},
					"signing": schema.SingleNestedBlock{
						Description: "App signing key properties > **Note:** Only apps with SAML_2_0, SAML_1_1, WS_FEDERATION, or OPENID_CONNECT `signOnMode` support the key rotation feature.",
						Attributes: map[string]schema.Attribute{
							"kid": schema.StringAttribute{
								Description: "Key identifier used for signing assertions > **Note:** Currently, only the X.",
								Optional:    true,
							},
							"last_rotated": schema.StringAttribute{
								Description: "Timestamp when the signing key was last rotated",
								Computed:    true,
							},
							"next_rotation": schema.StringAttribute{
								Description: "The scheduled time for the next signing key rotation",
								Computed:    true,
							},
							"rotation_mode": schema.StringAttribute{
								Description: "The mode of key rotation",
								Optional:    true,
							},
							"use": schema.StringAttribute{
								Description: "Specifies the intended use of the key",
								Optional:    true,
							},
						},
					},
					"user_name_template": schema.SingleNestedBlock{
						Description: "The template used to generate the username when the app is assigned through a group or directly to a user",
						Attributes: map[string]schema.Attribute{
							"push_status": schema.StringAttribute{
								Description: "Determines if the username is pushed to the app on updates for CUSTOM `type`",
								Optional:    true,
							},
							"template": schema.StringAttribute{
								Description: "Mapping expression used to generate usernames.",
								Optional:    true,
							},
							"type": schema.StringAttribute{
								Description: "Type of mapping expression.",
								Optional:    true,
							},
							"user_suffix": schema.StringAttribute{
								Description: "An optional suffix appended to usernames for `BUILT_IN` mapping expressions",
								Optional:    true,
							},
						},
					},
				},
			},
			"licensing": schema.SingleNestedBlock{
				Description: "Licenses for the app",
				Attributes: map[string]schema.Attribute{
					"seat_count": schema.Int64Attribute{
						Description: "Number of licenses purchased for the app",
						Optional:    true,
					},
				},
			},
			"settings": schema.SingleNestedBlock{
				Description: "Settings",
				Attributes: map[string]schema.Attribute{
					"em_opt_in_status": schema.StringAttribute{
						Description: "The entitlement management opt-in status for the app",
						Computed:    true,
					},
					"identity_store_id": schema.StringAttribute{
						Description: "Identifies an additional identity store app, if your app supports it.",
						Optional:    true,
					},
					"implicit_assignment": schema.BoolAttribute{
						Description: "Controls whether Okta automatically assigns users to the app based on the user's role or group membership.",
						Optional:    true,
					},
					"inline_hook_id": schema.StringAttribute{
						Description: "Identifier of an inline hook.",
						Optional:    true,
					},
				},
				Blocks: map[string]schema.Block{
					"app": schema.SingleNestedBlock{
						Description: "App",
						Attributes: map[string]schema.Attribute{
							"optional_field1": schema.StringAttribute{
								Description: "Name of the optional parameter in the sign-in form",
								Optional:    true,
							},
							"optional_field1_value": schema.StringAttribute{
								Description: "Name of the optional value in the sign-in form",
								Optional:    true,
							},
							"optional_field2": schema.StringAttribute{
								Description: "Name of the optional parameter in the sign-in form",
								Optional:    true,
							},
							"optional_field2_value": schema.StringAttribute{
								Description: "Name of the optional value in the sign-in form",
								Optional:    true,
							},
							"optional_field3": schema.StringAttribute{
								Description: "Name of the optional parameter in the sign-in form",
								Optional:    true,
							},
							"optional_field3_value": schema.StringAttribute{
								Description: "Name of the optional value in the sign-in form",
								Optional:    true,
							},
							"password_field": schema.StringAttribute{
								Description: "CSS selector for the **Password** field in the sign-in form",
								Required:    true,
							},
							"url": schema.StringAttribute{
								Description: "The URL of the sign-in page for this app",
								Required:    true,
							},
							"username_field": schema.StringAttribute{
								Description: "CSS selector for the **Username** field in the sign-in form",
								Required:    true,
							},
						},
					},
					"notes": schema.SingleNestedBlock{
						Description: "App notes visible to either the admin or end user",
						Attributes: map[string]schema.Attribute{
							"admin": schema.StringAttribute{
								Description: "An app message that's visible to admins",
								Optional:    true,
							},
							"enduser": schema.StringAttribute{
								Description: "A message that's visible in the End-User Dashboard",
								Optional:    true,
							},
						},
					},
					"notifications": schema.SingleNestedBlock{
						Description: "Specifies notifications settings for the app",
						Blocks: map[string]schema.Block{
							"vpn": schema.SingleNestedBlock{
								Description: "Sends customizable messages with conditions to end users when a VPN connection is required",
								Attributes: map[string]schema.Attribute{
									"help_url": schema.StringAttribute{
										Description: "An optional URL to a help page to assist your end users in signing in to your company VPN",
										Optional:    true,
									},
									"message": schema.StringAttribute{
										Description: "A VPN requirement message that's displayed to users",
										Optional:    true,
									},
								},
								Blocks: map[string]schema.Block{
									"network": schema.SingleNestedBlock{
										Description: "Defines network zones for VPN notification",
										Attributes: map[string]schema.Attribute{
											"connection": schema.StringAttribute{
												Description: "Specifies the VPN connection details required to access the app",
												Optional:    true,
											},
											"exclude": schema.ListAttribute{
												Description: "Defines the IP addresses or network ranges that are excluded from the VPN requirement",
												ElementType: types.StringType,
												Optional:    true,
											},
											"include": schema.ListAttribute{
												Description: "Defines the IP addresses or network ranges that are required to use the VPN",
												ElementType: types.StringType,
												Optional:    true,
											},
										},
									},
								},
							},
						},
					},
				},
			},
			"visibility": schema.SingleNestedBlock{
				Description: "Specifies visibility settings for the app",
				Attributes: map[string]schema.Attribute{
					"app_links": schema.ObjectAttribute{
						Description: "Links or icons that appear on the End-User Dashboard if they're set to `true`.",
						Optional:    true,
					},
					"auto_launch": schema.BoolAttribute{
						Description: "Automatically signs in to the app when user signs into Okta",
						Optional:    true,
					},
					"auto_submit_toolbar": schema.BoolAttribute{
						Description: "Automatically sign in when user lands on the sign-in page",
						Optional:    true,
					},
				},
				Blocks: map[string]schema.Block{
					"hide": schema.SingleNestedBlock{
						Description: "Hides the app for specific end-user apps",
						Attributes: map[string]schema.Attribute{
							"i_os": schema.BoolAttribute{
								Description: "Okta Mobile for iOS or Android (pre-dates Android)",
								Optional:    true,
							},
							"web": schema.BoolAttribute{
								Description: "Okta End-User Dashboard on a web browser",
								Optional:    true,
							},
						},
					},
				},
			},
		},
	}
}
func (r *applicationSecurePasswordStoreResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *applicationSecurePasswordStoreResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state applicationSecurePasswordStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.ApplicationAPI.GetApplication(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading application_secure_password_store", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	variantObj := result.SecurePasswordStoreApplication
	if variantObj == nil {
		resp.Diagnostics.AddError("Error reading application_secure_password_store", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(variantObj.GetCreated().Format(time.RFC3339))
	if m := variantObj.GetExpressConfiguration(); m != nil {
		configJSON, _ := json.Marshal(m)
		state.ExpressConfiguration = types.StringValue(string(configJSON))
	}
	state.Label = types.StringValue(string(variantObj.GetLabel()))
	state.LastUpdated = types.StringValue(variantObj.GetLastUpdated().Format(time.RFC3339))
	state.Name = types.StringValue(string(variantObj.GetName()))
	state.Orn = types.StringValue(string(variantObj.GetOrn()))
	if m := variantObj.GetProfile(); len(m) > 0 {
		profileVals := make(map[string]attr.Value, len(m))
		for k, v := range m {
			profileVals[k] = types.StringValue(fmt.Sprintf("%v", v))
		}
		state.Profile, _ = types.MapValue(types.StringType, profileVals)
	} else {
		state.Profile = types.MapNull(types.StringType)
	}
	state.Status = types.StringValue(string(variantObj.GetStatus()))
	if m := variantObj.GetUniversalLogout(); m != nil {
		configJSON, _ := json.Marshal(m)
		state.UniversalLogout = types.StringValue(string(configJSON))
	}
	state.ID = types.StringValue(string(variantObj.GetId()))
	if accessibilityRaw0, ok := variantObj.GetAccessibilityOk(); ok {
		var accessibilityModel0 *ApplicationSecurePasswordStoreModelAccessibilityModel
		if state.Accessibility == nil {
			accessibilityModel0 = &ApplicationSecurePasswordStoreModelAccessibilityModel{}
		} else {
			accessibilityModel0 = state.Accessibility
		}
		if v := accessibilityRaw0.GetErrorRedirectUrl(); v != "" {
			accessibilityModel0.ErrorRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.ErrorRedirectUrl = types.StringNull()
		}
		if v := accessibilityRaw0.GetLoginRedirectUrl(); v != "" {
			accessibilityModel0.LoginRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.LoginRedirectUrl = types.StringNull()
		}
		accessibilityModel0.SelfService = types.BoolValue(accessibilityRaw0.GetSelfService())
		state.Accessibility = accessibilityModel0
	}
	if credentialsRaw0, ok := variantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ApplicationSecurePasswordStoreModelCredentialsModel
		if state.Credentials == nil {
			credentialsModel0 = &ApplicationSecurePasswordStoreModelCredentialsModel{}
		} else {
			credentialsModel0 = state.Credentials
		}
		if passwordRaw1, ok := credentialsRaw0.GetPasswordOk(); ok {
			var passwordModel1 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel
			if credentialsModel0.Password == nil {
				passwordModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel{}
			} else {
				passwordModel1 = credentialsModel0.Password
			}
			if hashRaw2, ok := passwordRaw1.GetHashOk(); ok {
				var hashModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel
				if passwordModel1.Hash == nil {
					hashModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel{}
				} else {
					hashModel2 = passwordModel1.Hash
				}
				if v := hashRaw2.GetAlgorithm(); v != "" {
					hashModel2.Algorithm = types.StringValue(string(v))
				} else {
					hashModel2.Algorithm = types.StringNull()
				}
				if v := hashRaw2.GetDigestAlgorithm(); v != "" {
					hashModel2.DigestAlgorithm = types.StringValue(string(v))
				} else {
					hashModel2.DigestAlgorithm = types.StringNull()
				}
				hashModel2.IterationCount = types.Int64Value(int64(hashRaw2.GetIterationCount()))
				hashModel2.KeySize = types.Int64Value(int64(hashRaw2.GetKeySize()))
				if v := hashRaw2.GetSalt(); v != "" {
					hashModel2.Salt = types.StringValue(string(v))
				} else {
					hashModel2.Salt = types.StringNull()
				}
				if v := hashRaw2.GetSaltOrder(); v != "" {
					hashModel2.SaltOrder = types.StringValue(string(v))
				} else {
					hashModel2.SaltOrder = types.StringNull()
				}
				if v := hashRaw2.GetValue(); v != "" {
					hashModel2.Value = types.StringValue(string(v))
				} else {
					hashModel2.Value = types.StringNull()
				}
				hashModel2.WorkFactor = types.Int64Value(int64(hashRaw2.GetWorkFactor()))
				passwordModel1.Hash = hashModel2
			}
			if hookRaw2, ok := passwordRaw1.GetHookOk(); ok {
				var hookModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel
				if passwordModel1.Hook == nil {
					hookModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel{}
				} else {
					hookModel2 = passwordModel1.Hook
				}
				if v := hookRaw2.GetType(); v != "" {
					hookModel2.Type = types.StringValue(string(v))
				} else {
					hookModel2.Type = types.StringNull()
				}
				passwordModel1.Hook = hookModel2
			}
			if v := passwordRaw1.GetValue(); v != "" {
				passwordModel1.Value = types.StringValue(string(v))
			} else {
				passwordModel1.Value = types.StringNull()
			}
			credentialsModel0.Password = passwordModel1
		}
		credentialsModel0.RevealPassword = types.BoolValue(credentialsRaw0.GetRevealPassword())
		if v := credentialsRaw0.GetScheme(); v != "" {
			credentialsModel0.Scheme = types.StringValue(string(v))
		} else {
			credentialsModel0.Scheme = types.StringNull()
		}
		if signingRaw1, ok := credentialsRaw0.GetSigningOk(); ok {
			var signingModel1 *ApplicationSecurePasswordStoreModelCredentialsModelSigningModel
			if credentialsModel0.Signing == nil {
				signingModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelSigningModel{}
			} else {
				signingModel1 = credentialsModel0.Signing
			}
			if v := signingRaw1.GetKid(); v != "" {
				signingModel1.Kid = types.StringValue(string(v))
			} else {
				signingModel1.Kid = types.StringNull()
			}
			if t := signingRaw1.GetLastRotated(); !t.IsZero() {
				signingModel1.LastRotated = types.StringValue(t.Format(time.RFC3339))
			}
			if t := signingRaw1.GetNextRotation(); !t.IsZero() {
				signingModel1.NextRotation = types.StringValue(t.Format(time.RFC3339))
			}
			if v := signingRaw1.GetRotationMode(); v != "" {
				signingModel1.RotationMode = types.StringValue(string(v))
			} else {
				signingModel1.RotationMode = types.StringNull()
			}
			if v := signingRaw1.GetUse(); v != "" {
				signingModel1.Use = types.StringValue(string(v))
			} else {
				signingModel1.Use = types.StringNull()
			}
			credentialsModel0.Signing = signingModel1
		}
		if v := credentialsRaw0.GetUserName(); v != "" {
			credentialsModel0.UserName = types.StringValue(string(v))
		} else {
			credentialsModel0.UserName = types.StringNull()
		}
		if userNameTemplateRaw1, ok := credentialsRaw0.GetUserNameTemplateOk(); ok {
			var userNameTemplateModel1 *ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel
			if credentialsModel0.UserNameTemplate == nil {
				userNameTemplateModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel{}
			} else {
				userNameTemplateModel1 = credentialsModel0.UserNameTemplate
			}
			if v := userNameTemplateRaw1.GetPushStatus(); v != "" {
				userNameTemplateModel1.PushStatus = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.PushStatus = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetTemplate(); v != "" {
				userNameTemplateModel1.Template = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Template = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetType(); v != "" {
				userNameTemplateModel1.Type = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Type = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetUserSuffix(); v != "" {
				userNameTemplateModel1.UserSuffix = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.UserSuffix = types.StringNull()
			}
			credentialsModel0.UserNameTemplate = userNameTemplateModel1
		}
		state.Credentials = credentialsModel0
	}
	if licensingRaw0, ok := variantObj.GetLicensingOk(); ok {
		var licensingModel0 *ApplicationSecurePasswordStoreModelLicensingModel
		if state.Licensing == nil {
			licensingModel0 = &ApplicationSecurePasswordStoreModelLicensingModel{}
		} else {
			licensingModel0 = state.Licensing
		}
		licensingModel0.SeatCount = types.Int64Value(int64(licensingRaw0.GetSeatCount()))
		state.Licensing = licensingModel0
	}
	if settingsRaw0, ok := variantObj.GetSettingsOk(); ok {
		var settingsModel0 *ApplicationSecurePasswordStoreModelSettingsModel
		if state.Settings == nil {
			settingsModel0 = &ApplicationSecurePasswordStoreModelSettingsModel{}
		} else {
			settingsModel0 = state.Settings
		}
		if appRaw1, ok := settingsRaw0.GetAppOk(); ok {
			var appModel1 *ApplicationSecurePasswordStoreModelSettingsModelAppModel
			if settingsModel0.App == nil {
				appModel1 = &ApplicationSecurePasswordStoreModelSettingsModelAppModel{}
			} else {
				appModel1 = settingsModel0.App
			}
			if v := appRaw1.GetOptionalField1(); v != "" {
				appModel1.OptionalField1 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField1Value(); v != "" {
				appModel1.OptionalField1Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2(); v != "" {
				appModel1.OptionalField2 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2Value(); v != "" {
				appModel1.OptionalField2Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3(); v != "" {
				appModel1.OptionalField3 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3Value(); v != "" {
				appModel1.OptionalField3Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3Value = types.StringNull()
			}
			appModel1.PasswordField = types.StringValue(string(appRaw1.GetPasswordField()))
			appModel1.Url = types.StringValue(string(appRaw1.GetUrl()))
			appModel1.UsernameField = types.StringValue(string(appRaw1.GetUsernameField()))
			settingsModel0.App = appModel1
		}
		settingsModel0.EmOptInStatus = types.StringValue(string(settingsRaw0.GetEmOptInStatus()))
		if v := settingsRaw0.GetIdentityStoreId(); v != "" {
			settingsModel0.IdentityStoreId = types.StringValue(string(v))
		} else {
			settingsModel0.IdentityStoreId = types.StringNull()
		}
		settingsModel0.ImplicitAssignment = types.BoolValue(settingsRaw0.GetImplicitAssignment())
		if v := settingsRaw0.GetInlineHookId(); v != "" {
			settingsModel0.InlineHookId = types.StringValue(string(v))
		} else {
			settingsModel0.InlineHookId = types.StringNull()
		}
		if notesRaw1, ok := settingsRaw0.GetNotesOk(); ok {
			var notesModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotesModel
			if settingsModel0.Notes == nil {
				notesModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotesModel{}
			} else {
				notesModel1 = settingsModel0.Notes
			}
			if v := notesRaw1.GetAdmin(); v != "" {
				notesModel1.Admin = types.StringValue(string(v))
			} else {
				notesModel1.Admin = types.StringNull()
			}
			if v := notesRaw1.GetEnduser(); v != "" {
				notesModel1.Enduser = types.StringValue(string(v))
			} else {
				notesModel1.Enduser = types.StringNull()
			}
			settingsModel0.Notes = notesModel1
		}
		if notificationsRaw1, ok := settingsRaw0.GetNotificationsOk(); ok {
			var notificationsModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel
			if settingsModel0.Notifications == nil {
				notificationsModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel{}
			} else {
				notificationsModel1 = settingsModel0.Notifications
			}
			if vpnRaw2, ok := notificationsRaw1.GetVpnOk(); ok {
				var vpnModel2 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel
				if notificationsModel1.Vpn == nil {
					vpnModel2 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel{}
				} else {
					vpnModel2 = notificationsModel1.Vpn
				}
				if v := vpnRaw2.GetHelpUrl(); v != "" {
					vpnModel2.HelpUrl = types.StringValue(string(v))
				} else {
					vpnModel2.HelpUrl = types.StringNull()
				}
				if v := vpnRaw2.GetMessage(); v != "" {
					vpnModel2.Message = types.StringValue(string(v))
				} else {
					vpnModel2.Message = types.StringNull()
				}
				if networkRaw3, ok := vpnRaw2.GetNetworkOk(); ok {
					var networkModel3 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel
					if vpnModel2.Network == nil {
						networkModel3 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel{}
					} else {
						networkModel3 = vpnModel2.Network
					}
					if v := networkRaw3.GetConnection(); v != "" {
						networkModel3.Connection = types.StringValue(string(v))
					} else {
						networkModel3.Connection = types.StringNull()
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetExclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Exclude = listVal
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetInclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Include = listVal
					}
					vpnModel2.Network = networkModel3
				}
				notificationsModel1.Vpn = vpnModel2
			}
			settingsModel0.Notifications = notificationsModel1
		}
		state.Settings = settingsModel0
	}
	if visibilityRaw0, ok := variantObj.GetVisibilityOk(); ok {
		var visibilityModel0 *ApplicationSecurePasswordStoreModelVisibilityModel
		if state.Visibility == nil {
			visibilityModel0 = &ApplicationSecurePasswordStoreModelVisibilityModel{}
		} else {
			visibilityModel0 = state.Visibility
		}
		visibilityModel0.AutoLaunch = types.BoolValue(visibilityRaw0.GetAutoLaunch())
		visibilityModel0.AutoSubmitToolbar = types.BoolValue(visibilityRaw0.GetAutoSubmitToolbar())
		if hideRaw1, ok := visibilityRaw0.GetHideOk(); ok {
			var hideModel1 *ApplicationSecurePasswordStoreModelVisibilityModelHideModel
			if visibilityModel0.Hide == nil {
				hideModel1 = &ApplicationSecurePasswordStoreModelVisibilityModelHideModel{}
			} else {
				hideModel1 = visibilityModel0.Hide
			}
			hideModel1.IOS = types.BoolValue(hideRaw1.GetIOS())
			hideModel1.Web = types.BoolValue(hideRaw1.GetWeb())
			visibilityModel0.Hide = hideModel1
		}
		state.Visibility = visibilityModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *applicationSecurePasswordStoreResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan applicationSecurePasswordStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.ApplicationAPI.CreateApplication(ctx)
	body := okta.NewSecurePasswordStoreApplicationWithDefaults()
	if plan.Accessibility != nil {
		nestedAccessibility := okta.NewApplicationAccessibilityWithDefaults()
		if !plan.Accessibility.ErrorRedirectUrl.IsNull() && !plan.Accessibility.ErrorRedirectUrl.IsUnknown() {
			nestedAccessibility.SetErrorRedirectUrl(plan.Accessibility.ErrorRedirectUrl.ValueString())
		}
		if !plan.Accessibility.LoginRedirectUrl.IsNull() && !plan.Accessibility.LoginRedirectUrl.IsUnknown() {
			nestedAccessibility.SetLoginRedirectUrl(plan.Accessibility.LoginRedirectUrl.ValueString())
		}
		if !plan.Accessibility.SelfService.IsNull() && !plan.Accessibility.SelfService.IsUnknown() {
			nestedAccessibility.SetSelfService(plan.Accessibility.SelfService.ValueBool())
		}
		body.SetAccessibility(*nestedAccessibility)
	}
	if plan.Credentials != nil {
		nestedCredentials := okta.NewSchemeApplicationCredentialsWithDefaults()
		if !plan.Credentials.RevealPassword.IsNull() && !plan.Credentials.RevealPassword.IsUnknown() {
			nestedCredentials.SetRevealPassword(plan.Credentials.RevealPassword.ValueBool())
		}
		if !plan.Credentials.Scheme.IsNull() && !plan.Credentials.Scheme.IsUnknown() {
			nestedCredentials.SetScheme(plan.Credentials.Scheme.ValueString())
		}
		if !plan.Credentials.UserName.IsNull() && !plan.Credentials.UserName.IsUnknown() {
			nestedCredentials.SetUserName(plan.Credentials.UserName.ValueString())
		}
		body.SetCredentials(*nestedCredentials)
	}
	body.SetLabel(plan.Label.ValueString())
	if plan.Licensing != nil {
		nestedLicensing := okta.NewApplicationLicensingWithDefaults()
		if !plan.Licensing.SeatCount.IsNull() && !plan.Licensing.SeatCount.IsUnknown() {
			nestedLicensing.SetSeatCount(int32(plan.Licensing.SeatCount.ValueInt64()))
		}
		body.SetLicensing(*nestedLicensing)
	}
	body.SetName(plan.Name.ValueString())
	if plan.Settings != nil {
		nestedSettings := okta.NewSecurePasswordStoreApplicationSettingsWithDefaults()
		if !plan.Settings.EmOptInStatus.IsNull() && !plan.Settings.EmOptInStatus.IsUnknown() {
			nestedSettings.SetEmOptInStatus(plan.Settings.EmOptInStatus.ValueString())
		}
		if !plan.Settings.IdentityStoreId.IsNull() && !plan.Settings.IdentityStoreId.IsUnknown() {
			nestedSettings.SetIdentityStoreId(plan.Settings.IdentityStoreId.ValueString())
		}
		if !plan.Settings.ImplicitAssignment.IsNull() && !plan.Settings.ImplicitAssignment.IsUnknown() {
			nestedSettings.SetImplicitAssignment(plan.Settings.ImplicitAssignment.ValueBool())
		}
		if !plan.Settings.InlineHookId.IsNull() && !plan.Settings.InlineHookId.IsUnknown() {
			nestedSettings.SetInlineHookId(plan.Settings.InlineHookId.ValueString())
		}
		body.SetSettings(*nestedSettings)
	}
	if plan.Visibility != nil {
		nestedVisibility := okta.NewApplicationVisibilityWithDefaults()
		if !plan.Visibility.AutoLaunch.IsNull() && !plan.Visibility.AutoLaunch.IsUnknown() {
			nestedVisibility.SetAutoLaunch(plan.Visibility.AutoLaunch.ValueBool())
		}
		if !plan.Visibility.AutoSubmitToolbar.IsNull() && !plan.Visibility.AutoSubmitToolbar.IsUnknown() {
			nestedVisibility.SetAutoSubmitToolbar(plan.Visibility.AutoSubmitToolbar.ValueBool())
		}
		body.SetVisibility(*nestedVisibility)
	}
	createReq = createReq.Application(okta.SecurePasswordStoreApplicationAsListApplications200ResponseInner(body))
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating application_secure_password_store", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	createVariantObj := result.SecurePasswordStoreApplication
	if createVariantObj == nil {
		resp.Diagnostics.AddError("Error creating application_secure_password_store", "API returned a response for a different variant type")
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(createVariantObj.GetId()))

	// Map computed fields from response back to plan (scalar types only)
	plan.Created = types.StringValue(createVariantObj.GetCreated().Format(time.RFC3339))
	plan.ExpressConfiguration = types.StringValue(string(createVariantObj.GetExpressConfiguration()))
	plan.LastUpdated = types.StringValue(createVariantObj.GetLastUpdated().Format(time.RFC3339))
	plan.Orn = types.StringValue(string(createVariantObj.GetOrn()))
	plan.Status = types.StringValue(string(createVariantObj.GetStatus()))
	plan.UniversalLogout = types.StringValue(string(createVariantObj.GetUniversalLogout()))
	if accessibilityRaw0, ok := createVariantObj.GetAccessibilityOk(); ok {
		var accessibilityModel0 *ApplicationSecurePasswordStoreModelAccessibilityModel
		if plan.Accessibility == nil {
			accessibilityModel0 = &ApplicationSecurePasswordStoreModelAccessibilityModel{}
		} else {
			accessibilityModel0 = plan.Accessibility
		}
		if v := accessibilityRaw0.GetErrorRedirectUrl(); v != "" {
			accessibilityModel0.ErrorRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.ErrorRedirectUrl = types.StringNull()
		}
		if v := accessibilityRaw0.GetLoginRedirectUrl(); v != "" {
			accessibilityModel0.LoginRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.LoginRedirectUrl = types.StringNull()
		}
		accessibilityModel0.SelfService = types.BoolValue(accessibilityRaw0.GetSelfService())
		plan.Accessibility = accessibilityModel0
	}
	if credentialsRaw0, ok := createVariantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ApplicationSecurePasswordStoreModelCredentialsModel
		if plan.Credentials == nil {
			credentialsModel0 = &ApplicationSecurePasswordStoreModelCredentialsModel{}
		} else {
			credentialsModel0 = plan.Credentials
		}
		if passwordRaw1, ok := credentialsRaw0.GetPasswordOk(); ok {
			var passwordModel1 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel
			if credentialsModel0.Password == nil {
				passwordModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel{}
			} else {
				passwordModel1 = credentialsModel0.Password
			}
			if hashRaw2, ok := passwordRaw1.GetHashOk(); ok {
				var hashModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel
				if passwordModel1.Hash == nil {
					hashModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel{}
				} else {
					hashModel2 = passwordModel1.Hash
				}
				if v := hashRaw2.GetAlgorithm(); v != "" {
					hashModel2.Algorithm = types.StringValue(string(v))
				} else {
					hashModel2.Algorithm = types.StringNull()
				}
				if v := hashRaw2.GetDigestAlgorithm(); v != "" {
					hashModel2.DigestAlgorithm = types.StringValue(string(v))
				} else {
					hashModel2.DigestAlgorithm = types.StringNull()
				}
				hashModel2.IterationCount = types.Int64Value(int64(hashRaw2.GetIterationCount()))
				hashModel2.KeySize = types.Int64Value(int64(hashRaw2.GetKeySize()))
				if v := hashRaw2.GetSalt(); v != "" {
					hashModel2.Salt = types.StringValue(string(v))
				} else {
					hashModel2.Salt = types.StringNull()
				}
				if v := hashRaw2.GetSaltOrder(); v != "" {
					hashModel2.SaltOrder = types.StringValue(string(v))
				} else {
					hashModel2.SaltOrder = types.StringNull()
				}
				if v := hashRaw2.GetValue(); v != "" {
					hashModel2.Value = types.StringValue(string(v))
				} else {
					hashModel2.Value = types.StringNull()
				}
				hashModel2.WorkFactor = types.Int64Value(int64(hashRaw2.GetWorkFactor()))
				passwordModel1.Hash = hashModel2
			}
			if hookRaw2, ok := passwordRaw1.GetHookOk(); ok {
				var hookModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel
				if passwordModel1.Hook == nil {
					hookModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel{}
				} else {
					hookModel2 = passwordModel1.Hook
				}
				if v := hookRaw2.GetType(); v != "" {
					hookModel2.Type = types.StringValue(string(v))
				} else {
					hookModel2.Type = types.StringNull()
				}
				passwordModel1.Hook = hookModel2
			}
			if v := passwordRaw1.GetValue(); v != "" {
				passwordModel1.Value = types.StringValue(string(v))
			} else {
				passwordModel1.Value = types.StringNull()
			}
			credentialsModel0.Password = passwordModel1
		}
		credentialsModel0.RevealPassword = types.BoolValue(credentialsRaw0.GetRevealPassword())
		if v := credentialsRaw0.GetScheme(); v != "" {
			credentialsModel0.Scheme = types.StringValue(string(v))
		} else {
			credentialsModel0.Scheme = types.StringNull()
		}
		if signingRaw1, ok := credentialsRaw0.GetSigningOk(); ok {
			var signingModel1 *ApplicationSecurePasswordStoreModelCredentialsModelSigningModel
			if credentialsModel0.Signing == nil {
				signingModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelSigningModel{}
			} else {
				signingModel1 = credentialsModel0.Signing
			}
			if v := signingRaw1.GetKid(); v != "" {
				signingModel1.Kid = types.StringValue(string(v))
			} else {
				signingModel1.Kid = types.StringNull()
			}
			if t := signingRaw1.GetLastRotated(); !t.IsZero() {
				signingModel1.LastRotated = types.StringValue(t.Format(time.RFC3339))
			}
			if t := signingRaw1.GetNextRotation(); !t.IsZero() {
				signingModel1.NextRotation = types.StringValue(t.Format(time.RFC3339))
			}
			if v := signingRaw1.GetRotationMode(); v != "" {
				signingModel1.RotationMode = types.StringValue(string(v))
			} else {
				signingModel1.RotationMode = types.StringNull()
			}
			if v := signingRaw1.GetUse(); v != "" {
				signingModel1.Use = types.StringValue(string(v))
			} else {
				signingModel1.Use = types.StringNull()
			}
			credentialsModel0.Signing = signingModel1
		}
		if v := credentialsRaw0.GetUserName(); v != "" {
			credentialsModel0.UserName = types.StringValue(string(v))
		} else {
			credentialsModel0.UserName = types.StringNull()
		}
		if userNameTemplateRaw1, ok := credentialsRaw0.GetUserNameTemplateOk(); ok {
			var userNameTemplateModel1 *ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel
			if credentialsModel0.UserNameTemplate == nil {
				userNameTemplateModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel{}
			} else {
				userNameTemplateModel1 = credentialsModel0.UserNameTemplate
			}
			if v := userNameTemplateRaw1.GetPushStatus(); v != "" {
				userNameTemplateModel1.PushStatus = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.PushStatus = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetTemplate(); v != "" {
				userNameTemplateModel1.Template = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Template = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetType(); v != "" {
				userNameTemplateModel1.Type = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Type = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetUserSuffix(); v != "" {
				userNameTemplateModel1.UserSuffix = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.UserSuffix = types.StringNull()
			}
			credentialsModel0.UserNameTemplate = userNameTemplateModel1
		}
		plan.Credentials = credentialsModel0
	}
	if licensingRaw0, ok := createVariantObj.GetLicensingOk(); ok {
		var licensingModel0 *ApplicationSecurePasswordStoreModelLicensingModel
		if plan.Licensing == nil {
			licensingModel0 = &ApplicationSecurePasswordStoreModelLicensingModel{}
		} else {
			licensingModel0 = plan.Licensing
		}
		licensingModel0.SeatCount = types.Int64Value(int64(licensingRaw0.GetSeatCount()))
		plan.Licensing = licensingModel0
	}
	if settingsRaw0, ok := createVariantObj.GetSettingsOk(); ok {
		var settingsModel0 *ApplicationSecurePasswordStoreModelSettingsModel
		if plan.Settings == nil {
			settingsModel0 = &ApplicationSecurePasswordStoreModelSettingsModel{}
		} else {
			settingsModel0 = plan.Settings
		}
		if appRaw1, ok := settingsRaw0.GetAppOk(); ok {
			var appModel1 *ApplicationSecurePasswordStoreModelSettingsModelAppModel
			if settingsModel0.App == nil {
				appModel1 = &ApplicationSecurePasswordStoreModelSettingsModelAppModel{}
			} else {
				appModel1 = settingsModel0.App
			}
			if v := appRaw1.GetOptionalField1(); v != "" {
				appModel1.OptionalField1 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField1Value(); v != "" {
				appModel1.OptionalField1Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2(); v != "" {
				appModel1.OptionalField2 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2Value(); v != "" {
				appModel1.OptionalField2Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3(); v != "" {
				appModel1.OptionalField3 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3Value(); v != "" {
				appModel1.OptionalField3Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3Value = types.StringNull()
			}
			appModel1.PasswordField = types.StringValue(string(appRaw1.GetPasswordField()))
			appModel1.Url = types.StringValue(string(appRaw1.GetUrl()))
			appModel1.UsernameField = types.StringValue(string(appRaw1.GetUsernameField()))
			settingsModel0.App = appModel1
		}
		settingsModel0.EmOptInStatus = types.StringValue(string(settingsRaw0.GetEmOptInStatus()))
		if v := settingsRaw0.GetIdentityStoreId(); v != "" {
			settingsModel0.IdentityStoreId = types.StringValue(string(v))
		} else {
			settingsModel0.IdentityStoreId = types.StringNull()
		}
		settingsModel0.ImplicitAssignment = types.BoolValue(settingsRaw0.GetImplicitAssignment())
		if v := settingsRaw0.GetInlineHookId(); v != "" {
			settingsModel0.InlineHookId = types.StringValue(string(v))
		} else {
			settingsModel0.InlineHookId = types.StringNull()
		}
		if notesRaw1, ok := settingsRaw0.GetNotesOk(); ok {
			var notesModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotesModel
			if settingsModel0.Notes == nil {
				notesModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotesModel{}
			} else {
				notesModel1 = settingsModel0.Notes
			}
			if v := notesRaw1.GetAdmin(); v != "" {
				notesModel1.Admin = types.StringValue(string(v))
			} else {
				notesModel1.Admin = types.StringNull()
			}
			if v := notesRaw1.GetEnduser(); v != "" {
				notesModel1.Enduser = types.StringValue(string(v))
			} else {
				notesModel1.Enduser = types.StringNull()
			}
			settingsModel0.Notes = notesModel1
		}
		if notificationsRaw1, ok := settingsRaw0.GetNotificationsOk(); ok {
			var notificationsModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel
			if settingsModel0.Notifications == nil {
				notificationsModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel{}
			} else {
				notificationsModel1 = settingsModel0.Notifications
			}
			if vpnRaw2, ok := notificationsRaw1.GetVpnOk(); ok {
				var vpnModel2 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel
				if notificationsModel1.Vpn == nil {
					vpnModel2 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel{}
				} else {
					vpnModel2 = notificationsModel1.Vpn
				}
				if v := vpnRaw2.GetHelpUrl(); v != "" {
					vpnModel2.HelpUrl = types.StringValue(string(v))
				} else {
					vpnModel2.HelpUrl = types.StringNull()
				}
				if v := vpnRaw2.GetMessage(); v != "" {
					vpnModel2.Message = types.StringValue(string(v))
				} else {
					vpnModel2.Message = types.StringNull()
				}
				if networkRaw3, ok := vpnRaw2.GetNetworkOk(); ok {
					var networkModel3 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel
					if vpnModel2.Network == nil {
						networkModel3 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel{}
					} else {
						networkModel3 = vpnModel2.Network
					}
					if v := networkRaw3.GetConnection(); v != "" {
						networkModel3.Connection = types.StringValue(string(v))
					} else {
						networkModel3.Connection = types.StringNull()
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetExclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Exclude = listVal
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetInclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Include = listVal
					}
					vpnModel2.Network = networkModel3
				}
				notificationsModel1.Vpn = vpnModel2
			}
			settingsModel0.Notifications = notificationsModel1
		}
		plan.Settings = settingsModel0
	}
	if visibilityRaw0, ok := createVariantObj.GetVisibilityOk(); ok {
		var visibilityModel0 *ApplicationSecurePasswordStoreModelVisibilityModel
		if plan.Visibility == nil {
			visibilityModel0 = &ApplicationSecurePasswordStoreModelVisibilityModel{}
		} else {
			visibilityModel0 = plan.Visibility
		}
		visibilityModel0.AutoLaunch = types.BoolValue(visibilityRaw0.GetAutoLaunch())
		visibilityModel0.AutoSubmitToolbar = types.BoolValue(visibilityRaw0.GetAutoSubmitToolbar())
		if hideRaw1, ok := visibilityRaw0.GetHideOk(); ok {
			var hideModel1 *ApplicationSecurePasswordStoreModelVisibilityModelHideModel
			if visibilityModel0.Hide == nil {
				hideModel1 = &ApplicationSecurePasswordStoreModelVisibilityModelHideModel{}
			} else {
				hideModel1 = visibilityModel0.Hide
			}
			hideModel1.IOS = types.BoolValue(hideRaw1.GetIOS())
			hideModel1.Web = types.BoolValue(hideRaw1.GetWeb())
			visibilityModel0.Hide = hideModel1
		}
		plan.Visibility = visibilityModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *applicationSecurePasswordStoreResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan applicationSecurePasswordStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state applicationSecurePasswordStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.ApplicationAPI.ReplaceApplication(ctx, id)
	updateBody := okta.NewSecurePasswordStoreApplicationWithDefaults()
	if plan.Accessibility != nil {
		nestedAccessibility := okta.NewApplicationAccessibilityWithDefaults()
		if !plan.Accessibility.ErrorRedirectUrl.IsNull() && !plan.Accessibility.ErrorRedirectUrl.IsUnknown() {
			nestedAccessibility.SetErrorRedirectUrl(plan.Accessibility.ErrorRedirectUrl.ValueString())
		}
		if !plan.Accessibility.LoginRedirectUrl.IsNull() && !plan.Accessibility.LoginRedirectUrl.IsUnknown() {
			nestedAccessibility.SetLoginRedirectUrl(plan.Accessibility.LoginRedirectUrl.ValueString())
		}
		if !plan.Accessibility.SelfService.IsNull() && !plan.Accessibility.SelfService.IsUnknown() {
			nestedAccessibility.SetSelfService(plan.Accessibility.SelfService.ValueBool())
		}
		updateBody.SetAccessibility(*nestedAccessibility)
	}
	if plan.Credentials != nil {
		nestedCredentials := okta.NewSchemeApplicationCredentialsWithDefaults()
		if !plan.Credentials.RevealPassword.IsNull() && !plan.Credentials.RevealPassword.IsUnknown() {
			nestedCredentials.SetRevealPassword(plan.Credentials.RevealPassword.ValueBool())
		}
		if !plan.Credentials.Scheme.IsNull() && !plan.Credentials.Scheme.IsUnknown() {
			nestedCredentials.SetScheme(plan.Credentials.Scheme.ValueString())
		}
		if !plan.Credentials.UserName.IsNull() && !plan.Credentials.UserName.IsUnknown() {
			nestedCredentials.SetUserName(plan.Credentials.UserName.ValueString())
		}
		updateBody.SetCredentials(*nestedCredentials)
	}
	updateBody.SetLabel(plan.Label.ValueString())
	if plan.Licensing != nil {
		nestedLicensing := okta.NewApplicationLicensingWithDefaults()
		if !plan.Licensing.SeatCount.IsNull() && !plan.Licensing.SeatCount.IsUnknown() {
			nestedLicensing.SetSeatCount(int32(plan.Licensing.SeatCount.ValueInt64()))
		}
		updateBody.SetLicensing(*nestedLicensing)
	}
	updateBody.SetName(plan.Name.ValueString())
	if plan.Settings != nil {
		nestedSettings := okta.NewSecurePasswordStoreApplicationSettingsWithDefaults()
		if !plan.Settings.EmOptInStatus.IsNull() && !plan.Settings.EmOptInStatus.IsUnknown() {
			nestedSettings.SetEmOptInStatus(plan.Settings.EmOptInStatus.ValueString())
		}
		if !plan.Settings.IdentityStoreId.IsNull() && !plan.Settings.IdentityStoreId.IsUnknown() {
			nestedSettings.SetIdentityStoreId(plan.Settings.IdentityStoreId.ValueString())
		}
		if !plan.Settings.ImplicitAssignment.IsNull() && !plan.Settings.ImplicitAssignment.IsUnknown() {
			nestedSettings.SetImplicitAssignment(plan.Settings.ImplicitAssignment.ValueBool())
		}
		if !plan.Settings.InlineHookId.IsNull() && !plan.Settings.InlineHookId.IsUnknown() {
			nestedSettings.SetInlineHookId(plan.Settings.InlineHookId.ValueString())
		}
		updateBody.SetSettings(*nestedSettings)
	}
	if plan.Visibility != nil {
		nestedVisibility := okta.NewApplicationVisibilityWithDefaults()
		if !plan.Visibility.AutoLaunch.IsNull() && !plan.Visibility.AutoLaunch.IsUnknown() {
			nestedVisibility.SetAutoLaunch(plan.Visibility.AutoLaunch.ValueBool())
		}
		if !plan.Visibility.AutoSubmitToolbar.IsNull() && !plan.Visibility.AutoSubmitToolbar.IsUnknown() {
			nestedVisibility.SetAutoSubmitToolbar(plan.Visibility.AutoSubmitToolbar.ValueBool())
		}
		updateBody.SetVisibility(*nestedVisibility)
	}
	updateReq = updateReq.Application(okta.SecurePasswordStoreApplicationAsListApplications200ResponseInner(updateBody))
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating application_secure_password_store", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	updateVariantObj := result.SecurePasswordStoreApplication
	if updateVariantObj == nil {
		resp.Diagnostics.AddError("Error updating application_secure_password_store", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only)
	state.ID = types.StringValue(string(updateVariantObj.GetId()))
	state.Created = types.StringValue(updateVariantObj.GetCreated().Format(time.RFC3339))
	state.ExpressConfiguration = types.StringValue(string(updateVariantObj.GetExpressConfiguration()))
	state.Label = types.StringValue(string(updateVariantObj.GetLabel()))
	state.LastUpdated = types.StringValue(updateVariantObj.GetLastUpdated().Format(time.RFC3339))
	state.Name = types.StringValue(string(updateVariantObj.GetName()))
	state.Orn = types.StringValue(string(updateVariantObj.GetOrn()))
	if m := updateVariantObj.GetProfile(); len(m) > 0 {
		profileVals := make(map[string]attr.Value, len(m))
		for k, v := range m {
			profileVals[k] = types.StringValue(fmt.Sprintf("%v", v))
		}
		state.Profile, _ = types.MapValue(types.StringType, profileVals)
	} else {
		state.Profile = types.MapNull(types.StringType)
	}
	state.Status = types.StringValue(string(updateVariantObj.GetStatus()))
	state.UniversalLogout = types.StringValue(string(updateVariantObj.GetUniversalLogout()))
	if accessibilityRaw0, ok := updateVariantObj.GetAccessibilityOk(); ok {
		var accessibilityModel0 *ApplicationSecurePasswordStoreModelAccessibilityModel
		if state.Accessibility == nil {
			accessibilityModel0 = &ApplicationSecurePasswordStoreModelAccessibilityModel{}
		} else {
			accessibilityModel0 = state.Accessibility
		}
		if v := accessibilityRaw0.GetErrorRedirectUrl(); v != "" {
			accessibilityModel0.ErrorRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.ErrorRedirectUrl = types.StringNull()
		}
		if v := accessibilityRaw0.GetLoginRedirectUrl(); v != "" {
			accessibilityModel0.LoginRedirectUrl = types.StringValue(string(v))
		} else {
			accessibilityModel0.LoginRedirectUrl = types.StringNull()
		}
		accessibilityModel0.SelfService = types.BoolValue(accessibilityRaw0.GetSelfService())
		state.Accessibility = accessibilityModel0
	}
	if credentialsRaw0, ok := updateVariantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ApplicationSecurePasswordStoreModelCredentialsModel
		if state.Credentials == nil {
			credentialsModel0 = &ApplicationSecurePasswordStoreModelCredentialsModel{}
		} else {
			credentialsModel0 = state.Credentials
		}
		if passwordRaw1, ok := credentialsRaw0.GetPasswordOk(); ok {
			var passwordModel1 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel
			if credentialsModel0.Password == nil {
				passwordModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModel{}
			} else {
				passwordModel1 = credentialsModel0.Password
			}
			if hashRaw2, ok := passwordRaw1.GetHashOk(); ok {
				var hashModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel
				if passwordModel1.Hash == nil {
					hashModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHashModel{}
				} else {
					hashModel2 = passwordModel1.Hash
				}
				if v := hashRaw2.GetAlgorithm(); v != "" {
					hashModel2.Algorithm = types.StringValue(string(v))
				} else {
					hashModel2.Algorithm = types.StringNull()
				}
				if v := hashRaw2.GetDigestAlgorithm(); v != "" {
					hashModel2.DigestAlgorithm = types.StringValue(string(v))
				} else {
					hashModel2.DigestAlgorithm = types.StringNull()
				}
				hashModel2.IterationCount = types.Int64Value(int64(hashRaw2.GetIterationCount()))
				hashModel2.KeySize = types.Int64Value(int64(hashRaw2.GetKeySize()))
				if v := hashRaw2.GetSalt(); v != "" {
					hashModel2.Salt = types.StringValue(string(v))
				} else {
					hashModel2.Salt = types.StringNull()
				}
				if v := hashRaw2.GetSaltOrder(); v != "" {
					hashModel2.SaltOrder = types.StringValue(string(v))
				} else {
					hashModel2.SaltOrder = types.StringNull()
				}
				if v := hashRaw2.GetValue(); v != "" {
					hashModel2.Value = types.StringValue(string(v))
				} else {
					hashModel2.Value = types.StringNull()
				}
				hashModel2.WorkFactor = types.Int64Value(int64(hashRaw2.GetWorkFactor()))
				passwordModel1.Hash = hashModel2
			}
			if hookRaw2, ok := passwordRaw1.GetHookOk(); ok {
				var hookModel2 *ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel
				if passwordModel1.Hook == nil {
					hookModel2 = &ApplicationSecurePasswordStoreModelCredentialsModelPasswordModelHookModel{}
				} else {
					hookModel2 = passwordModel1.Hook
				}
				if v := hookRaw2.GetType(); v != "" {
					hookModel2.Type = types.StringValue(string(v))
				} else {
					hookModel2.Type = types.StringNull()
				}
				passwordModel1.Hook = hookModel2
			}
			if v := passwordRaw1.GetValue(); v != "" {
				passwordModel1.Value = types.StringValue(string(v))
			} else {
				passwordModel1.Value = types.StringNull()
			}
			credentialsModel0.Password = passwordModel1
		}
		credentialsModel0.RevealPassword = types.BoolValue(credentialsRaw0.GetRevealPassword())
		if v := credentialsRaw0.GetScheme(); v != "" {
			credentialsModel0.Scheme = types.StringValue(string(v))
		} else {
			credentialsModel0.Scheme = types.StringNull()
		}
		if signingRaw1, ok := credentialsRaw0.GetSigningOk(); ok {
			var signingModel1 *ApplicationSecurePasswordStoreModelCredentialsModelSigningModel
			if credentialsModel0.Signing == nil {
				signingModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelSigningModel{}
			} else {
				signingModel1 = credentialsModel0.Signing
			}
			if v := signingRaw1.GetKid(); v != "" {
				signingModel1.Kid = types.StringValue(string(v))
			} else {
				signingModel1.Kid = types.StringNull()
			}
			if t := signingRaw1.GetLastRotated(); !t.IsZero() {
				signingModel1.LastRotated = types.StringValue(t.Format(time.RFC3339))
			}
			if t := signingRaw1.GetNextRotation(); !t.IsZero() {
				signingModel1.NextRotation = types.StringValue(t.Format(time.RFC3339))
			}
			if v := signingRaw1.GetRotationMode(); v != "" {
				signingModel1.RotationMode = types.StringValue(string(v))
			} else {
				signingModel1.RotationMode = types.StringNull()
			}
			if v := signingRaw1.GetUse(); v != "" {
				signingModel1.Use = types.StringValue(string(v))
			} else {
				signingModel1.Use = types.StringNull()
			}
			credentialsModel0.Signing = signingModel1
		}
		if v := credentialsRaw0.GetUserName(); v != "" {
			credentialsModel0.UserName = types.StringValue(string(v))
		} else {
			credentialsModel0.UserName = types.StringNull()
		}
		if userNameTemplateRaw1, ok := credentialsRaw0.GetUserNameTemplateOk(); ok {
			var userNameTemplateModel1 *ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel
			if credentialsModel0.UserNameTemplate == nil {
				userNameTemplateModel1 = &ApplicationSecurePasswordStoreModelCredentialsModelUserNameTemplateModel{}
			} else {
				userNameTemplateModel1 = credentialsModel0.UserNameTemplate
			}
			if v := userNameTemplateRaw1.GetPushStatus(); v != "" {
				userNameTemplateModel1.PushStatus = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.PushStatus = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetTemplate(); v != "" {
				userNameTemplateModel1.Template = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Template = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetType(); v != "" {
				userNameTemplateModel1.Type = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.Type = types.StringNull()
			}
			if v := userNameTemplateRaw1.GetUserSuffix(); v != "" {
				userNameTemplateModel1.UserSuffix = types.StringValue(string(v))
			} else {
				userNameTemplateModel1.UserSuffix = types.StringNull()
			}
			credentialsModel0.UserNameTemplate = userNameTemplateModel1
		}
		state.Credentials = credentialsModel0
	}
	if licensingRaw0, ok := updateVariantObj.GetLicensingOk(); ok {
		var licensingModel0 *ApplicationSecurePasswordStoreModelLicensingModel
		if state.Licensing == nil {
			licensingModel0 = &ApplicationSecurePasswordStoreModelLicensingModel{}
		} else {
			licensingModel0 = state.Licensing
		}
		licensingModel0.SeatCount = types.Int64Value(int64(licensingRaw0.GetSeatCount()))
		state.Licensing = licensingModel0
	}
	if settingsRaw0, ok := updateVariantObj.GetSettingsOk(); ok {
		var settingsModel0 *ApplicationSecurePasswordStoreModelSettingsModel
		if state.Settings == nil {
			settingsModel0 = &ApplicationSecurePasswordStoreModelSettingsModel{}
		} else {
			settingsModel0 = state.Settings
		}
		if appRaw1, ok := settingsRaw0.GetAppOk(); ok {
			var appModel1 *ApplicationSecurePasswordStoreModelSettingsModelAppModel
			if settingsModel0.App == nil {
				appModel1 = &ApplicationSecurePasswordStoreModelSettingsModelAppModel{}
			} else {
				appModel1 = settingsModel0.App
			}
			if v := appRaw1.GetOptionalField1(); v != "" {
				appModel1.OptionalField1 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField1Value(); v != "" {
				appModel1.OptionalField1Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField1Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2(); v != "" {
				appModel1.OptionalField2 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField2Value(); v != "" {
				appModel1.OptionalField2Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField2Value = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3(); v != "" {
				appModel1.OptionalField3 = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3 = types.StringNull()
			}
			if v := appRaw1.GetOptionalField3Value(); v != "" {
				appModel1.OptionalField3Value = types.StringValue(string(v))
			} else {
				appModel1.OptionalField3Value = types.StringNull()
			}
			appModel1.PasswordField = types.StringValue(string(appRaw1.GetPasswordField()))
			appModel1.Url = types.StringValue(string(appRaw1.GetUrl()))
			appModel1.UsernameField = types.StringValue(string(appRaw1.GetUsernameField()))
			settingsModel0.App = appModel1
		}
		settingsModel0.EmOptInStatus = types.StringValue(string(settingsRaw0.GetEmOptInStatus()))
		if v := settingsRaw0.GetIdentityStoreId(); v != "" {
			settingsModel0.IdentityStoreId = types.StringValue(string(v))
		} else {
			settingsModel0.IdentityStoreId = types.StringNull()
		}
		settingsModel0.ImplicitAssignment = types.BoolValue(settingsRaw0.GetImplicitAssignment())
		if v := settingsRaw0.GetInlineHookId(); v != "" {
			settingsModel0.InlineHookId = types.StringValue(string(v))
		} else {
			settingsModel0.InlineHookId = types.StringNull()
		}
		if notesRaw1, ok := settingsRaw0.GetNotesOk(); ok {
			var notesModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotesModel
			if settingsModel0.Notes == nil {
				notesModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotesModel{}
			} else {
				notesModel1 = settingsModel0.Notes
			}
			if v := notesRaw1.GetAdmin(); v != "" {
				notesModel1.Admin = types.StringValue(string(v))
			} else {
				notesModel1.Admin = types.StringNull()
			}
			if v := notesRaw1.GetEnduser(); v != "" {
				notesModel1.Enduser = types.StringValue(string(v))
			} else {
				notesModel1.Enduser = types.StringNull()
			}
			settingsModel0.Notes = notesModel1
		}
		if notificationsRaw1, ok := settingsRaw0.GetNotificationsOk(); ok {
			var notificationsModel1 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel
			if settingsModel0.Notifications == nil {
				notificationsModel1 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModel{}
			} else {
				notificationsModel1 = settingsModel0.Notifications
			}
			if vpnRaw2, ok := notificationsRaw1.GetVpnOk(); ok {
				var vpnModel2 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel
				if notificationsModel1.Vpn == nil {
					vpnModel2 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModel{}
				} else {
					vpnModel2 = notificationsModel1.Vpn
				}
				if v := vpnRaw2.GetHelpUrl(); v != "" {
					vpnModel2.HelpUrl = types.StringValue(string(v))
				} else {
					vpnModel2.HelpUrl = types.StringNull()
				}
				if v := vpnRaw2.GetMessage(); v != "" {
					vpnModel2.Message = types.StringValue(string(v))
				} else {
					vpnModel2.Message = types.StringNull()
				}
				if networkRaw3, ok := vpnRaw2.GetNetworkOk(); ok {
					var networkModel3 *ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel
					if vpnModel2.Network == nil {
						networkModel3 = &ApplicationSecurePasswordStoreModelSettingsModelNotificationsModelVpnModelNetworkModel{}
					} else {
						networkModel3 = vpnModel2.Network
					}
					if v := networkRaw3.GetConnection(); v != "" {
						networkModel3.Connection = types.StringValue(string(v))
					} else {
						networkModel3.Connection = types.StringNull()
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetExclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Exclude = listVal
					}
					{
						listVal, listDiags := types.ListValueFrom(ctx, types.StringType, networkRaw3.GetInclude())
						resp.Diagnostics.Append(listDiags...)
						networkModel3.Include = listVal
					}
					vpnModel2.Network = networkModel3
				}
				notificationsModel1.Vpn = vpnModel2
			}
			settingsModel0.Notifications = notificationsModel1
		}
		state.Settings = settingsModel0
	}
	if visibilityRaw0, ok := updateVariantObj.GetVisibilityOk(); ok {
		var visibilityModel0 *ApplicationSecurePasswordStoreModelVisibilityModel
		if state.Visibility == nil {
			visibilityModel0 = &ApplicationSecurePasswordStoreModelVisibilityModel{}
		} else {
			visibilityModel0 = state.Visibility
		}
		visibilityModel0.AutoLaunch = types.BoolValue(visibilityRaw0.GetAutoLaunch())
		visibilityModel0.AutoSubmitToolbar = types.BoolValue(visibilityRaw0.GetAutoSubmitToolbar())
		if hideRaw1, ok := visibilityRaw0.GetHideOk(); ok {
			var hideModel1 *ApplicationSecurePasswordStoreModelVisibilityModelHideModel
			if visibilityModel0.Hide == nil {
				hideModel1 = &ApplicationSecurePasswordStoreModelVisibilityModelHideModel{}
			} else {
				hideModel1 = visibilityModel0.Hide
			}
			hideModel1.IOS = types.BoolValue(hideRaw1.GetIOS())
			hideModel1.Web = types.BoolValue(hideRaw1.GetWeb())
			visibilityModel0.Hide = hideModel1
		}
		state.Visibility = visibilityModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *applicationSecurePasswordStoreResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state applicationSecurePasswordStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.ApplicationAPI.DeleteApplication(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting application_secure_password_store", err.Error())
		return
	}
}
