// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &resourceAppAccountResource{}
	_ resource.ResourceWithConfigure   = &resourceAppAccountResource{}
	_ resource.ResourceWithImportState = &resourceAppAccountResource{}
)

// ResourceAppAccountResource defines the resource implementation.
type resourceAppAccountResource struct {
	Config *config.Config
}

// ResourceAppAccountModel describes the resource data model.
type resourceAppAccountModel struct {
	ID                 types.String                                    `tfsdk:"id"`
	ResourceType       types.String                                    `tfsdk:"resource_type"`
	ContainerDetails   *ResourceAppAccountModelContainerDetailsModel   `tfsdk:"container_details"`
	Created            types.String                                    `tfsdk:"created"`
	CredentialSyncInfo *ResourceAppAccountModelCredentialSyncInfoModel `tfsdk:"credential_sync_info"`
	Credentials        *ResourceAppAccountModelCredentialsModel        `tfsdk:"credentials"`
	LastUpdated        types.String                                    `tfsdk:"last_updated"`
	Status             types.String                                    `tfsdk:"status"`
}

// ResourceAppAccountModelContainerDetailsModel is the nested model for container_details.
type ResourceAppAccountModelContainerDetailsModel struct {
	AppName               types.String `tfsdk:"app_name"`
	ContainerId           types.String `tfsdk:"container_id"`
	DisplayName           types.String `tfsdk:"display_name"`
	GlobalAppId           types.String `tfsdk:"global_app_id"`
	PasswordPushSupported types.Bool   `tfsdk:"password_push_supported"`
	ProvisioningEnabled   types.Bool   `tfsdk:"provisioning_enabled"`
	Status                types.String `tfsdk:"status"`
}

// ResourceAppAccountModelCredentialSyncInfoModel is the nested model for credential_sync_info.
type ResourceAppAccountModelCredentialSyncInfoModel struct {
	ErrorCode       types.String `tfsdk:"error_code"`
	ErrorReason     types.String `tfsdk:"error_reason"`
	SecretVersionId types.String `tfsdk:"secret_version_id"`
	SyncState       types.String `tfsdk:"sync_state"`
	SyncTime        types.String `tfsdk:"sync_time"`
}

// ResourceAppAccountModelCredentialsModel is the nested model for credentials.
type ResourceAppAccountModelCredentialsModel struct {
	Password types.String `tfsdk:"password"`
	UserName types.String `tfsdk:"user_name"`
}

func NewResourceAppAccountResource() resource.Resource {
	return &resourceAppAccountResource{}
}

func (r *resourceAppAccountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_resource_app_account"
}

func (r *resourceAppAccountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *resourceAppAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Privileged Resources API provides operations to fetch and manage privileged resources.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"resource_type": schema.StringAttribute{
				Description: "Discriminator field identifying the variant type. Must be set to \"APP_ACCOUNT\".",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the object was created",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the object was last updated",
				Computed:    true,
			},
			"status": schema.StringAttribute{
				Description: "Current status of the privileged resource",
				Computed:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"container_details": schema.SingleNestedBlock{
				Description: "Container details for resource type APP_ACCOUNT",
				Attributes: map[string]schema.Attribute{
					"app_name": schema.StringAttribute{
						Description: "The application name",
						Computed:    true,
					},
					"container_id": schema.StringAttribute{
						Description: "The app ID associated with the privileged resource",
						Required:    true,
					},
					"display_name": schema.StringAttribute{
						Description: "Human-readable name of the container that owns the privileged resource",
						Computed:    true,
					},
					"global_app_id": schema.StringAttribute{
						Description: "The application global ID",
						Computed:    true,
					},
					"password_push_supported": schema.BoolAttribute{
						Description: "Indicates if the application supports password push",
						Computed:    true,
					},
					"provisioning_enabled": schema.BoolAttribute{
						Description: "Indicates if provisioning is enabled for this application",
						Computed:    true,
					},
					"status": schema.StringAttribute{
						Description: "Current status of the application instance",
						Computed:    true,
					},
				},
			},
			"credential_sync_info": schema.SingleNestedBlock{
				Description: "CredentialSyncInfo",
				Attributes: map[string]schema.Attribute{
					"error_code": schema.StringAttribute{
						Description: "The error code for the type of error",
						Computed:    true,
					},
					"error_reason": schema.StringAttribute{
						Description: "A short description of the error",
						Computed:    true,
					},
					"secret_version_id": schema.StringAttribute{
						Description: "The version ID of the password secret from the OPA vault.",
						Optional:    true,
					},
					"sync_state": schema.StringAttribute{
						Description: "Current credential sync status of the privileged resource",
						Computed:    true,
					},
					"sync_time": schema.StringAttribute{
						Description: "Timestamp when the credential was changed",
						Computed:    true,
					},
				},
			},
			"credentials": schema.SingleNestedBlock{
				Description: "Credentials for the privileged resource",
				Attributes: map[string]schema.Attribute{
					"password": schema.StringAttribute{
						Description: "The password associated with the privileged resource",
						Optional:    true,
					},
					"user_name": schema.StringAttribute{
						Description: "The username associated with the privileged resource",
						Required:    true,
					},
				},
			},
		},
	}
}
func (r *resourceAppAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *resourceAppAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resourceAppAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.PrivilegedResourceAPI.GetPrivilegedResource(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading resource_app_account", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	variantObj := result.PrivilegedResourceAccountAppRequest
	if variantObj == nil {
		resp.Diagnostics.AddError("Error reading resource_app_account", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(variantObj.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(variantObj.GetLastUpdated().Format(time.RFC3339))
	state.Status = types.StringValue(string(variantObj.GetStatus()))
	state.ID = types.StringValue(string(variantObj.GetId()))
	if containerDetailsRaw0, ok := variantObj.GetContainerDetailsOk(); ok {
		var containerDetailsModel0 *ResourceAppAccountModelContainerDetailsModel
		if state.ContainerDetails == nil {
			containerDetailsModel0 = &ResourceAppAccountModelContainerDetailsModel{}
		} else {
			containerDetailsModel0 = state.ContainerDetails
		}
		containerDetailsModel0.AppName = types.StringValue(string(containerDetailsRaw0.GetAppName()))
		containerDetailsModel0.ContainerId = types.StringValue(string(containerDetailsRaw0.GetContainerId()))
		containerDetailsModel0.DisplayName = types.StringValue(string(containerDetailsRaw0.GetDisplayName()))
		containerDetailsModel0.GlobalAppId = types.StringValue(string(containerDetailsRaw0.GetGlobalAppId()))
		containerDetailsModel0.PasswordPushSupported = types.BoolValue(containerDetailsRaw0.GetPasswordPushSupported())
		containerDetailsModel0.ProvisioningEnabled = types.BoolValue(containerDetailsRaw0.GetProvisioningEnabled())
		containerDetailsModel0.Status = types.StringValue(string(containerDetailsRaw0.GetStatus()))
		state.ContainerDetails = containerDetailsModel0
	}
	if credentialSyncInfoRaw0, ok := variantObj.GetCredentialSyncInfoOk(); ok {
		var credentialSyncInfoModel0 *ResourceAppAccountModelCredentialSyncInfoModel
		if state.CredentialSyncInfo == nil {
			credentialSyncInfoModel0 = &ResourceAppAccountModelCredentialSyncInfoModel{}
		} else {
			credentialSyncInfoModel0 = state.CredentialSyncInfo
		}
		credentialSyncInfoModel0.ErrorCode = types.StringValue(string(credentialSyncInfoRaw0.GetErrorCode()))
		credentialSyncInfoModel0.ErrorReason = types.StringValue(string(credentialSyncInfoRaw0.GetErrorReason()))
		if v := credentialSyncInfoRaw0.GetSecretVersionId(); v != "" {
			credentialSyncInfoModel0.SecretVersionId = types.StringValue(string(v))
		} else {
			credentialSyncInfoModel0.SecretVersionId = types.StringNull()
		}
		credentialSyncInfoModel0.SyncState = types.StringValue(string(credentialSyncInfoRaw0.GetSyncState()))
		if t := credentialSyncInfoRaw0.GetSyncTime(); !t.IsZero() {
			credentialSyncInfoModel0.SyncTime = types.StringValue(t.Format(time.RFC3339))
		}
		state.CredentialSyncInfo = credentialSyncInfoModel0
	}
	if credentialsRaw0, ok := variantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ResourceAppAccountModelCredentialsModel
		if state.Credentials == nil {
			credentialsModel0 = &ResourceAppAccountModelCredentialsModel{}
		} else {
			credentialsModel0 = state.Credentials
		}
		if v := credentialsRaw0.GetPassword(); v != "" {
			credentialsModel0.Password = types.StringValue(string(v))
		} else {
			credentialsModel0.Password = types.StringNull()
		}
		credentialsModel0.UserName = types.StringValue(string(credentialsRaw0.GetUserName()))
		state.Credentials = credentialsModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *resourceAppAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resourceAppAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.PrivilegedResourceAPI.CreatePrivilegedResource(ctx)
	body := okta.NewPrivilegedResourceAccountAppRequestWithDefaults()
	if plan.ContainerDetails != nil {
		nestedContainerDetails := okta.NewAppAccountContainerDetailsWithDefaults()
		if !plan.ContainerDetails.AppName.IsNull() && !plan.ContainerDetails.AppName.IsUnknown() {
			nestedContainerDetails.SetAppName(plan.ContainerDetails.AppName.ValueString())
		}
		if !plan.ContainerDetails.ContainerId.IsNull() && !plan.ContainerDetails.ContainerId.IsUnknown() {
			nestedContainerDetails.SetContainerId(plan.ContainerDetails.ContainerId.ValueString())
		}
		if !plan.ContainerDetails.DisplayName.IsNull() && !plan.ContainerDetails.DisplayName.IsUnknown() {
			nestedContainerDetails.SetDisplayName(plan.ContainerDetails.DisplayName.ValueString())
		}
		if !plan.ContainerDetails.GlobalAppId.IsNull() && !plan.ContainerDetails.GlobalAppId.IsUnknown() {
			nestedContainerDetails.SetGlobalAppId(plan.ContainerDetails.GlobalAppId.ValueString())
		}
		if !plan.ContainerDetails.PasswordPushSupported.IsNull() && !plan.ContainerDetails.PasswordPushSupported.IsUnknown() {
			nestedContainerDetails.SetPasswordPushSupported(plan.ContainerDetails.PasswordPushSupported.ValueBool())
		}
		if !plan.ContainerDetails.ProvisioningEnabled.IsNull() && !plan.ContainerDetails.ProvisioningEnabled.IsUnknown() {
			nestedContainerDetails.SetProvisioningEnabled(plan.ContainerDetails.ProvisioningEnabled.ValueBool())
		}
		if !plan.ContainerDetails.Status.IsNull() && !plan.ContainerDetails.Status.IsUnknown() {
			nestedContainerDetails.SetStatus(plan.ContainerDetails.Status.ValueString())
		}
		body.SetContainerDetails(*nestedContainerDetails)
	}
	if plan.CredentialSyncInfo != nil {
		nestedCredentialSyncInfo := okta.NewCredentialSyncInfoWithDefaults()
		if !plan.CredentialSyncInfo.ErrorCode.IsNull() && !plan.CredentialSyncInfo.ErrorCode.IsUnknown() {
			nestedCredentialSyncInfo.SetErrorCode(plan.CredentialSyncInfo.ErrorCode.ValueString())
		}
		if !plan.CredentialSyncInfo.ErrorReason.IsNull() && !plan.CredentialSyncInfo.ErrorReason.IsUnknown() {
			nestedCredentialSyncInfo.SetErrorReason(plan.CredentialSyncInfo.ErrorReason.ValueString())
		}
		if !plan.CredentialSyncInfo.SecretVersionId.IsNull() && !plan.CredentialSyncInfo.SecretVersionId.IsUnknown() {
			nestedCredentialSyncInfo.SetSecretVersionId(plan.CredentialSyncInfo.SecretVersionId.ValueString())
		}
		if !plan.CredentialSyncInfo.SyncState.IsNull() && !plan.CredentialSyncInfo.SyncState.IsUnknown() {
			nestedCredentialSyncInfo.SetSyncState(plan.CredentialSyncInfo.SyncState.ValueString())
		}
		if !plan.CredentialSyncInfo.SyncTime.IsNull() && !plan.CredentialSyncInfo.SyncTime.IsUnknown() {
			if t, _err := time.Parse(time.RFC3339, plan.CredentialSyncInfo.SyncTime.ValueString()); _err == nil {
				nestedCredentialSyncInfo.SetSyncTime(t)
			}
		}
		body.SetCredentialSyncInfo(*nestedCredentialSyncInfo)
	}
	if plan.Credentials != nil {
		nestedCredentials := okta.NewPrivilegedResourceCredentialsWithDefaults()
		if !plan.Credentials.Password.IsNull() && !plan.Credentials.Password.IsUnknown() {
			nestedCredentials.SetPassword(plan.Credentials.Password.ValueString())
		}
		if !plan.Credentials.UserName.IsNull() && !plan.Credentials.UserName.IsUnknown() {
			nestedCredentials.SetUserName(plan.Credentials.UserName.ValueString())
		}
		body.SetCredentials(*nestedCredentials)
	}
	createReq = createReq.CreatePrivilegedResourceRequest(okta.PrivilegedResourceAccountAppRequestAsCreatePrivilegedResourceRequest(body))
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating resource_app_account", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	createVariantObj := result.PrivilegedResourceAccountAppRequest
	if createVariantObj == nil {
		resp.Diagnostics.AddError("Error creating resource_app_account", "API returned a response for a different variant type")
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(createVariantObj.GetId()))

	// Map computed fields from response back to plan (scalar types only)
	plan.Created = types.StringValue(createVariantObj.GetCreated().Format(time.RFC3339))
	plan.LastUpdated = types.StringValue(createVariantObj.GetLastUpdated().Format(time.RFC3339))
	plan.Status = types.StringValue(string(createVariantObj.GetStatus()))
	if containerDetailsRaw0, ok := createVariantObj.GetContainerDetailsOk(); ok {
		var containerDetailsModel0 *ResourceAppAccountModelContainerDetailsModel
		if plan.ContainerDetails == nil {
			containerDetailsModel0 = &ResourceAppAccountModelContainerDetailsModel{}
		} else {
			containerDetailsModel0 = plan.ContainerDetails
		}
		containerDetailsModel0.AppName = types.StringValue(string(containerDetailsRaw0.GetAppName()))
		containerDetailsModel0.ContainerId = types.StringValue(string(containerDetailsRaw0.GetContainerId()))
		containerDetailsModel0.DisplayName = types.StringValue(string(containerDetailsRaw0.GetDisplayName()))
		containerDetailsModel0.GlobalAppId = types.StringValue(string(containerDetailsRaw0.GetGlobalAppId()))
		containerDetailsModel0.PasswordPushSupported = types.BoolValue(containerDetailsRaw0.GetPasswordPushSupported())
		containerDetailsModel0.ProvisioningEnabled = types.BoolValue(containerDetailsRaw0.GetProvisioningEnabled())
		containerDetailsModel0.Status = types.StringValue(string(containerDetailsRaw0.GetStatus()))
		plan.ContainerDetails = containerDetailsModel0
	}
	if credentialSyncInfoRaw0, ok := createVariantObj.GetCredentialSyncInfoOk(); ok {
		var credentialSyncInfoModel0 *ResourceAppAccountModelCredentialSyncInfoModel
		if plan.CredentialSyncInfo == nil {
			credentialSyncInfoModel0 = &ResourceAppAccountModelCredentialSyncInfoModel{}
		} else {
			credentialSyncInfoModel0 = plan.CredentialSyncInfo
		}
		credentialSyncInfoModel0.ErrorCode = types.StringValue(string(credentialSyncInfoRaw0.GetErrorCode()))
		credentialSyncInfoModel0.ErrorReason = types.StringValue(string(credentialSyncInfoRaw0.GetErrorReason()))
		if v := credentialSyncInfoRaw0.GetSecretVersionId(); v != "" {
			credentialSyncInfoModel0.SecretVersionId = types.StringValue(string(v))
		} else {
			credentialSyncInfoModel0.SecretVersionId = types.StringNull()
		}
		credentialSyncInfoModel0.SyncState = types.StringValue(string(credentialSyncInfoRaw0.GetSyncState()))
		if t := credentialSyncInfoRaw0.GetSyncTime(); !t.IsZero() {
			credentialSyncInfoModel0.SyncTime = types.StringValue(t.Format(time.RFC3339))
		}
		plan.CredentialSyncInfo = credentialSyncInfoModel0
	}
	if credentialsRaw0, ok := createVariantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ResourceAppAccountModelCredentialsModel
		if plan.Credentials == nil {
			credentialsModel0 = &ResourceAppAccountModelCredentialsModel{}
		} else {
			credentialsModel0 = plan.Credentials
		}
		if v := credentialsRaw0.GetPassword(); v != "" {
			credentialsModel0.Password = types.StringValue(string(v))
		} else {
			credentialsModel0.Password = types.StringNull()
		}
		credentialsModel0.UserName = types.StringValue(string(credentialsRaw0.GetUserName()))
		plan.Credentials = credentialsModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *resourceAppAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan resourceAppAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state resourceAppAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.PrivilegedResourceAPI.ReplacePrivilegedResource(ctx, id)
	updateBody := okta.NewPrivilegedResourceAccountAppRequestWithDefaults()
	if plan.ContainerDetails != nil {
		nestedContainerDetails := okta.NewAppAccountContainerDetailsWithDefaults()
		if !plan.ContainerDetails.AppName.IsNull() && !plan.ContainerDetails.AppName.IsUnknown() {
			nestedContainerDetails.SetAppName(plan.ContainerDetails.AppName.ValueString())
		}
		if !plan.ContainerDetails.ContainerId.IsNull() && !plan.ContainerDetails.ContainerId.IsUnknown() {
			nestedContainerDetails.SetContainerId(plan.ContainerDetails.ContainerId.ValueString())
		}
		if !plan.ContainerDetails.DisplayName.IsNull() && !plan.ContainerDetails.DisplayName.IsUnknown() {
			nestedContainerDetails.SetDisplayName(plan.ContainerDetails.DisplayName.ValueString())
		}
		if !plan.ContainerDetails.GlobalAppId.IsNull() && !plan.ContainerDetails.GlobalAppId.IsUnknown() {
			nestedContainerDetails.SetGlobalAppId(plan.ContainerDetails.GlobalAppId.ValueString())
		}
		if !plan.ContainerDetails.PasswordPushSupported.IsNull() && !plan.ContainerDetails.PasswordPushSupported.IsUnknown() {
			nestedContainerDetails.SetPasswordPushSupported(plan.ContainerDetails.PasswordPushSupported.ValueBool())
		}
		if !plan.ContainerDetails.ProvisioningEnabled.IsNull() && !plan.ContainerDetails.ProvisioningEnabled.IsUnknown() {
			nestedContainerDetails.SetProvisioningEnabled(plan.ContainerDetails.ProvisioningEnabled.ValueBool())
		}
		if !plan.ContainerDetails.Status.IsNull() && !plan.ContainerDetails.Status.IsUnknown() {
			nestedContainerDetails.SetStatus(plan.ContainerDetails.Status.ValueString())
		}
		updateBody.SetContainerDetails(*nestedContainerDetails)
	}
	if plan.CredentialSyncInfo != nil {
		nestedCredentialSyncInfo := okta.NewCredentialSyncInfoWithDefaults()
		if !plan.CredentialSyncInfo.ErrorCode.IsNull() && !plan.CredentialSyncInfo.ErrorCode.IsUnknown() {
			nestedCredentialSyncInfo.SetErrorCode(plan.CredentialSyncInfo.ErrorCode.ValueString())
		}
		if !plan.CredentialSyncInfo.ErrorReason.IsNull() && !plan.CredentialSyncInfo.ErrorReason.IsUnknown() {
			nestedCredentialSyncInfo.SetErrorReason(plan.CredentialSyncInfo.ErrorReason.ValueString())
		}
		if !plan.CredentialSyncInfo.SecretVersionId.IsNull() && !plan.CredentialSyncInfo.SecretVersionId.IsUnknown() {
			nestedCredentialSyncInfo.SetSecretVersionId(plan.CredentialSyncInfo.SecretVersionId.ValueString())
		}
		if !plan.CredentialSyncInfo.SyncState.IsNull() && !plan.CredentialSyncInfo.SyncState.IsUnknown() {
			nestedCredentialSyncInfo.SetSyncState(plan.CredentialSyncInfo.SyncState.ValueString())
		}
		if !plan.CredentialSyncInfo.SyncTime.IsNull() && !plan.CredentialSyncInfo.SyncTime.IsUnknown() {
			if t, _err := time.Parse(time.RFC3339, plan.CredentialSyncInfo.SyncTime.ValueString()); _err == nil {
				nestedCredentialSyncInfo.SetSyncTime(t)
			}
		}
		updateBody.SetCredentialSyncInfo(*nestedCredentialSyncInfo)
	}
	if plan.Credentials != nil {
		nestedCredentials := okta.NewPrivilegedResourceCredentialsWithDefaults()
		if !plan.Credentials.Password.IsNull() && !plan.Credentials.Password.IsUnknown() {
			nestedCredentials.SetPassword(plan.Credentials.Password.ValueString())
		}
		if !plan.Credentials.UserName.IsNull() && !plan.Credentials.UserName.IsUnknown() {
			nestedCredentials.SetUserName(plan.Credentials.UserName.ValueString())
		}
		updateBody.SetCredentials(*nestedCredentials)
	}
	updateReq = updateReq.CreatePrivilegedResourceRequest(okta.PrivilegedResourceAccountAppRequestAsGetPrivilegedResource200Response(updateBody))
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating resource_app_account", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	updateVariantObj := result.PrivilegedResourceAccountAppRequest
	if updateVariantObj == nil {
		resp.Diagnostics.AddError("Error updating resource_app_account", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only)
	state.ID = types.StringValue(string(updateVariantObj.GetId()))
	state.Created = types.StringValue(updateVariantObj.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(updateVariantObj.GetLastUpdated().Format(time.RFC3339))
	state.Status = types.StringValue(string(updateVariantObj.GetStatus()))
	if containerDetailsRaw0, ok := updateVariantObj.GetContainerDetailsOk(); ok {
		var containerDetailsModel0 *ResourceAppAccountModelContainerDetailsModel
		if state.ContainerDetails == nil {
			containerDetailsModel0 = &ResourceAppAccountModelContainerDetailsModel{}
		} else {
			containerDetailsModel0 = state.ContainerDetails
		}
		containerDetailsModel0.AppName = types.StringValue(string(containerDetailsRaw0.GetAppName()))
		containerDetailsModel0.ContainerId = types.StringValue(string(containerDetailsRaw0.GetContainerId()))
		containerDetailsModel0.DisplayName = types.StringValue(string(containerDetailsRaw0.GetDisplayName()))
		containerDetailsModel0.GlobalAppId = types.StringValue(string(containerDetailsRaw0.GetGlobalAppId()))
		containerDetailsModel0.PasswordPushSupported = types.BoolValue(containerDetailsRaw0.GetPasswordPushSupported())
		containerDetailsModel0.ProvisioningEnabled = types.BoolValue(containerDetailsRaw0.GetProvisioningEnabled())
		containerDetailsModel0.Status = types.StringValue(string(containerDetailsRaw0.GetStatus()))
		state.ContainerDetails = containerDetailsModel0
	}
	if credentialSyncInfoRaw0, ok := updateVariantObj.GetCredentialSyncInfoOk(); ok {
		var credentialSyncInfoModel0 *ResourceAppAccountModelCredentialSyncInfoModel
		if state.CredentialSyncInfo == nil {
			credentialSyncInfoModel0 = &ResourceAppAccountModelCredentialSyncInfoModel{}
		} else {
			credentialSyncInfoModel0 = state.CredentialSyncInfo
		}
		credentialSyncInfoModel0.ErrorCode = types.StringValue(string(credentialSyncInfoRaw0.GetErrorCode()))
		credentialSyncInfoModel0.ErrorReason = types.StringValue(string(credentialSyncInfoRaw0.GetErrorReason()))
		if v := credentialSyncInfoRaw0.GetSecretVersionId(); v != "" {
			credentialSyncInfoModel0.SecretVersionId = types.StringValue(string(v))
		} else {
			credentialSyncInfoModel0.SecretVersionId = types.StringNull()
		}
		credentialSyncInfoModel0.SyncState = types.StringValue(string(credentialSyncInfoRaw0.GetSyncState()))
		if t := credentialSyncInfoRaw0.GetSyncTime(); !t.IsZero() {
			credentialSyncInfoModel0.SyncTime = types.StringValue(t.Format(time.RFC3339))
		}
		state.CredentialSyncInfo = credentialSyncInfoModel0
	}
	if credentialsRaw0, ok := updateVariantObj.GetCredentialsOk(); ok {
		var credentialsModel0 *ResourceAppAccountModelCredentialsModel
		if state.Credentials == nil {
			credentialsModel0 = &ResourceAppAccountModelCredentialsModel{}
		} else {
			credentialsModel0 = state.Credentials
		}
		if v := credentialsRaw0.GetPassword(); v != "" {
			credentialsModel0.Password = types.StringValue(string(v))
		} else {
			credentialsModel0.Password = types.StringNull()
		}
		credentialsModel0.UserName = types.StringValue(string(credentialsRaw0.GetUserName()))
		state.Credentials = credentialsModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *resourceAppAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resourceAppAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.PrivilegedResourceAPI.DeletePrivilegedResource(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting resource_app_account", err.Error())
		return
	}
}
