// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"strings"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &brandsTemplatesEmailCustomizationResource{}
	_ resource.ResourceWithConfigure   = &brandsTemplatesEmailCustomizationResource{}
	_ resource.ResourceWithImportState = &brandsTemplatesEmailCustomizationResource{}
)

// BrandsTemplatesEmailCustomizationResource defines the resource implementation.
type brandsTemplatesEmailCustomizationResource struct {
	Config *config.Config
}

// BrandsTemplatesEmailCustomizationModel describes the resource data model.
type brandsTemplatesEmailCustomizationModel struct {
	ID           types.String `tfsdk:"id"`
	BrandId      types.String `tfsdk:"brand_id"`
	TemplateName types.String `tfsdk:"template_name"`
	Body         types.String `tfsdk:"body"`
	Created      types.String `tfsdk:"created"`
	IsDefault    types.Bool   `tfsdk:"is_default"`
	Language     types.String `tfsdk:"language"`
	LastUpdated  types.String `tfsdk:"last_updated"`
	Subject      types.String `tfsdk:"subject"`
}

func NewBrandsTemplatesEmailCustomizationResource() resource.Resource {
	return &brandsTemplatesEmailCustomizationResource{}
}

func (r *brandsTemplatesEmailCustomizationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_brands_templates_email_customization"
}

func (r *brandsTemplatesEmailCustomizationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *brandsTemplatesEmailCustomizationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "These endpoints allow you to programmatically manage email customizations.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"brand_id": schema.StringAttribute{
				Description: "The ID of the brand",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"template_name": schema.StringAttribute{
				Description: "The name of the email template",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"body": schema.StringAttribute{
				Description: "The HTML body of the email.",
				Required:    true,
			},
			"created": schema.StringAttribute{
				Description: "The UTC time at which this email customization was created.",
				Computed:    true,
			},
			"is_default": schema.BoolAttribute{
				Description: "Whether this is the default customization for the email template.",
				Optional:    true,
			},
			"language": schema.StringAttribute{
				Description: "The language specified as an [IETF BCP 47 language tag](https://datatracker.",
				Required:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "The UTC time at which this email customization was last updated.",
				Computed:    true,
			},
			"subject": schema.StringAttribute{
				Description: "The email subject.",
				Required:    true,
			},
		},
	}
}
func (r *brandsTemplatesEmailCustomizationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: {brand_id}/{template_name}/{id}
	parts := strings.SplitN(req.ID, "/", 3)
	if len(parts) != 3 || parts[0] == "" || parts[0] == "" || parts[2] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Import ID must be in the format: {brand_id}/{template_name}/{id}",
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("brand_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("template_name"), parts[1])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, frameworkPath.Root("id"), parts[2])...)
}

func (r *brandsTemplatesEmailCustomizationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state brandsTemplatesEmailCustomizationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	brandId := state.BrandId.ValueString()
	templateName := state.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.CustomTemplatesAPI.GetEmailCustomization(ctx, brandId, templateName, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading brands_templates_email_customization", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Body = types.StringValue(string(result.GetBody()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsDefault = types.BoolValue(result.GetIsDefault())
	state.Language = types.StringValue(string(result.GetLanguage()))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.Subject = types.StringValue(string(result.GetSubject()))

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *brandsTemplatesEmailCustomizationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan brandsTemplatesEmailCustomizationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	brandId := plan.BrandId.ValueString()
	templateName := plan.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.CustomTemplatesAPI.CreateEmailCustomization(ctx, brandId, templateName)
	body := okta.NewEmailCustomizationWithDefaults()
	body.SetBody(plan.Body.ValueString())
	body.SetIsDefault(plan.IsDefault.ValueBool())
	body.SetLanguage(plan.Language.ValueString())
	body.SetSubject(plan.Subject.ValueString())
	createReq = createReq.Instance(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating brands_templates_email_customization", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Body = types.StringValue(string(result.GetBody()))
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.IsDefault = types.BoolValue(result.GetIsDefault())
	plan.Language = types.StringValue(string(result.GetLanguage()))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	plan.Subject = types.StringValue(string(result.GetSubject()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *brandsTemplatesEmailCustomizationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan brandsTemplatesEmailCustomizationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state brandsTemplatesEmailCustomizationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	brandId := state.BrandId.ValueString()
	templateName := state.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.CustomTemplatesAPI.ReplaceEmailCustomization(ctx, brandId, templateName, id)
	updateBody := okta.NewEmailCustomizationWithDefaults()
	updateBody.SetBody(plan.Body.ValueString())
	updateBody.SetIsDefault(plan.IsDefault.ValueBool())
	updateBody.SetLanguage(plan.Language.ValueString())
	updateBody.SetSubject(plan.Subject.ValueString())
	updateReq = updateReq.Instance(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating brands_templates_email_customization", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Body = types.StringValue(string(result.GetBody()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsDefault = types.BoolValue(result.GetIsDefault())
	state.Language = types.StringValue(string(result.GetLanguage()))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	state.Subject = types.StringValue(string(result.GetSubject()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *brandsTemplatesEmailCustomizationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state brandsTemplatesEmailCustomizationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	brandId := state.BrandId.ValueString()
	templateName := state.TemplateName.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.CustomTemplatesAPI.DeleteEmailCustomization(ctx, brandId, templateName, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting brands_templates_email_customization", err.Error())
		return
	}
}
