// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource              = &orgResource{}
	_ resource.ResourceWithConfigure = &orgResource{}
)

// OrgResource defines the resource implementation.
type orgResource struct {
	Config *config.Config
}

// OrgModel describes the resource data model.
type orgModel struct {
	Address1              types.String `tfsdk:"address1"`
	Address2              types.String `tfsdk:"address2"`
	City                  types.String `tfsdk:"city"`
	CompanyName           types.String `tfsdk:"company_name"`
	Country               types.String `tfsdk:"country"`
	Created               types.String `tfsdk:"created"`
	EndUserSupportHelpURL types.String `tfsdk:"end_user_support_help_url"`
	ExpiresAt             types.String `tfsdk:"expires_at"`
	LastUpdated           types.String `tfsdk:"last_updated"`
	PhoneNumber           types.String `tfsdk:"phone_number"`
	PostalCode            types.String `tfsdk:"postal_code"`
	State                 types.String `tfsdk:"state"`
	Status                types.String `tfsdk:"status"`
	Subdomain             types.String `tfsdk:"subdomain"`
	SupportPhoneNumber    types.String `tfsdk:"support_phone_number"`
	Website               types.String `tfsdk:"website"`
}

func NewOrgResource() resource.Resource {
	return &orgResource{}
}

func (r *orgResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_org"
}

func (r *orgResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *orgResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Org General Settings API provides operations to manage the general settings of your Okta org.",
		Attributes: map[string]schema.Attribute{
			"address1": schema.StringAttribute{
				Description: "Primary address of the organization associated with the org",
				Optional:    true,
			},
			"address2": schema.StringAttribute{
				Description: "Secondary address of the organization associated with the org",
				Optional:    true,
			},
			"city": schema.StringAttribute{
				Description: "City of the organization associated with the org",
				Optional:    true,
			},
			"company_name": schema.StringAttribute{
				Description: "Name of org",
				Optional:    true,
			},
			"country": schema.StringAttribute{
				Description: "County of the organization associated with the org",
				Optional:    true,
			},
			"created": schema.StringAttribute{
				Description: "When org was created",
				Computed:    true,
			},
			"end_user_support_help_url": schema.StringAttribute{
				Description: "Support link of org",
				Optional:    true,
			},
			"expires_at": schema.StringAttribute{
				Description: "Expiration of org",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "When org was last updated",
				Computed:    true,
			},
			"phone_number": schema.StringAttribute{
				Description: "Phone number of the organization associated with the org",
				Optional:    true,
			},
			"postal_code": schema.StringAttribute{
				Description: "Postal code of the organization associated with the org",
				Optional:    true,
			},
			"state": schema.StringAttribute{
				Description: "State of the organization associated with the org",
				Optional:    true,
			},
			"status": schema.StringAttribute{
				Description: "Status of org",
				Computed:    true,
			},
			"subdomain": schema.StringAttribute{
				Description: "Subdomain of org",
				Computed:    true,
			},
			"support_phone_number": schema.StringAttribute{
				Description: "Support help phone of the organization associated with the org",
				Optional:    true,
			},
			"website": schema.StringAttribute{
				Description: "Website of the organization associated with the org",
				Optional:    true,
			},
		},
	}
}

func (r *orgResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state orgModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.OrgSettingGeneralAPI.GetOrgSettings(ctx).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading org", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	if v := result.GetAddress1(); v != "" {
		state.Address1 = types.StringValue(string(v))
	} else {
		state.Address1 = types.StringNull()
	}
	if v := result.GetAddress2(); v != "" {
		state.Address2 = types.StringValue(string(v))
	} else {
		state.Address2 = types.StringNull()
	}
	if v := result.GetCity(); v != "" {
		state.City = types.StringValue(string(v))
	} else {
		state.City = types.StringNull()
	}
	if v := result.GetCompanyName(); v != "" {
		state.CompanyName = types.StringValue(string(v))
	} else {
		state.CompanyName = types.StringNull()
	}
	if v := result.GetCountry(); v != "" {
		state.Country = types.StringValue(string(v))
	} else {
		state.Country = types.StringNull()
	}
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetEndUserSupportHelpURL(); v != "" {
		state.EndUserSupportHelpURL = types.StringValue(string(v))
	} else {
		state.EndUserSupportHelpURL = types.StringNull()
	}
	state.ExpiresAt = types.StringValue(result.GetExpiresAt().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetPhoneNumber(); v != "" {
		state.PhoneNumber = types.StringValue(string(v))
	} else {
		state.PhoneNumber = types.StringNull()
	}
	if v := result.GetPostalCode(); v != "" {
		state.PostalCode = types.StringValue(string(v))
	} else {
		state.PostalCode = types.StringNull()
	}
	if v := result.GetState(); v != "" {
		state.State = types.StringValue(string(v))
	} else {
		state.State = types.StringNull()
	}
	state.Status = types.StringValue(string(result.GetStatus()))
	state.Subdomain = types.StringValue(string(result.GetSubdomain()))
	if v := result.GetSupportPhoneNumber(); v != "" {
		state.SupportPhoneNumber = types.StringValue(string(v))
	} else {
		state.SupportPhoneNumber = types.StringNull()
	}
	if v := result.GetWebsite(); v != "" {
		state.Website = types.StringValue(string(v))
	} else {
		state.Website = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *orgResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan orgModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.OrgSettingGeneralAPI.UpdateOrgSettings(ctx)
	body := okta.NewOrgSettingWithDefaults()
	body.SetAddress1(plan.Address1.ValueString())
	body.SetAddress2(plan.Address2.ValueString())
	body.SetCity(plan.City.ValueString())
	body.SetCompanyName(plan.CompanyName.ValueString())
	body.SetCountry(plan.Country.ValueString())
	body.SetEndUserSupportHelpURL(plan.EndUserSupportHelpURL.ValueString())
	body.SetPhoneNumber(plan.PhoneNumber.ValueString())
	body.SetPostalCode(plan.PostalCode.ValueString())
	body.SetState(plan.State.ValueString())
	body.SetSupportPhoneNumber(plan.SupportPhoneNumber.ValueString())
	body.SetWebsite(plan.Website.ValueString())
	createReq = createReq.OrgSetting(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating org", err.Error())
		return
	}
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	if v := result.GetAddress1(); v != "" {
		plan.Address1 = types.StringValue(string(v))
	} else {
		plan.Address1 = types.StringNull()
	}
	if v := result.GetAddress2(); v != "" {
		plan.Address2 = types.StringValue(string(v))
	} else {
		plan.Address2 = types.StringNull()
	}
	if v := result.GetCity(); v != "" {
		plan.City = types.StringValue(string(v))
	} else {
		plan.City = types.StringNull()
	}
	if v := result.GetCompanyName(); v != "" {
		plan.CompanyName = types.StringValue(string(v))
	} else {
		plan.CompanyName = types.StringNull()
	}
	if v := result.GetCountry(); v != "" {
		plan.Country = types.StringValue(string(v))
	} else {
		plan.Country = types.StringNull()
	}
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	if v := result.GetEndUserSupportHelpURL(); v != "" {
		plan.EndUserSupportHelpURL = types.StringValue(string(v))
	} else {
		plan.EndUserSupportHelpURL = types.StringNull()
	}
	plan.ExpiresAt = types.StringValue(result.GetExpiresAt().Format(time.RFC3339))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetPhoneNumber(); v != "" {
		plan.PhoneNumber = types.StringValue(string(v))
	} else {
		plan.PhoneNumber = types.StringNull()
	}
	if v := result.GetPostalCode(); v != "" {
		plan.PostalCode = types.StringValue(string(v))
	} else {
		plan.PostalCode = types.StringNull()
	}
	if v := result.GetState(); v != "" {
		plan.State = types.StringValue(string(v))
	} else {
		plan.State = types.StringNull()
	}
	plan.Status = types.StringValue(string(result.GetStatus()))
	plan.Subdomain = types.StringValue(string(result.GetSubdomain()))
	if v := result.GetSupportPhoneNumber(); v != "" {
		plan.SupportPhoneNumber = types.StringValue(string(v))
	} else {
		plan.SupportPhoneNumber = types.StringNull()
	}
	if v := result.GetWebsite(); v != "" {
		plan.Website = types.StringValue(string(v))
	} else {
		plan.Website = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *orgResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddWarning(
		"Update Not Supported",
		"This resource does not support in-place updates. Changes will require resource replacement.",
	)
}

func (r *orgResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning(
		"Delete Not Supported",
		"This resource cannot be deleted via Terraform.",
	)
}
