// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &realmAssignmentResource{}
	_ resource.ResourceWithConfigure   = &realmAssignmentResource{}
	_ resource.ResourceWithImportState = &realmAssignmentResource{}
)

// RealmAssignmentResource defines the resource implementation.
type realmAssignmentResource struct {
	Config *config.Config
}

// RealmAssignmentModel describes the resource data model.
type realmAssignmentModel struct {
	ID          types.String                         `tfsdk:"id"`
	Actions     *RealmAssignmentModelActionsModel    `tfsdk:"actions"`
	Conditions  *RealmAssignmentModelConditionsModel `tfsdk:"conditions"`
	Created     types.String                         `tfsdk:"created"`
	Domains     types.List                           `tfsdk:"domains"`
	IsDefault   types.Bool                           `tfsdk:"is_default"`
	LastUpdated types.String                         `tfsdk:"last_updated"`
	Name        types.String                         `tfsdk:"name"`
	Priority    types.Int64                          `tfsdk:"priority"`
	Status      types.String                         `tfsdk:"status"`
}

// RealmAssignmentModelActionsModel is the nested model for actions.
type RealmAssignmentModelActionsModel struct {
	AssignUserToRealm *RealmAssignmentModelActionsModelAssignUserToRealmModel `tfsdk:"assign_user_to_realm"`
}

// RealmAssignmentModelActionsModelAssignUserToRealmModel is the nested model for assign_user_to_realm.
type RealmAssignmentModelActionsModelAssignUserToRealmModel struct {
	RealmId types.String `tfsdk:"realm_id"`
}

// RealmAssignmentModelConditionsModel is the nested model for conditions.
type RealmAssignmentModelConditionsModel struct {
	Expression      *RealmAssignmentModelConditionsModelExpressionModel `tfsdk:"expression"`
	ProfileSourceId types.String                                        `tfsdk:"profile_source_id"`
}

// RealmAssignmentModelConditionsModelExpressionModel is the nested model for expression.
type RealmAssignmentModelConditionsModelExpressionModel struct {
	Value types.String `tfsdk:"value"`
}

func NewRealmAssignmentResource() resource.Resource {
	return &realmAssignmentResource{}
}

func (r *realmAssignmentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_realm_assignment"
}

func (r *realmAssignmentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *realmAssignmentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "> **Note:** This API is only available if you're subscribed to Okta Identity Governance or Secure Partner Access, or Advanced Directory Management.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the realm assignment was created",
				Computed:    true,
			},
			"domains": schema.ListAttribute{
				Description: "Array of allowed domains.",
				ElementType: types.StringType,
				Optional:    true,
			},
			"is_default": schema.BoolAttribute{
				Description: "Indicates the default realm.",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp of when the realm assignment was updated",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "Name of the realm",
				Optional:    true,
			},
			"priority": schema.Int64Attribute{
				Description: "The priority of the realm assignment.",
				Optional:    true,
			},
			"status": schema.StringAttribute{
				Description: "Status",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"actions": schema.SingleNestedBlock{
				Description: "Action to apply to a user",
				Blocks: map[string]schema.Block{
					"assign_user_to_realm": schema.SingleNestedBlock{
						Description: "Action that assigns a user to a realm",
						Attributes: map[string]schema.Attribute{
							"realm_id": schema.StringAttribute{
								Description: "ID of the realm",
								Optional:    true,
							},
						},
					},
				},
			},
			"conditions": schema.SingleNestedBlock{
				Description: "Conditions of applying realm assignment",
				Attributes: map[string]schema.Attribute{
					"profile_source_id": schema.StringAttribute{
						Description: "ID of the profile source",
						Optional:    true,
					},
				},
				Blocks: map[string]schema.Block{
					"expression": schema.SingleNestedBlock{
						Description: "Conditional expression",
						Attributes: map[string]schema.Attribute{
							"value": schema.StringAttribute{
								Description: "Value of the condition expression",
								Optional:    true,
							},
						},
					},
				},
			},
		},
	}
}
func (r *realmAssignmentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *realmAssignmentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state realmAssignmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.RealmAssignmentAPI.GetRealmAssignment(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading realm_assignment", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsDefault = types.BoolValue(result.GetIsDefault())
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	state.Priority = types.Int64Value(int64(result.GetPriority()))
	if v := result.GetStatus(); v != "" {
		state.Status = types.StringValue(string(v))
	} else {
		state.Status = types.StringNull()
	}
	if actionsRaw0, ok := result.GetActionsOk(); ok {
		var actionsModel0 *RealmAssignmentModelActionsModel
		if state.Actions == nil {
			actionsModel0 = &RealmAssignmentModelActionsModel{}
		} else {
			actionsModel0 = state.Actions
		}
		if assignUserToRealmRaw1, ok := actionsRaw0.GetAssignUserToRealmOk(); ok {
			var assignUserToRealmModel1 *RealmAssignmentModelActionsModelAssignUserToRealmModel
			if actionsModel0.AssignUserToRealm == nil {
				assignUserToRealmModel1 = &RealmAssignmentModelActionsModelAssignUserToRealmModel{}
			} else {
				assignUserToRealmModel1 = actionsModel0.AssignUserToRealm
			}
			if v := assignUserToRealmRaw1.GetRealmId(); v != "" {
				assignUserToRealmModel1.RealmId = types.StringValue(string(v))
			} else {
				assignUserToRealmModel1.RealmId = types.StringNull()
			}
			actionsModel0.AssignUserToRealm = assignUserToRealmModel1
		}
		state.Actions = actionsModel0
	}
	if conditionsRaw0, ok := result.GetConditionsOk(); ok {
		var conditionsModel0 *RealmAssignmentModelConditionsModel
		if state.Conditions == nil {
			conditionsModel0 = &RealmAssignmentModelConditionsModel{}
		} else {
			conditionsModel0 = state.Conditions
		}
		if expressionRaw1, ok := conditionsRaw0.GetExpressionOk(); ok {
			var expressionModel1 *RealmAssignmentModelConditionsModelExpressionModel
			if conditionsModel0.Expression == nil {
				expressionModel1 = &RealmAssignmentModelConditionsModelExpressionModel{}
			} else {
				expressionModel1 = conditionsModel0.Expression
			}
			if v := expressionRaw1.GetValue(); v != "" {
				expressionModel1.Value = types.StringValue(string(v))
			} else {
				expressionModel1.Value = types.StringNull()
			}
			conditionsModel0.Expression = expressionModel1
		}
		if v := conditionsRaw0.GetProfileSourceId(); v != "" {
			conditionsModel0.ProfileSourceId = types.StringValue(string(v))
		} else {
			conditionsModel0.ProfileSourceId = types.StringNull()
		}
		state.Conditions = conditionsModel0
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *realmAssignmentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan realmAssignmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.RealmAssignmentAPI.CreateRealmAssignment(ctx)
	body := okta.NewCreateRealmAssignmentRequestWithDefaults()
	if plan.Actions != nil {
		nestedActions := okta.NewActionsWithDefaults()
		body.SetActions(*nestedActions)
	}
	if plan.Conditions != nil {
		nestedConditions := okta.NewConditionsWithDefaults()
		if !plan.Conditions.ProfileSourceId.IsNull() && !plan.Conditions.ProfileSourceId.IsUnknown() {
			nestedConditions.SetProfileSourceId(plan.Conditions.ProfileSourceId.ValueString())
		}
		body.SetConditions(*nestedConditions)
	}
	body.SetName(plan.Name.ValueString())
	body.SetPriority(int32(plan.Priority.ValueInt64()))
	createReq = createReq.Body(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating realm_assignment", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.IsDefault = types.BoolValue(result.GetIsDefault())
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		plan.Name = types.StringValue(string(v))
	} else {
		plan.Name = types.StringNull()
	}
	plan.Priority = types.Int64Value(int64(result.GetPriority()))
	if v := result.GetStatus(); v != "" {
		plan.Status = types.StringValue(string(v))
	} else {
		plan.Status = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *realmAssignmentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan realmAssignmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state realmAssignmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.RealmAssignmentAPI.ReplaceRealmAssignment(ctx, id)
	updateBody := okta.NewUpdateRealmAssignmentRequestWithDefaults()
	if plan.Actions != nil {
		nestedActions := okta.NewActionsWithDefaults()
		updateBody.SetActions(*nestedActions)
	}
	if plan.Conditions != nil {
		nestedConditions := okta.NewConditionsWithDefaults()
		if !plan.Conditions.ProfileSourceId.IsNull() && !plan.Conditions.ProfileSourceId.IsUnknown() {
			nestedConditions.SetProfileSourceId(plan.Conditions.ProfileSourceId.ValueString())
		}
		updateBody.SetConditions(*nestedConditions)
	}
	updateBody.SetName(plan.Name.ValueString())
	updateBody.SetPriority(int32(plan.Priority.ValueInt64()))
	updateReq = updateReq.Body(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating realm_assignment", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsDefault = types.BoolValue(result.GetIsDefault())
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	state.Priority = types.Int64Value(int64(result.GetPriority()))
	if v := result.GetStatus(); v != "" {
		state.Status = types.StringValue(string(v))
	} else {
		state.Status = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *realmAssignmentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state realmAssignmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.RealmAssignmentAPI.DeleteRealmAssignment(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting realm_assignment", err.Error())
		return
	}
}
