// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &pushProviderApnsResource{}
	_ resource.ResourceWithConfigure   = &pushProviderApnsResource{}
	_ resource.ResourceWithImportState = &pushProviderApnsResource{}
)

// PushProviderApnsResource defines the resource implementation.
type pushProviderApnsResource struct {
	Config *config.Config
}

// PushProviderApnsModel describes the resource data model.
type pushProviderApnsModel struct {
	ID              types.String                             `tfsdk:"id"`
	ProviderType    types.String                             `tfsdk:"provider_type"`
	Configuration   *PushProviderApnsModelConfigurationModel `tfsdk:"configuration"`
	LastUpdatedDate types.String                             `tfsdk:"last_updated_date"`
	Name            types.String                             `tfsdk:"name"`
}

// PushProviderApnsModelConfigurationModel is the nested model for configuration.
type PushProviderApnsModelConfigurationModel struct {
	FileName        types.String `tfsdk:"file_name"`
	KeyId           types.String `tfsdk:"key_id"`
	TeamId          types.String `tfsdk:"team_id"`
	TokenSigningKey types.String `tfsdk:"token_signing_key"`
}

func NewPushProviderApnsResource() resource.Resource {
	return &pushProviderApnsResource{}
}

func (r *pushProviderApnsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_push_provider_apns"
}

func (r *pushProviderApnsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *pushProviderApnsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Okta Push Providers API provides a centralized integration platform to fetch and manage push provider configurations.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"provider_type": schema.StringAttribute{
				Description: "Discriminator field identifying the variant type. Must be set to \"APNS\".",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"last_updated_date": schema.StringAttribute{
				Description: "Timestamp when the Push Provider was last modified",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "Display name of the push provider",
				Optional:    true,
			},
		},
		Blocks: map[string]schema.Block{
			"configuration": schema.SingleNestedBlock{
				Description: "Configuration",
				Attributes: map[string]schema.Attribute{
					"file_name": schema.StringAttribute{
						Description: "(Optional) File name for Admin Console display",
						Optional:    true,
					},
					"key_id": schema.StringAttribute{
						Description: "10-character Key ID obtained from the Apple developer account",
						Optional:    true,
					},
					"team_id": schema.StringAttribute{
						Description: "10-character Team ID used to develop the iOS app",
						Optional:    true,
					},
					"token_signing_key": schema.StringAttribute{
						Description: "APNs private authentication token signing key",
						Optional:    true,
					},
				},
			},
		},
	}
}
func (r *pushProviderApnsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *pushProviderApnsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state pushProviderApnsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.PushProviderAPI.GetPushProvider(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading push_provider_apns", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	variantObj := result.APNSPushProvider
	if variantObj == nil {
		resp.Diagnostics.AddError("Error reading push_provider_apns", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.LastUpdatedDate = types.StringValue(string(variantObj.GetLastUpdatedDate()))
	if v := variantObj.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	state.ID = types.StringValue(string(variantObj.GetId()))
	if configurationRaw0, ok := variantObj.GetConfigurationOk(); ok {
		var configurationModel0 *PushProviderApnsModelConfigurationModel
		if state.Configuration == nil {
			configurationModel0 = &PushProviderApnsModelConfigurationModel{}
		} else {
			configurationModel0 = state.Configuration
		}
		if v := configurationRaw0.GetFileName(); v != "" {
			configurationModel0.FileName = types.StringValue(string(v))
		} else {
			configurationModel0.FileName = types.StringNull()
		}
		if v := configurationRaw0.GetKeyId(); v != "" {
			configurationModel0.KeyId = types.StringValue(string(v))
		} else {
			configurationModel0.KeyId = types.StringNull()
		}
		if v := configurationRaw0.GetTeamId(); v != "" {
			configurationModel0.TeamId = types.StringValue(string(v))
		} else {
			configurationModel0.TeamId = types.StringNull()
		}
		if v := configurationRaw0.GetTokenSigningKey(); v != "" {
			configurationModel0.TokenSigningKey = types.StringValue(string(v))
		} else {
			configurationModel0.TokenSigningKey = types.StringNull()
		}
		state.Configuration = configurationModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *pushProviderApnsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan pushProviderApnsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.PushProviderAPI.CreatePushProvider(ctx)
	body := okta.NewAPNSPushProviderWithDefaults()
	if plan.Configuration != nil {
		nestedConfiguration := okta.NewAPNSConfigurationWithDefaults()
		if !plan.Configuration.FileName.IsNull() && !plan.Configuration.FileName.IsUnknown() {
			nestedConfiguration.SetFileName(plan.Configuration.FileName.ValueString())
		}
		if !plan.Configuration.KeyId.IsNull() && !plan.Configuration.KeyId.IsUnknown() {
			nestedConfiguration.SetKeyId(plan.Configuration.KeyId.ValueString())
		}
		if !plan.Configuration.TeamId.IsNull() && !plan.Configuration.TeamId.IsUnknown() {
			nestedConfiguration.SetTeamId(plan.Configuration.TeamId.ValueString())
		}
		if !plan.Configuration.TokenSigningKey.IsNull() && !plan.Configuration.TokenSigningKey.IsUnknown() {
			nestedConfiguration.SetTokenSigningKey(plan.Configuration.TokenSigningKey.ValueString())
		}
		body.SetConfiguration(*nestedConfiguration)
	}
	body.SetName(plan.Name.ValueString())
	createReq = createReq.PushProvider(okta.APNSPushProviderAsListPushProviders200ResponseInner(body))
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating push_provider_apns", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	createVariantObj := result.APNSPushProvider
	if createVariantObj == nil {
		resp.Diagnostics.AddError("Error creating push_provider_apns", "API returned a response for a different variant type")
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(createVariantObj.GetId()))

	// Map computed fields from response back to plan (scalar types only)
	plan.LastUpdatedDate = types.StringValue(string(createVariantObj.GetLastUpdatedDate()))
	if configurationRaw0, ok := createVariantObj.GetConfigurationOk(); ok {
		var configurationModel0 *PushProviderApnsModelConfigurationModel
		if plan.Configuration == nil {
			configurationModel0 = &PushProviderApnsModelConfigurationModel{}
		} else {
			configurationModel0 = plan.Configuration
		}
		if v := configurationRaw0.GetFileName(); v != "" {
			configurationModel0.FileName = types.StringValue(string(v))
		} else {
			configurationModel0.FileName = types.StringNull()
		}
		if v := configurationRaw0.GetKeyId(); v != "" {
			configurationModel0.KeyId = types.StringValue(string(v))
		} else {
			configurationModel0.KeyId = types.StringNull()
		}
		if v := configurationRaw0.GetTeamId(); v != "" {
			configurationModel0.TeamId = types.StringValue(string(v))
		} else {
			configurationModel0.TeamId = types.StringNull()
		}
		if v := configurationRaw0.GetTokenSigningKey(); v != "" {
			configurationModel0.TokenSigningKey = types.StringValue(string(v))
		} else {
			configurationModel0.TokenSigningKey = types.StringNull()
		}
		plan.Configuration = configurationModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *pushProviderApnsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan pushProviderApnsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state pushProviderApnsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.PushProviderAPI.ReplacePushProvider(ctx, id)
	updateBody := okta.NewAPNSPushProviderWithDefaults()
	if plan.Configuration != nil {
		nestedConfiguration := okta.NewAPNSConfigurationWithDefaults()
		if !plan.Configuration.FileName.IsNull() && !plan.Configuration.FileName.IsUnknown() {
			nestedConfiguration.SetFileName(plan.Configuration.FileName.ValueString())
		}
		if !plan.Configuration.KeyId.IsNull() && !plan.Configuration.KeyId.IsUnknown() {
			nestedConfiguration.SetKeyId(plan.Configuration.KeyId.ValueString())
		}
		if !plan.Configuration.TeamId.IsNull() && !plan.Configuration.TeamId.IsUnknown() {
			nestedConfiguration.SetTeamId(plan.Configuration.TeamId.ValueString())
		}
		if !plan.Configuration.TokenSigningKey.IsNull() && !plan.Configuration.TokenSigningKey.IsUnknown() {
			nestedConfiguration.SetTokenSigningKey(plan.Configuration.TokenSigningKey.ValueString())
		}
		updateBody.SetConfiguration(*nestedConfiguration)
	}
	updateBody.SetName(plan.Name.ValueString())
	updateReq = updateReq.PushProvider(okta.APNSPushProviderAsListPushProviders200ResponseInner(updateBody))
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating push_provider_apns", err.Error())
		return
	}
	// Unwrap the union type to access the concrete variant's fields.
	updateVariantObj := result.APNSPushProvider
	if updateVariantObj == nil {
		resp.Diagnostics.AddError("Error updating push_provider_apns", "API returned a response for a different variant type")
		return
	}

	// Map API response fields to state (scalar types only)
	state.ID = types.StringValue(string(updateVariantObj.GetId()))
	state.LastUpdatedDate = types.StringValue(string(updateVariantObj.GetLastUpdatedDate()))
	if v := updateVariantObj.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}
	if configurationRaw0, ok := updateVariantObj.GetConfigurationOk(); ok {
		var configurationModel0 *PushProviderApnsModelConfigurationModel
		if state.Configuration == nil {
			configurationModel0 = &PushProviderApnsModelConfigurationModel{}
		} else {
			configurationModel0 = state.Configuration
		}
		if v := configurationRaw0.GetFileName(); v != "" {
			configurationModel0.FileName = types.StringValue(string(v))
		} else {
			configurationModel0.FileName = types.StringNull()
		}
		if v := configurationRaw0.GetKeyId(); v != "" {
			configurationModel0.KeyId = types.StringValue(string(v))
		} else {
			configurationModel0.KeyId = types.StringNull()
		}
		if v := configurationRaw0.GetTeamId(); v != "" {
			configurationModel0.TeamId = types.StringValue(string(v))
		} else {
			configurationModel0.TeamId = types.StringNull()
		}
		if v := configurationRaw0.GetTokenSigningKey(); v != "" {
			configurationModel0.TokenSigningKey = types.StringValue(string(v))
		} else {
			configurationModel0.TokenSigningKey = types.StringNull()
		}
		state.Configuration = configurationModel0
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *pushProviderApnsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state pushProviderApnsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.PushProviderAPI.DeletePushProvider(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting push_provider_apns", err.Error())
		return
	}
}
