// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"net/http"
	"time"

	frameworkPath "github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource                = &hookKeyResource{}
	_ resource.ResourceWithConfigure   = &hookKeyResource{}
	_ resource.ResourceWithImportState = &hookKeyResource{}
)

// HookKeyResource defines the resource implementation.
type hookKeyResource struct {
	Config *config.Config
}

// HookKeyModel describes the resource data model.
type hookKeyModel struct {
	ID          types.String `tfsdk:"id"`
	Created     types.String `tfsdk:"created"`
	IsUsed      types.Bool   `tfsdk:"is_used"`
	KeyId       types.String `tfsdk:"key_id"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Name        types.String `tfsdk:"name"`
}

func NewHookKeyResource() resource.Resource {
	return &hookKeyResource{}
}

func (r *hookKeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_hook_key"
}

func (r *hookKeyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *hookKeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The Okta Key Management API provides a CRUD interface for JSON Web Keys (JWK) used with other parts of the application, such as inline hooks.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the key was created",
				Computed:    true,
			},
			"is_used": schema.BoolAttribute{
				Description: "Whether this key is currently in use by other applications",
				Computed:    true,
			},
			"key_id": schema.StringAttribute{
				Description: "The alias of the public key",
				Computed:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the key was updated",
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Description: "Display name of the key",
				Optional:    true,
			},
		},
	}
}
func (r *hookKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, frameworkPath.Root("id"), req, resp)
}

func (r *hookKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state hookKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	result, httpResp, err := client.HookKeyAPI.GetHookKey(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading hook_key", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsUsed = types.BoolValue(result.GetIsUsed())
	state.KeyId = types.StringValue(string(result.GetKeyId()))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}

	state.ID = types.StringValue(string(result.GetId()))

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *hookKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan hookKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan
	createReq := client.HookKeyAPI.CreateHookKey(ctx)
	body := okta.NewKeyRequestWithDefaults()
	body.SetName(plan.Name.ValueString())
	createReq = createReq.KeyRequest(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating hook_key", err.Error())
		return
	}
	// Set ID from API response
	plan.ID = types.StringValue(string(result.GetId()))
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.IsUsed = types.BoolValue(result.GetIsUsed())
	plan.KeyId = types.StringValue(string(result.GetKeyId()))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		plan.Name = types.StringValue(string(v))
	} else {
		plan.Name = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *hookKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan hookKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state hookKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()

	// Build request body from plan — only send changed fields
	updateReq := client.HookKeyAPI.ReplaceHookKey(ctx, id)
	updateBody := okta.NewKeyRequestWithDefaults()
	updateBody.SetName(plan.Name.ValueString())
	updateReq = updateReq.KeyRequest(*updateBody)
	result, _, err := updateReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating hook_key", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly and SkipRead fields skipped)
	state.ID = types.StringValue(string(result.GetId()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.IsUsed = types.BoolValue(result.GetIsUsed())
	state.KeyId = types.StringValue(string(result.GetKeyId()))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))
	if v := result.GetName(); v != "" {
		state.Name = types.StringValue(string(v))
	} else {
		state.Name = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *hookKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state hookKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()

	client := r.Config.OktaIDaaSClient.OktaSDKClient()
	httpResp, err := client.HookKeyAPI.DeleteHookKey(ctx, id).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			return
		}
		resp.Diagnostics.AddError("Error deleting hook_key", err.Error())
		return
	}
}
