// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccOktaApplicationGrant_basic(t *testing.T) {
	resourceName := "okta_application_grant.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		CheckDestroy:             testAccCheckOktaApplicationGrantDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccOktaApplicationGrantConfig_basic(),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckOktaApplicationGrantExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccOktaApplicationGrantConfig_basic() string {
	return `
resource "okta_application_grant" "test" {
  # app_id = "<app_id>"
	// TODO: Add required attributes
}
`
}

func testAccCheckOktaApplicationGrantExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		// TODO: Implement API call to verify resource exists
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// Retrieve parent param(s) from state attributes:
		// app_id := rs.Primary.Attributes["app_id"]
		// _, _, err := client.ApplicationGrantsAPI.GetScopeConsentGrant(context.Background(), app_id, rs.Primary.ID).Execute()
		// if err != nil {
		//     return fmt.Errorf("error getting application_grant: %v", err)
		// }

		return nil
	}
}

func testAccCheckOktaApplicationGrantDestroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "okta_application_grant" {
			continue
		}

		// TODO: Implement API call to verify resource is destroyed
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// Retrieve parent param(s) from state attributes:
		// app_id := rs.Primary.Attributes["app_id"]
		// _, httpResp, err := client.ApplicationGrantsAPI.GetScopeConsentGrant(context.Background(), app_id, rs.Primary.ID).Execute()
		// if err == nil {
		//     return fmt.Errorf("application_grant still exists: %s", rs.Primary.ID)
		// }
		// if httpResp != nil && httpResp.StatusCode != 404 {
		//     return fmt.Errorf("error checking application_grant destruction: %v", err)
		// }
	}
	return nil
}

// Ensure context is used
var _ = context.Background
