// Code generated by tf-generator. DO NOT EDIT.
package fwprovider

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/okta/terraform-provider-okta/okta/acctest"
)

func TestAccOktaApplicationSaml11_basic(t *testing.T) {
	resourceName := "okta_application_saml_11.test"

	resource.Test(t, resource.TestCase{
		PreCheck:                 acctest.AccPreCheck(t),
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactoriesForTestAcc(t),
		CheckDestroy:             testAccCheckOktaApplicationSaml11Destroy,
		Steps: []resource.TestStep{
			{
				Config: testAccOktaApplicationSaml11Config_basic(),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckOktaApplicationSaml11Exists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccOktaApplicationSaml11Config_basic() string {
	return `
resource "okta_application_saml_11" "test" {
	// TODO: Add required attributes
}
`
}

func testAccCheckOktaApplicationSaml11Exists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is not set")
		}

		// TODO: Implement API call to verify resource exists
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, _, err := client.ApplicationAPI.GetApplication(context.Background(), rs.Primary.ID).Execute()
		// if err != nil {
		//     return fmt.Errorf("error getting application_saml_11: %v", err)
		// }

		return nil
	}
}

func testAccCheckOktaApplicationSaml11Destroy(s *terraform.State) error {
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "okta_application_saml_11" {
			continue
		}

		// TODO: Implement API call to verify resource is destroyed
		// client := testAccProvider.Meta().(*config.Config).OktaIDaaSClient.OktaSDKClientV6()
		// _, httpResp, err := client.ApplicationAPI.GetApplication(context.Background(), rs.Primary.ID).Execute()
		// if err == nil {
		//     return fmt.Errorf("application_saml_11 still exists: %s", rs.Primary.ID)
		// }
		// if httpResp != nil && httpResp.StatusCode != 404 {
		//     return fmt.Errorf("error checking application_saml_11 destruction: %v", err)
		// }
	}
	return nil
}

// Ensure context is used
var _ = context.Background
