# See https://github.com/kentaro-m/auto-assign-action?tab=readme-ov-file#single-reviewers-list

addReviewers: true # add reviewers to pull requests

addAssignees: false # don't add assignees to pull requests

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - aditya-okta
  - dhiwakar-okta
  - pranav-okta

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1