dist: bionic
sudo: required
services:
  - docker
language: go

env:
  - GOFLAGS=-mod=vendor

install:
  - make build
  - make tools

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: '1.15.x'
      name: 'Code Lint'
      script: make lint
    - go: '1.15.x'
      name: 'Code Vet'
      script: make vet
    - go: '1.15.x'
      name: 'Code UnitTest'
      script: make test
