// Code generated by tf-generator. DO NOT EDIT.
package idaas

import (
	"context"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &iamAssigneesUserDataSource{}
	_ datasource.DataSourceWithConfigure = &iamAssigneesUserDataSource{}
)

// IamAssigneesUserDataSource defines the data source implementation.
type iamAssigneesUserDataSource struct {
	Config *config.Config
}

// IamAssigneesUserDataSourceModel describes the data source data model.
type iamAssigneesUserDataSourceModel struct {
	ID    types.String                                `tfsdk:"id"`
	Value []IamAssigneesUserDataSourceModelValueModel `tfsdk:"value"`
}

// IamAssigneesUserDataSourceModelValueModel is the nested model for value.
type IamAssigneesUserDataSourceModelValueModel struct {
	Id  types.String `tfsdk:"id"`
	Orn types.String `tfsdk:"orn"`
}

func NewIamAssigneesUserDataSource() datasource.DataSource {
	return &iamAssigneesUserDataSource{}
}

func (d *iamAssigneesUserDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_assignees_user"
}

func (d *iamAssigneesUserDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *iamAssigneesUserDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Fetches an Okta IamAssigneesUser resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the iam_assignees_user.",
				Optional:            true,
				Computed:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"value": schema.ListNestedBlock{
				Description: "Value",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "The ID of the user",
							Computed:    true,
						},
						"orn": schema.StringAttribute{
							Description: "ORN representing the assignee",
							Computed:    true,
						},
					},
				},
			},
		},
	}
}

func (d *iamAssigneesUserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state iamAssigneesUserDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClientV6()
	{
		results, httpResp, err := client.RoleAssignmentAUserAPI.ListUsersWithRoleAssignments(ctx).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No iam_assignees_user resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing iam_assignees_user", err.Error())
			return
		}
		items := results.GetValue()
		if len(items) == 0 {
			resp.Diagnostics.AddError("Not Found", "No iam_assignees_user resources were found.")
			return
		}
		result := items[0]
		state.ID = types.StringValue("iam_assignees_user")
		_ = result // IDExpr may not reference result; prevent "declared and not used"

	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
