// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package idaas

import (
	"context"
	"net/http"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/okta/terraform-provider-okta/okta/config"
)

var (
	_ datasource.DataSource              = &iamAssigneesUserDataSource{}
	_ datasource.DataSourceWithConfigure = &iamAssigneesUserDataSource{}
)

// IamAssigneesUserDataSource defines the data source implementation.
type iamAssigneesUserDataSource struct {
	Config *config.Config
}

// IamAssigneesUserItemModel is one element returned by the list endpoint.
type iamAssigneesUserItemModel struct {
	ID  types.String `tfsdk:"id"`
	Orn types.String `tfsdk:"orn"`
}

// IamAssigneesUserDataSourceModel describes the data source data model.
type iamAssigneesUserDataSourceModel struct {
	ID    types.String                `tfsdk:"id"`
	Items []iamAssigneesUserItemModel `tfsdk:"items"`
}

func newIamAssigneesUserDataSource() datasource.DataSource {
	return &iamAssigneesUserDataSource{}
}

func (d *iamAssigneesUserDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_assignees_user"
}

func (d *iamAssigneesUserDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.Config = dataSourceConfiguration(req, resp)
}

func (d *iamAssigneesUserDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Fetches an Okta IamAssigneesUser resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the iam_assignees_user.",
				Optional:            true,
				Computed:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"items": schema.ListNestedBlock{
				MarkdownDescription: "List of iam_assignees_user items.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{Computed: true},
						"orn": schema.StringAttribute{
							MarkdownDescription: "ORN representing the assignee",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *iamAssigneesUserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state iamAssigneesUserDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := d.Config.OktaIDaaSClient.OktaSDKClientV6()
	{
		results, httpResp, err := client.RoleAssignmentAUserAPI.ListUsersWithRoleAssignments(ctx).Execute()
		if err != nil {
			if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
				resp.Diagnostics.AddError("Not Found", "No iam_assignees_user resources were found.")
				return
			}
			resp.Diagnostics.AddError("Error listing iam_assignees_user", err.Error())
			return
		}
		allRawItems := results.GetValue()
		state.Items = make([]iamAssigneesUserItemModel, 0, len(allRawItems))
		for _i, result := range allRawItems {
			_ = _i
			_ = result
			item := iamAssigneesUserItemModel{}
			item.ID = types.StringValue(result.GetId())
			item.Orn = types.StringValue(result.GetOrn())
			state.Items = append(state.Items, item)
		}
		sort.Slice(state.Items, func(i, j int) bool {
			return state.Items[i].ID.ValueString() < state.Items[j].ID.ValueString()
		})
		state.ID = types.StringValue("okta_iam_assignees_user_list")
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
