// Copyright 2025 - Present Okta, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tf-generator. DO NOT EDIT.
package idaas

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	okta "github.com/okta/okta-sdk-golang/v6/okta"

	"github.com/okta/terraform-provider-okta/okta/config"
)

// Ensure interface compliance
var (
	_ resource.Resource              = &threatInsightSettingsResource{}
	_ resource.ResourceWithConfigure = &threatInsightSettingsResource{}
)

// ThreatInsightSettingsResource defines the resource implementation.
type threatInsightSettingsResource struct {
	Config *config.Config
}

// ThreatInsightSettingsModel describes the resource data model.
type threatInsightSettingsModel struct {
	ID           types.String `tfsdk:"id"`
	Action       types.String `tfsdk:"action"`
	Created      types.String `tfsdk:"created"`
	ExcludeZones types.List   `tfsdk:"exclude_zones"`
	LastUpdated  types.String `tfsdk:"last_updated"`
}

func newThreatInsightSettingsResource() resource.Resource {
	return &threatInsightSettingsResource{}
}

func (r *threatInsightSettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_threat_insight_settings"
}

func (r *threatInsightSettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Config = resourceConfiguration(req, resp)
}

func (r *threatInsightSettingsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "[Okta ThreatInsight](https://help.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The unique identifier for the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"action": schema.StringAttribute{
				Description: "Specifies how Okta responds to authentication requests from suspicious IP addresses",
				Required:    true,
			},
			"created": schema.StringAttribute{
				Description: "Timestamp when the ThreatInsight Configuration object was created",
				Computed:    true,
			},
			"exclude_zones": schema.ListAttribute{
				Description: "Accepts a list of [Network Zone](/openapi/okta-management/management/networkzone/) IDs.",
				ElementType: types.StringType,
				Optional:    true,
			},
			"last_updated": schema.StringAttribute{
				Description: "Timestamp when the ThreatInsight Configuration object was last updated",
				Computed:    true,
			},
		},
	}
}

func (r *threatInsightSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state threatInsightSettingsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClientV6()
	result, httpResp, err := client.ThreatInsightAPI.GetCurrentConfiguration(ctx).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading threat_insight_settings", err.Error())
		return
	}
	// Map API response fields to state (scalar types only; WriteOnly fields are skipped — response type doesn't have them)
	state.Action = types.StringValue(string(result.GetAction()))
	state.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	state.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))

	state.ID = types.StringValue("threat_insight_settings")

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *threatInsightSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan threatInsightSettingsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client := r.Config.OktaIDaaSClient.OktaSDKClientV6()

	// Build request body from plan
	createReq := client.ThreatInsightAPI.UpdateConfiguration(ctx)
	body := okta.NewThreatInsightConfigurationWithDefaults()
	body.SetAction(plan.Action.ValueString())
	if !plan.ExcludeZones.IsNull() && !plan.ExcludeZones.IsUnknown() {
		var excludeZonesSlice []string
		for _, item := range plan.ExcludeZones.Elements() {
			if sv, ok := item.(types.String); ok {
				excludeZonesSlice = append(excludeZonesSlice, sv.ValueString())
			}
		}
		body.SetExcludeZones(excludeZonesSlice)
	}
	createReq = createReq.ThreatInsightConfiguration(*body)
	result, _, err := createReq.Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating threat_insight_settings", err.Error())
		return
	}
	plan.ID = types.StringValue("threat_insight_settings")
	// Map response fields back to plan (scalar types only; WriteOnly and SkipRead fields skipped)
	plan.Action = types.StringValue(string(result.GetAction()))
	plan.Created = types.StringValue(result.GetCreated().Format(time.RFC3339))
	plan.LastUpdated = types.StringValue(result.GetLastUpdated().Format(time.RFC3339))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *threatInsightSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddWarning(
		"Update Not Supported",
		"This resource does not support in-place updates. Changes will require resource replacement.",
	)
}

func (r *threatInsightSettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning(
		"Delete Not Supported",
		"This resource cannot be deleted via Terraform.",
	)
}
