name: "Question"
labels: ["question"]
description: "If you have a question, please check out our [community resources](https://www.terraform.io/docs/extend/community/index.html)!"
body:
  - type: markdown
    attributes:
      value: |
        Issues on GitHub are intended to be related to bugs or feature requests with provider codebase, so we recommend using our other community resources instead of asking here 👍.

        If you have a support request or question please submit them to one of these resources:

        * [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
        * [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
        * [Okta support](https://support.okta.com/) for paid customers, else users can use the [Okta Community](https://devforum.okta.com/) for questions and support requests.
  - type: textarea
    id: question
    attributes:
      label: Question
      value: Please use the resources listed above instead of submitting a question with this form.
    validations:
      required: true

  - type: textarea
    id: customer_info
    attributes:
      label: Customer Information
      description: |
        Please provide your organization name, and whether you are a paid customer or using the free developer edition.
      value: |
        Organization Name: <your-org-name>
        Paid Customer: <yes/no>