name: Report a Documentation Error
description: Choose this option if you've found an error in the provider documentation or contributor guides.
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for raising a documentation issue!

        This form is meant to alert the maintainers to issues with the provider documentation found on the [Terraform Registry](https://registry.terraform.io/providers/okta/okta/latest) (such as resource and data source documentation, guides, and examples), or the [contributors guide](https://github.com/okta/terraform-provider-okta/blob/main/.github/CONTRIBUTING.md).

        We ask that you first [search existing issues](https://github.com/okta/terraform-provider-okta/labels/documentation-bug) and [pull requests](https://github.com/okta/terraform-provider-okta/pulls) to see if someone else may have already noticed the same issue or has already submitted a fix for it.

  - type: textarea
    id: registry_link
    attributes:
      label: Documentation Link(s)
      description: |
        Please link to the affected page(s) on the Terraform Registry or [contributors guide](https://github.com/okta/terraform-provider-okta/blob/main/.github/CONTRIBUTING.md).
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please leave a brief description of the documentation issue(s), including what the documentation currently says and, if possible, what it should say.
    validations:
      required: true

  - type: textarea
    id: customer_info
    attributes:
      label: Customer Information
      description: |
        Please provide your organization name, and whether you are a paid customer or using the free developer edition.
      value: |
        Organization Name: <your-org-name>
        Paid Customer: <yes/no>     

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to Okta documentation and/or other GitHub issues or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false
