package okta

var validNotificationTypes = []string{
	"CONNECTOR_AGENT", "USER_LOCKED_OUT", "APP_IMPORT", "LDAP_AGENT",
	"AD_AGENT", "OKTA_ANNOUNCEMENT", "OKTA_ISSUE", "OKTA_UPDATE", "IWA_AGENT", "USER_DEPROVISION",
	"REPORT_SUSPICIOUS_ACTIVITY", "RATELIMIT_NOTIFICATION", "AGENT_AUTO_UPDATE_NOTIFICATION",
}
