name: release
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ${{ fromJSON(vars.BW_RUNNER_GLORG_EKS_PROD_UBUNTU_2404_AMD64_XS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.0"

      - name: Run VCR acceptance tests
        run: time make smoke-test-play-vcr-acc
        timeout-minutes: 30

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          version: "v2.12.7"
          args: release --clean --parallelism 2 --skip=sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
